# -*- coding: utf-8 -*-
#!/usr/bin/env python3
import json

T = {
"311": {
  "fr": ("Le comportement est le meilleur miroir dans lequel chacun peut se voir.",
         "Maximes et reflexions",
         "Goethe observa un jeune poete qui se disait humble, mais interrompait chaque conversation. Il nota dans son journal : les mots peuvent mentir, les actes rarement. Le comportement revele ce que la bouche dissimule.",
         "Aujourd'hui, observez vos actes plutot que vos intentions. Ce que vous avez reellement fait en dit-il autant que ce que vous aviez prevu de faire ?"),
  "de": ("Das Verhalten ist der beste Spiegel, in dem jeder sich selbst sehen kann.",
         "Maximen und Reflexionen",
         "Goethe beobachtete einen jungen Dichter, der sich bescheiden nannte, aber jedes Gesprach unterbrach. Er notierte in seinem Tagebuch: Worte konnen lugen, Taten selten. Das Verhalten offenbart, was der Mund verbirgt.",
         "Beobachten Sie heute Ihre Handlungen statt Ihrer Absichten. Sagen Ihre tatsachlichen Taten genauso viel aus wie das, was Sie vorhatte zu tun?"),
  "es": ("El comportamiento es el mejor espejo en el que cada uno puede verse.",
         "Maximas y reflexiones",
         "Goethe observo a un joven poeta que se decia humilde pero interrumpia cada conversacion. Anoto en su diario: las palabras pueden mentir, los actos raramente. El comportamiento revela lo que la boca oculta.",
         "Hoy observa tus actos en lugar de tus intenciones. Lo que realmente hiciste, dice tanto como lo que planeabas hacer?"),
  "pt": ("O comportamento e o melhor espelho no qual cada um pode se ver.",
         "Maximas e reflexoes",
         "Goethe observou um jovem poeta que se dizia humilde, mas interrompia cada conversa. Anotou em seu diario: palavras podem mentir, atos raramente. O comportamento revela o que a boca oculta.",
         "Hoje observe seus atos em vez de suas intencoes. O que voce realmente fez diz tanto quanto o que planejava fazer?"),
},
"312": {
  "fr": ("La plupart des gens passent leur vie a fuir leur ombre plutot qu'a eclairer leur lumiere.",
         "L'homme et ses symboles",
         "Jung rencontra un homme d'affaires prospere qui souffrait d'une depression inexpliquee. En explorant ses reves, ils decouvrirent une ambition creAtrice etouffee depuis l'enfance. Jung ecrivit : ce que nous refoulons ne disparait pas — il grandit dans l'ombre.",
         "Notez une qualite que vous critiquez souvent chez les autres. Demandez-vous honnêtement : est-ce quelque chose que vous niez en vous-meme ?"),
  "de": ("Die meisten Menschen verbringen ihr Leben damit, ihrem Schatten zu entfliehen, anstatt ihr Licht zu erhellen.",
         "Der Mensch und seine Symbole",
         "Jung traf einen erfolgreichen Geschaftsmann, der an einer unerklarlichen Depression litt. Bei der Erforschung seiner Traume entdeckten sie eine seit der Kindheit unterdrueckte kreative Ambition. Jung schrieb: Was wir verdraengen verschwindet nicht — es wachst im Schatten.",
         "Notieren Sie eine Eigenschaft, die Sie haufig an anderen kritisieren. Fragen Sie sich ehrlich: Ist das etwas, das Sie in sich selbst leugnen?"),
  "es": ("La mayoria de las personas pasan su vida huyendo de su sombra en lugar de iluminar su luz.",
         "El hombre y sus simbolos",
         "Jung encontro a un exitoso hombre de negocios que sufria de una depresion inexplicable. Al explorar sus suenos, descubrieron una ambicion creativa reprimida desde la infancia. Jung escribio: lo que reprimimos no desaparece, crece en la sombra.",
         "Anota una cualidad que criticas frecuentemente en otros. Preguntate honestamente: es algo que niegas en ti mismo?"),
  "pt": ("A maioria das pessoas passa a vida fugindo de sua sombra em vez de iluminar sua luz.",
         "O homem e seus simbolos",
         "Jung encontrou um homem de negocios bem-sucedido que sofria de uma depressao inexplicavel. Ao explorar seus sonhos, descobriram uma ambicao criativa reprimida desde a infancia. Jung escreveu: o que reprimimos nao desaparece, cresce na sombra.",
         "Anote uma qualidade que voce critica com frequencia nos outros. Pergunte-se honestamente: e algo que voce nega em si mesmo?"),
},
"313": {
  "fr": ("Nous ne voyons pas le monde tel qu'il est, mais tel que nous sommes.",
         "Journal, 1941",
         "Nin observa deux lecteurs lire le meme livre : l'un en ressortit inspire, l'autre deprime. Elle nota que le texte n'avait pas change — seuls les lecteurs differaient. Cette observation devint le coeur de sa philosophie : nos filtres interieurs colorent tout.",
         "Choisissez une situation recente qui vous a contrarie. Demandez-vous : qu'est-ce que ma reaction dit de moi, et non de la situation ?"),
  "de": ("Wir sehen die Welt nicht so, wie sie ist, sondern so, wie wir sind.",
         "Tagebuch, 1941",
         "Nin beobachtete zwei Leser, die dasselbe Buch lasen: einer kam inspiriert heraus, der andere deprimiert. Sie stellte fest, dass der Text sich nicht verandert hatte - nur die Leser unterschieden sich. Diese Beobachtung wurde zum Kern ihrer Philosophie: unsere inneren Filter farben alles.",
         "Wahlen Sie eine kurzlich erlebte Situation, die Sie geargert hat. Fragen Sie sich: Was sagt meine Reaktion uber mich aus, und nicht uber die Situation?"),
  "es": ("No vemos el mundo como es, sino como somos.",
         "Diario, 1941",
         "Nin observo a dos lectores leer el mismo libro: uno salio inspirado, el otro deprimido. Noto que el texto no habia cambiado, solo diferian los lectores. Esta observacion se convirtio en el nucleo de su filosofia: nuestros filtros internos colorean todo.",
         "Elige una situacion reciente que te molesto. Preguntate: que dice mi reaccion sobre mi, y no sobre la situacion?"),
  "pt": ("Nao vemos o mundo como ele e, mas como nos somos.",
         "Diario, 1941",
         "Nin observou dois leitores ler o mesmo livro: um saiu inspirado, o outro deprimido. Percebeu que o texto nao mudara, apenas os leitores diferiam. Essa observacao tornou-se o nucleo de sua filosofia: nossos filtros internos colorem tudo.",
         "Escolha uma situacao recente que te incomodou. Pergunte-se: o que minha reacao diz sobre mim, e nao sobre a situacao?"),
},
"314": {
  "fr": ("Le critique interieur est le tyran le plus cruel auquel la plupart des gens obeissent sans jamais l'avoir elu.",
         "Ne vous disputez pas avec votre esprit",
         "Carson travaillait avec un cadre superieur qui ne pouvait pas terminer un seul projet sans se dire qu'il etait insuffisant. En cartographiant la voix interieure du patient, ils decouvrirent qu'elle appartenait a son pere. Carson nota : nous vivons souvent sous la dictature de voix heritees.",
         "Aujourd'hui, notez la premiere pensee negative que vous avez sur vous-meme. Posez-vous cette question : qui vous a dit cela pour la premiere fois ?"),
  "de": ("Der innere Kritiker ist der grausamste Tyrann, dem die meisten Menschen gehorchen, ohne ihn je gewahlt zu haben.",
         "Streite nicht mit deinem Geist",
         "Carson arbeitete mit einem leitenden Angestellten, der kein einziges Projekt abschliessen konnte, ohne sich zu sagen, er sei unzulanglich. Beim Kartieren der inneren Stimme des Patienten entdeckten sie, dass sie seinem Vater gehorte. Carson notierte: Wir leben oft unter der Diktatur geerbter Stimmen.",
         "Notieren Sie heute den ersten negativen Gedanken, den Sie uber sich haben. Stellen Sie sich diese Frage: Wer hat Ihnen das zuerst gesagt?"),
  "es": ("El critico interior es el tirano mas cruel al que la mayoria de las personas obedece sin haberlo elegido jamas.",
         "No discutas con tu mente",
         "Carson trabajaba con un alto directivo que no podia terminar ni un solo proyecto sin decirse que era insuficiente. Al mapear la voz interior del paciente, descubrieron que pertenecia a su padre. Carson anoto: vivimos frecuentemente bajo la dictadura de voces heredadas.",
         "Hoy anota el primer pensamiento negativo que tengas sobre ti mismo. Hazte esta pregunta: quien te dijo eso por primera vez?"),
  "pt": ("O critico interno e o tirano mais cruel ao qual a maioria das pessoas obedece sem jamas te-lo eleito.",
         "Nao discuta com sua mente",
         "Carson trabalhava com um executivo senior que nao conseguia terminar nenhum projeto sem se dizer que era insuficiente. Ao mapear a voz interior do paciente, descobriram que ela pertencia a seu pai. Carson anotou: vivemos frequentemente sob a ditadura de vozes herdadas.",
         "Hoje anote o primeiro pensamento negativo que tiver sobre voce mesmo. Faca esta pergunta: quem te disse isso pela primeira vez?"),
},
"315": {
  "fr": ("Le bonheur n'est pas quelque chose qu'on trouve. C'est quelque chose qu'on construit.",
         "La force de l'optimisme",
         "Seligman avait initialement etudie la depression. Apres des decennies de recherche, il remarqua que les patients qui guerissaient completement avaient une chose en commun : ils avaient commence a construire quelque chose — une relation, un projet, une signification.",
         "Nommez une chose que vous construisez actuellement qui vous donne de la satisfaction. Si vous n'en trouvez pas, choisissez-en une petite aujourd'hui."),
  "de": ("Gluck ist nicht etwas, das man findet. Es ist etwas, das man aufbaut.",
         "Flourish: Wie Menschen aufbluhen",
         "Seligman hatte ursprunglich Depression erforscht. Nach Jahrzehnten der Forschung bemerkte er, dass Patienten, die vollstandig genasen, eines gemeinsam hatten: Sie hatten begonnen, etwas aufzubauen — eine Beziehung, ein Projekt, eine Bedeutung.",
         "Nennen Sie etwas, das Sie gerade aufbauen und das Ihnen Befriedigung gibt. Falls Sie nichts finden, wahlen Sie heute eine kleine Sache aus."),
  "es": ("La felicidad no es algo que encuentras. Es algo que construyes.",
         "La fuerza del optimismo",
         "Seligman habia estudiado originalmente la depresion. Tras decadas de investigacion, noto que los pacientes que sanaban por completo tenian algo en comun: habian comenzado a construir algo: una relacion, un proyecto, un significado.",
         "Nombra algo que estas construyendo actualmente que te da satisfaccion. Si no encuentras nada, elige algo pequeno hoy."),
  "pt": ("A felicidade nao e algo que se encontra. E algo que se constroi.",
         "Florescer: como as pessoas prosperam",
         "Seligman tinha originalmente estudado a depressao. Apos decadas de pesquisa, percebeu que os pacientes que se curavam completamente tinham algo em comum: haviam comecado a construir algo — uma relacao, um projeto, um significado.",
         "Nomeie algo que voce esta construindo atualmente que lhe da satisfacao. Se nao encontrar nada, escolha algo pequeno hoje."),
},
"316": {
  "fr": ("On ne peut pas changer ce que l'on n'accepte pas.",
         "L'ame et la vie",
         "Jung travaillait avec un patient alcoolo qui refusait d'admettre sa dependance. Pendant des mois, ils tournerent en rond. Le jour ou le patient dit 'je suis alcoolique', quelque chose changea. Jung nota : l'acceptation n'est pas la capitulation, c'est le debut du pouvoir.",
         "Nommez une situation dans votre vie que vous n'avez pas encore acceptee. Ecrivez : j'accepte que cela soit ainsi maintenant. Remarquez comment vous vous sentez."),
  "de": ("Man kann nicht verandern, was man nicht akzeptiert.",
         "Seele und Leben",
         "Jung arbeitete mit einem alkoholkranken Patienten, der seine Abhangigkeit nicht zugeben wollte. Monatelang drehten sie sich im Kreis. An dem Tag, als der Patient sagte 'Ich bin Alkoholiker', anderte sich etwas. Jung notierte: Akzeptanz ist nicht Kapitulation, sie ist der Beginn der Kraft.",
         "Nennen Sie eine Situation in Ihrem Leben, die Sie noch nicht akzeptiert haben. Schreiben Sie: Ich akzeptiere, dass es jetzt so ist. Beachten Sie, wie Sie sich dabei fuhlen."),
  "es": ("No se puede cambiar lo que no se acepta.",
         "Alma y vida",
         "Jung trabajaba con un paciente alcoholico que se negaba a admitir su dependencia. Durante meses giraron en circulos. El dia que el paciente dijo 'soy alcoholico', algo cambio. Jung anoto: la aceptacion no es capitulacion, es el comienzo del poder.",
         "Nombra una situacion en tu vida que aun no hayas aceptado. Escribe: acepto que esto es asi ahora. Observa como te sientes."),
  "pt": ("Nao se pode mudar o que nao se aceita.",
         "Alma e vida",
         "Jung trabalhava com um paciente alcoolatra que se recusava a admitir sua dependencia. Durante meses giraram em circulos. No dia em que o paciente disse 'sou alcoolatra', algo mudou. Jung anotou: a aceitacao nao e capitulacao, e o inicio do poder.",
         "Nomeie uma situacao em sua vida que voce ainda nao aceitou. Escreva: aceito que isso e assim agora. Observe como se sente."),
},
"317": {
  "fr": ("La peur n'est pas un ennemi. C'est une information sur ce qui est important.",
         "Le don de la peur",
         "De Becker etudia des centaines de cas ou des personnes avaient survecu a des situations dangereuses. Dans presque tous les cas, elles avaient ressenti une peur avant l'evenement qu'elles avaient ignoree. Il conclut : la peur naturelle est toujours pertinente.",
         "La prochaine fois que vous ressentez une inquietude inexpliquee, arretez-vous et demandez : quelle information cette peur me transmet-elle ?"),
  "de": ("Angst ist kein Feind. Sie ist eine Information daruber, was wichtig ist.",
         "Das Geschenk der Angst",
         "De Becker untersuchte Hunderte von Fallen, in denen Menschen gefaehrliche Situationen ueberlebt hatten. In fast allen Fallen hatten sie eine Angst vor dem Ereignis gespuert, die sie ignoriert hatten. Er schloss: Naturliche Angst ist immer relevant.",
         "Wenn Sie das nachste Mal eine unerklaerliche Besorgnis verspuren, halten Sie inne und fragen Sie: Welche Information vermittelt mir diese Angst?"),
  "es": ("El miedo no es un enemigo. Es informacion sobre lo que importa.",
         "El regalo del miedo",
         "De Becker estudio cientos de casos en que personas habian sobrevivido situaciones peligrosas. En casi todos los casos, habian sentido un miedo antes del evento que ignoraron. Concluyo: el miedo natural siempre es relevante.",
         "La proxima vez que sientas una inquietud inexplicable, detente y pregunta: que informacion me esta transmitiendo este miedo?"),
  "pt": ("O medo nao e um inimigo. E uma informacao sobre o que e importante.",
         "O dom do medo",
         "De Becker estudou centenas de casos em que pessoas sobreviveram a situacoes perigosas. Em quase todos os casos, elas sentiram um medo antes do evento que ignoraram. Concluiu: o medo natural e sempre relevante.",
         "Da proxima vez que sentir uma preocupacao inexplicavel, pare e pergunte: que informacao esse medo esta me transmitindo?"),
},
"318": {
  "fr": ("Nous acceptons l'amour que nous pensons meriter.",
         "Les avantages d'etre un garcon efface",
         "Le protagoniste du roman de Chbosky observe sa tante qui reste avec un homme qui la maltraite. Il ne comprend pas pourquoi — jusqu'au moment ou il realise qu'elle croit au fond d'elle qu'elle ne merite pas mieux. Cette phrase est devenue l'une des plus citees de la litterature young adult.",
         "Pensez a la facon dont vous etes traite dans vos relations les plus proches. Est-ce coherent avec ce que vous croyez meriter au fond de vous ?"),
  "de": ("Wir akzeptieren die Liebe, von der wir glauben, dass wir sie verdienen.",
         "Vorzuge des Unsichtbarseins",
         "Der Protagonist in Chboskys Roman beobachtet seine Tante, die bei einem Mann bleibt, der sie misshandelt. Er versteht nicht warum — bis er erkennt, dass sie im Inneren glaubt, nichts Besseres zu verdienen. Dieser Satz wurde zu einem der meistzitierten der Jugendliteratur.",
         "Denken Sie daran, wie Sie in Ihren engsten Beziehungen behandelt werden. Entspricht das dem, was Sie tief im Inneren glauben zu verdienen?"),
  "es": ("Aceptamos el amor que creemos merecer.",
         "Las ventajas de ser invisible",
         "El protagonista de la novela de Chbosky observa a su tia que permanece con un hombre que la maltrata. No entiende por que, hasta que se da cuenta de que ella cree en el fondo que no merece algo mejor. Esta frase se convirtio en una de las mas citadas de la literatura juvenil.",
         "Piensa en como eres tratado en tus relaciones mas cercanas. Es coherente con lo que crees merecer en el fondo?"),
  "pt": ("Aceitamos o amor que achamos que merecemos.",
         "As vantagens de ser invisivel",
         "O protagonista do romance de Chbosky observa sua tia que permanece com um homem que a maltrata. Nao entende por que, ate perceber que ela acredita no fundo que nao merece algo melhor. Essa frase tornou-se uma das mais citadas da literatura juvenil.",
         "Pense em como e tratado em seus relacionamentos mais proximos. E coerente com o que voce acredita merecer no fundo?"),
},
"319": {
  "fr": ("Ce n'est pas toi qui penses les pensees — ce sont les pensees qui te pensent.",
         "Dhammapada",
         "Un moine bouddhiste demanda au Bouddha comment arreter les pensees negativos. Bouddha repondit : essaie d'arreter le vent. Les pensees viennent et vont comme des nuages — ta tache n'est pas de les arreter, mais de ne pas te confondre avec elles.",
         "Asseyez-vous 5 minutes en silence. Observez une pensee qui apparait. Rappelez-vous : je ne suis pas cette pensee, j'observe cette pensee."),
  "de": ("Nicht du denkst die Gedanken — die Gedanken denken dich.",
         "Dhammapada",
         "Ein buddhistischer Monch fragte den Buddha, wie er negative Gedanken aufhalten konnte. Buddha antwortete: Versuche den Wind anzuhalten. Gedanken kommen und gehen wie Wolken — deine Aufgabe ist nicht, sie zu stoppen, sondern dich nicht mit ihnen zu verwechseln.",
         "Sitzen Sie 5 Minuten still. Beobachten Sie einen Gedanken, der auftaucht. Erinnern Sie sich: Ich bin nicht dieser Gedanke, ich beobachte diesen Gedanken."),
  "es": ("No eres tu quien piensa los pensamientos: son los pensamientos quienes te piensan.",
         "Dhammapada",
         "Un monje budista le pregunto a Buda como detener los pensamientos negativos. Buda respondio: intenta detener el viento. Los pensamientos vienen y van como nubes; tu tarea no es detenerlos, sino no confundirte con ellos.",
         "Siéntate 5 minutos en silencio. Observa un pensamiento que aparece. Recuerda: yo no soy ese pensamiento, observo ese pensamiento."),
  "pt": ("Nao es tu quem pensa os pensamentos: sao os pensamentos que te pensam.",
         "Dhammapada",
         "Um monge budista perguntou ao Buda como parar os pensamentos negativos. Buda respondeu: tente parar o vento. Os pensamentos vem e vao como nuvens; sua tarefa nao e para-los, mas nao se confundir com eles.",
         "Sente-se 5 minutos em silencio. Observe um pensamento que aparece. Lembre-se: eu nao sou esse pensamento, observo esse pensamento."),
},
"320": {
  "fr": ("Les emotions sont des donnees, pas des directives.",
         "Agilite emotionnelle",
         "David travaillait avec une dirigeante qui supprimait toute emotion au travail, pensant que cela la rendrait plus efficace. Mais son equipe la percevait comme froide et peu fiable. Paradoxalement, quand elle commenca a nommer ses emotions, la confiance augmenta.",
         "Aujourd'hui, nommez trois emotions que vous ressentez. Notez-les sans jugement. Que signalent-elles sur ce qui compte pour vous ?"),
  "de": ("Emotionen sind Daten, keine Direktiven.",
         "Emotionale Beweglichkeit",
         "David arbeitete mit einer Fuhrungskraft, die alle Emotionen bei der Arbeit unterdrueckte, weil sie dachte, das wurde sie effizienter machen. Aber ihr Team nahm sie als kalt und unzuverlassig wahr. Paradoxerweise stieg das Vertrauen, als sie begann, ihre Emotionen zu benennen.",
         "Benennen Sie heute drei Emotionen, die Sie gerade fuhlen. Notieren Sie sie ohne Urteil. Was signalisieren sie uber das, was Ihnen wichtig ist?"),
  "es": ("Las emociones son datos, no directivas.",
         "Agilidad emocional",
         "David trabajaba con una directiva que suprimia toda emocion en el trabajo, creyendo que eso la haria mas eficiente. Pero su equipo la percibia como fria y poco fiable. Paradojicamente, cuando empezo a nombrar sus emociones, la confianza aumento.",
         "Hoy nombra tres emociones que estas sintiendo. Anotalas sin juicio. Que senalan sobre lo que importa para ti?"),
  "pt": ("As emocoes sao dados, nao diretivas.",
         "Agilidade emocional",
         "David trabalhava com uma executiva que suprimia toda emocao no trabalho, acreditando que isso a tornaria mais eficiente. Mas sua equipe a percebia como fria e pouco confivel. Paradoxalmente, quando ela comecou a nomear suas emocoes, a confianca aumentou.",
         "Hoje nomeie tres emocoes que esta sentindo. Anote-as sem julgamento. O que elas sinalizam sobre o que importa para voce?"),
},
"321": {
  "fr": ("La plupart des gens n'ecoutent pas — ils attendent leur tour de parler.",
         "Le vieil homme et la mer",
         "Hemingway remarqua ce pattern pendant des annees de journalisme : les gens pretendaient ecouter, mais leurs yeux trahissaient l'attente. Il entraina lui-meme sa capacite d'ecoute en passant des soirees entiere a ne poser que des questions.",
         "Dans votre prochaine conversation importante, comptez combien de fois vous etes sur le point de parler mais vous retenez pour ecouter davantage."),
  "de": ("Die meisten Menschen horen nicht zu — sie warten darauf, an der Reihe zu sein zu sprechen.",
         "Der alte Mann und das Meer",
         "Hemingway bemerkte dieses Muster uber Jahre des Journalismus: Die Menschen taten so, als wurden sie zuhoren, aber ihre Augen verrieten das Warten. Er trainierte seine eigene Zuhorfahigkeit, indem er ganze Abende damit verbrachte, nur Fragen zu stellen.",
         "Zahlen Sie in Ihrem nachsten wichtigen Gesprach, wie oft Sie kurz davor sind zu sprechen, sich aber zuruckhalten, um mehr zuzuhoren."),
  "es": ("La mayoria de las personas no escucha: espera su turno para hablar.",
         "El viejo y el mar",
         "Hemingway noto este patron durante anos de periodismo: las personas fingian escuchar, pero sus ojos traicionaban la espera. El mismo entrenaba su capacidad de escucha pasando veladas enteras solo haciendo preguntas.",
         "En tu proxima conversacion importante, cuenta cuantas veces estas a punto de hablar pero te contienes para escuchar mas."),
  "pt": ("A maioria das pessoas nao escuta: espera sua vez de falar.",
         "O velho e o mar",
         "Hemingway notou esse padrao durante anos de jornalismo: as pessoas fingiam ouvir, mas seus olhos traiam a espera. Ele mesmo treinava sua capacidade de escuta passando noites inteiras apenas fazendo perguntas.",
         "Na sua proxima conversa importante, conte quantas vezes esta prestes a falar mas se contem para ouvir mais."),
},
"322": {
  "fr": ("L'etat d'esprit de croissance fait du processus d'apprentissage — et non du resultat — la source de la fierte.",
         "Mindset : changer votre etat d'esprit",
         "Dweck etudia deux groupes d'enfants : ceux qu'on felicitait pour leur intelligence et ceux qu'on felicitait pour leurs efforts. Face a des taches difficiles, le premier groupe abandonnait, le deuxieme persistait. La conclusion : louer l'effort, non le talent, change la trajectoire.",
         "La prochaine fois que vous echouez a quelque chose, remplacez 'je suis mauvais en cela' par 'je n'y suis pas encore arrive'."),
  "de": ("Die Wachstumsmentalitat macht den Lernprozess — nicht das Ergebnis — zur Quelle des Stolzes.",
         "Mindset: Wie wir unser Potenzial entfalten",
         "Dweck untersuchte zwei Gruppen von Kindern: diejenigen, die fur ihre Intelligenz gelobt wurden, und diejenigen, die fur ihre Bemuehungen gelobt wurden. Bei schwierigen Aufgaben gab die erste Gruppe auf, die zweite blieb dran. Das Fazit: Anstrengung zu loben, nicht Talent, verandert die Entwicklung.",
         "Wenn Sie das nachste Mal an etwas scheitern, ersetzen Sie 'Ich bin schlecht darin' durch 'Ich bin noch nicht dort angekommen'."),
  "es": ("La mentalidad de crecimiento convierte el proceso de aprendizaje, no el resultado, en la fuente del orgullo.",
         "Mindset: la actitud del exito",
         "Dweck estudio dos grupos de ninos: los que eran elogiados por su inteligencia y los que eran elogiados por sus esfuerzos. Ante tareas dificiles, el primer grupo abandonaba, el segundo persistia. La conclusion: elogiar el esfuerzo, no el talento, cambia la trayectoria.",
         "La proxima vez que falles en algo, reemplaza 'soy malo en esto' por 'aun no lo he logrado'."),
  "pt": ("A mentalidade de crescimento faz do processo de aprendizagem, nao do resultado, a fonte do orgulho.",
         "Mindset: a nova psicologia do sucesso",
         "Dweck estudou dois grupos de criancas: as elogiadas por sua inteligencia e as elogiadas por seus esforos. Diante de tarefas dificeis, o primeiro grupo desistia, o segundo persistia. A conclusao: elogiar o esforco, nao o talento, muda a trajetoria.",
         "Da proxima vez que falhar em algo, substitua 'sou ruim nisso' por 'ainda nao cheguei la'."),
},
"323": {
  "fr": ("Ce dont nous ne sommes pas conscients nous controle. Ce dont nous sommes conscients, nous le controlons.",
         "Psychologie de l'inconscient",
         "Jung traita un homme qui sabotait repetitivement ses relations amoureuses. Chaque partenaire finissait par 'trop exiger'. En travaillant ensemble, ils decouvrirent que l'homme avait peur profonde de l'abandon — une peur si inconsciente qu'elle operait sans son consentement.",
         "Identifiez un comportement que vous repetez dans diverses situations et que vous n'aimez pas. Demandez-vous : de quelle peur cachee ce comportement vous protege-t-il ?"),
  "de": ("Was uns nicht bewusst ist, kontrolliert uns. Was uns bewusst ist, kontrollieren wir.",
         "Psychologie des Unbewussten",
         "Jung behandelte einen Mann, der wiederholt seine Liebesbeziehungen sabotierte. Jeder Partner verlangte am Ende 'zu viel'. Beim gemeinsamen Arbeiten entdeckten sie, dass der Mann eine tiefe Angst vor Verlassenwerden hatte — eine Angst, die so unbewusst war, dass sie ohne sein Wissen operierte.",
         "Identifizieren Sie ein Verhalten, das Sie in verschiedenen Situationen wiederholen und das Ihnen nicht gefallt. Fragen Sie sich: Vor welcher versteckten Angst schutzt Sie dieses Verhalten?"),
  "es": ("Lo que no somos conscientes nos controla. Lo que somos conscientes, lo controlamos.",
         "Psicologia del inconsciente",
         "Jung trataba a un hombre que saboteaba repetidamente sus relaciones amorosas. Cada pareja terminaba exigiendo 'demasiado'. Trabajando juntos, descubrieron que el hombre tenia un miedo profundo al abandono, tan inconsciente que operaba sin su consentimiento.",
         "Identifica un comportamiento que repites en diversas situaciones y que no te gusta. Preguntate: de que miedo oculto te protege este comportamiento?"),
  "pt": ("O que nao somos conscientes nos controla. O que somos conscientes, controlamos.",
         "Psicologia do inconsciente",
         "Jung tratou um homem que sabotava repetidamente seus relacionamentos amorosos. Cada parceiro acabava exigindo 'demais'. Trabalhando juntos, descobriram que o homem tinha um medo profundo de abandono, tao inconsciente que operava sem seu consentimento.",
         "Identifique um comportamento que repete em diversas situacoes e que nao gosta. Pergunte-se: de que medo oculto esse comportamento te protege?"),
},
"324": {
  "fr": ("La forme la plus repandue du desespoir est l'incapacite d'etre soi-meme.",
         "La maladie mortelle",
         "Kierkegaard observa des hommes d'eglise qui predichaient la vertu mais vivaient dans l'automatisme. Il diagnostiqua ce qu'il appela le 'desespoir' — non pas le sentiment de tristesse, mais la condition d'etre desaligne avec sa verite interieure.",
         "Pensez a la difference entre qui vous etes reellement et qui vous pretendez etre dans votre vie quotidienne. Nommez un endroit ou cet ecart est le plus grand."),
  "de": ("Die verbreitetste Form der Verzweiflung ist die Unfahigkeit, man selbst zu sein.",
         "Die Krankheit zum Tode",
         "Kierkegaard beobachtete Kirchenmanner, die Tugend predigten, aber im Automatismus lebten. Er diagnostizierte, was er 'Verzweiflung' nannte — nicht das Gefuhl der Traurigkeit, sondern den Zustand des Nichteinklangs mit der inneren Wahrheit.",
         "Denken Sie an den Unterschied zwischen dem, wer Sie wirklich sind, und dem, wer Sie im Alltag vorgeben zu sein. Nennen Sie einen Ort, wo diese Lucke am grossten ist."),
  "es": ("La forma mas extendida de desesperacion es la incapacidad de ser uno mismo.",
         "La enfermedad mortal",
         "Kierkegaard observo a hombres de iglesia que predicaban la virtud pero vivian en el automatismo. Diagnostico lo que llamo 'desesperacion': no el sentimiento de tristeza, sino el estado de desalineacion con la verdad interior.",
         "Piensa en la diferencia entre quien realmente eres y quien finges ser en tu vida cotidiana. Nombra un lugar donde esa brecha es mayor."),
  "pt": ("A forma mais comum de desespero e a incapacidade de ser si mesmo.",
         "A doenca ate a morte",
         "Kierkegaard observou homens da igreja que pregavam a virtude mas viviam no automatismo. Diagnosticou o que chamou de 'desespero': nao o sentimento de tristeza, mas o estado de desalinhamento com a verdade interior.",
         "Pense na diferenca entre quem voce realmente e e quem finge ser em sua vida cotidiana. Nomeie um lugar onde essa lacuna e maior."),
},
"325": {
  "fr": ("Les habitudes sont simplement des decisions automatisees sur la facon de se comporter.",
         "Le pouvoir des habitudes",
         "Duhigg etudia les habitudes d'une femme qui fumait depuis des annees et n'arretait pas. Ils decouvrirent que la cigarette n'etait pas la dependance reelle — c'etait le rituel de sortir du bureau pour socialiser. Quand ils ont cree un rituel de remplacement, elle a arrete en 3 semaines.",
         "Choisissez une habitude negative. Identifiez la recompense qu'elle vous procure. Trouvez une action differente qui donne la meme recompense."),
  "de": ("Gewohnheiten sind einfach automatisierte Entscheidungen daruber, wie man sich verhalt.",
         "Die Macht der Gewohnheit",
         "Duhigg studierte die Gewohnheiten einer Frau, die seit Jahren rauchte und nicht aufhoren konnte. Sie entdeckten, dass Rauchen nicht die eigentliche Sucht war — es war das Ritual, das Buro zu verlassen, um zu sozialisieren. Als sie ein Ersatzritual schufen, hort sie in 3 Wochen auf.",
         "Wahlen Sie eine negative Gewohnheit. Identifizieren Sie die Belohnung, die sie Ihnen gibt. Finden Sie eine andere Handlung, die dieselbe Belohnung bringt."),
  "es": ("Los habitos son simplemente decisiones automatizadas sobre como comportarse.",
         "El poder de los habitos",
         "Duhigg estudio los habitos de una mujer que llevaba anos fumando y no podia dejar. Descubrieron que fumar no era la verdadera adiccion, sino el ritual de salir de la oficina para socializar. Cuando crearon un ritual sustituto, lo dejo en 3 semanas.",
         "Elige un habito negativo. Identifica la recompensa que te da. Encuentra una accion diferente que proporcione la misma recompensa."),
  "pt": ("Habitos sao simplesmente decisoes automatizadas sobre como se comportar.",
         "O poder do habito",
         "Duhigg estudou os habitos de uma mulher que fumava ha anos e nao conseguia parar. Descobriram que fumar nao era o vicio real, mas o ritual de sair do escritorio para socializar. Quando criaram um ritual substituto, ela parou em 3 semanas.",
         "Escolha um habito negativo. Identifique a recompensa que ele te da. Encontre uma acao diferente que proporcione a mesma recompensa."),
},
"326": {
  "fr": ("L'anxiete est l'imagination au service de la peur.",
         "Vivre sans anxiete",
         "Honner travaillait avec un entrepreneur qui souffrait d'attaques de panique avant chaque grande presentation. En examinant ses pensees, ils decouvrirent que son imagination construisait des scenarios catastrophiques detailles. Elle lui apprit a utiliser cette meme imagination pour des scenarios positifs.",
         "La prochaine fois que vous vous sentez anxieux, ecrivez le scenario que votre imagination cree. Puis ecrivez un scenario alternatif avec le meme niveau de detail."),
  "de": ("Angst ist Vorstellungskraft im Dienst der Furcht.",
         "Leben ohne Angst",
         "Honner arbeitete mit einem Unternehmer, der vor jeder grossen Prasentation Panikattacken erlitt. Bei der Untersuchung seiner Gedanken entdeckten sie, dass seine Vorstellungskraft detaillierte Katastrophenszenarien aufbaute. Sie lehrte ihn, dieselbe Vorstellungskraft fur positive Szenarien zu nutzen.",
         "Wenn Sie das nachste Mal Angst verspuren, schreiben Sie das Szenario auf, das Ihre Vorstellungskraft erstellt. Schreiben Sie dann ein alternatives Szenario mit dem gleichen Detailgrad."),
  "es": ("La ansiedad es la imaginacion al servicio del miedo.",
         "Vivir sin ansiedad",
         "Honner trabajaba con un emprendedor que sufria ataques de panico antes de cada gran presentacion. Al examinar sus pensamientos, descubrieron que su imaginacion construia escenarios catastroficos detallados. Ella le enseno a usar esa misma imaginacion para escenarios positivos.",
         "La proxima vez que te sientas ansioso, escribe el escenario que tu imaginacion crea. Luego escribe un escenario alternativo con el mismo nivel de detalle."),
  "pt": ("A ansiedade e a imaginacao a servico do medo.",
         "Viver sem ansiedade",
         "Honner trabalhava com um empreendedor que sofria ataques de panico antes de cada grande apresentacao. Ao examinar seus pensamentos, descobriram que sua imaginacao construia cenarios catastroficos detalhados. Ela o ensinou a usar essa mesma imaginacao para cenarios positivos.",
         "Da proxima vez que se sentir ansioso, escreva o cenario que sua imaginacao cria. Em seguida escreva um cenario alternativo com o mesmo nivel de detalhe."),
},
"327": {
  "fr": ("L'homme est tout ce qu'il aurait pu etre et n'est pas devenu.",
         "L'existentialisme est un humanisme",
         "Sartre donna une conference apres la Seconde Guerre mondiale ou il rejeta l'idee que la nature humaine predetermine le destin. Il provoqua le public : vous etes ce que vous faites, pas ce que vous planifiez. La salle etait divisee — mais chacun repartit avec une question.",
         "Nommez une chose que vous avez toujours voulu faire mais que vous reportez. Fixez une date precise pour commencer — pas quand les conditions seront parfaites."),
  "de": ("Der Mensch ist alles, was er hatte sein konnen und nicht geworden ist.",
         "Der Existentialismus ist ein Humanismus",
         "Sartre hielt nach dem Zweiten Weltkrieg einen Vortrag, in dem er die Idee ablehnte, dass die menschliche Natur das Schicksal vorherbestimmt. Er provozierte das Publikum: Sie sind das, was Sie tun, nicht das, was Sie planen. Der Saal war gespalten — aber jeder verliess ihn mit einer Frage.",
         "Nennen Sie etwas, das Sie schon immer tun wollten, aber aufschieben. Legen Sie ein genaues Datum fest, um zu beginnen — nicht wenn die Bedingungen perfekt sein werden."),
  "es": ("El hombre es todo lo que pudo haber sido y no llego a ser.",
         "El existencialismo es un humanismo",
         "Sartre dio una conferencia tras la Segunda Guerra Mundial en que rechazo la idea de que la naturaleza humana predetermina el destino. Provoco al publico: eres lo que haces, no lo que planeas. La sala estaba dividida, pero cada uno se fue con una pregunta.",
         "Nombra algo que siempre quisiste hacer pero pospones. Fija una fecha concreta para comenzar, no cuando las condiciones sean perfectas."),
  "pt": ("O homem e tudo o que poderia ter sido e nao se tornou.",
         "O existencialismo e um humanismo",
         "Sartre deu uma conferencia apos a Segunda Guerra Mundial em que rejeitou a ideia de que a natureza humana predetermina o destino. Provocou o publico: voce e o que faz, nao o que planeja. A sala estava dividida, mas cada um saiu com uma pergunta.",
         "Nomeie algo que sempre quis fazer mas adia. Defina uma data precisa para comecar, nao quando as condicoes forem perfeitas."),
},
"328": {
  "fr": ("Un esprit qui s'est elargi a une nouvelle idee ne reviendra jamais a sa taille originale.",
         "Autocrat of the Breakfast Table",
         "Holmes observa ses collegues avocats vieillir en accrochant aux memes arguments qu'ils avaient appris a 25 ans. Il nota que les plus brillants partageaient un trait : la curiosite perpetuelle, pas l'experience accumulee.",
         "Aujourd'hui, lisez sur un sujet que vous n'avez jamais etudie. Pas pour l'utiliser — juste pour etendre votre esprit."),
  "de": ("Ein Geist, der sich auf eine neue Idee ausgedehnt hat, wird nie zu seiner ursprunglichen Grosse zuruckkehren.",
         "The Autocrat of the Breakfast Table",
         "Holmes beobachtete, wie seine Anwaltskollegen alterten und an denselben Argumenten festhielten, die sie mit 25 Jahren gelernt hatten. Er stellte fest, dass die Brillantesten ein Merkmal teilten: ewige Neugier, nicht angesammelter Erfahrung.",
         "Lesen Sie heute uber ein Thema, das Sie noch nie studiert haben. Nicht um es zu nutzen — sondern um Ihren Geist zu erweitern."),
  "es": ("Una mente que se ha expandido a una nueva idea nunca volvera a su tamano original.",
         "El autocrata de la mesa del desayuno",
         "Holmes observo como sus colegas abogados envejecian aferrandose a los mismos argumentos que habian aprendido a los 25 anos. Noto que los mas brillantes compartian un rasgo: curiosidad perpetua, no experiencia acumulada.",
         "Hoy lee sobre un tema que nunca hayas estudiado. No para usarlo, sino para expandir tu mente."),
  "pt": ("Uma mente que se expandiu para uma nova ideia nunca voltara ao seu tamanho original.",
         "O autocrata da mesa do cafe da manha",
         "Holmes observou como seus colegas advogados envelheciam apegados aos mesmos argumentos que haviam aprendido aos 25 anos. Notou que os mais brilhantes compartilhavam uma caracteristica: curiosidade perpetua, nao experiencia acumulada.",
         "Hoje leia sobre um assunto que nunca estudou. Nao para usar, mas para expandir sua mente."),
},
"329": {
  "fr": ("Notre plus grande peur n'est pas d'etre inadequat. Notre plus grande peur est d'etre puissant au-dela de toute mesure.",
         "Un retour a l'amour",
         "Williamson ecrivit ce passage apres des annees d'observation : la plupart des gens sabotent leur propre succes, non par peur de l'echec, mais par peur de ce que leur plein potentiel exigerait d'eux. Briller est plus effrayant que se cacher.",
         "Pensez a un domaine ou vous vous contentez de moins que vous ne pourriez. Demandez-vous honnêtement : ai-je peur de ce que le plein succes exigerait de moi ?"),
  "de": ("Unsere grosste Angst ist nicht, unzulanglich zu sein. Unsere grosste Angst ist, uber alle Massen machtig zu sein.",
         "Ruckkehr zur Liebe",
         "Williamson schrieb diesen Abschnitt nach Jahren der Beobachtung: Die meisten Menschen sabotieren ihren eigenen Erfolg, nicht aus Angst vor dem Scheitern, sondern aus Angst davor, was ihr volles Potenzial von ihnen verlangen wurde. Zu leuchten ist angsteinflossender als sich zu verstecken.",
         "Denken Sie an einen Bereich, in dem Sie sich mit weniger zufrieden geben, als Sie konnten. Fragen Sie sich ehrlich: Habe ich Angst vor dem, was vollstandiger Erfolg von mir verlangen wurde?"),
  "es": ("Nuestro mayor miedo no es ser inadecuados. Nuestro mayor miedo es ser poderosos mas alla de toda medida.",
         "Volver al amor",
         "Williamson escribio este pasaje tras anos de observacion: la mayoria de las personas sabotean su propio exito, no por miedo al fracaso, sino por miedo a lo que su pleno potencial les exigiria. Brillar es mas aterrador que esconderse.",
         "Piensa en un area donde te conformas con menos de lo que podrias. Preguntate honestamente: tengo miedo de lo que el exito pleno me exigiria?"),
  "pt": ("Nosso maior medo nao e ser inadequado. Nosso maior medo e ser poderoso alem de toda medida.",
         "Um retorno ao amor",
         "Williamson escreveu este trecho apos anos de observacao: a maioria das pessoas sabota seu proprio sucesso, nao por medo do fracasso, mas por medo do que seu pleno potencial exigiria delas. Brilhar e mais assustador do que se esconder.",
         "Pense em uma area onde se contenta com menos do que poderia. Pergunte-se honestamente: tenho medo do que o sucesso pleno exigiria de mim?"),
},
"330": {
  "fr": ("Quand tu es fatigue — repose-toi, ne capitule pas.",
         "Les lecons de vie",
         "Bimbo, pasteur et auteur nigerien, ecrivit cette pensee apres avoir accompagne des centaines de personnes a travers des crises. Il observa que la capitulation n'arrive pas au moment de la defaite — elle arrive dans les instants d'epuisement qui la precedent.",
         "La prochaine fois que vous voudrez arreter quelque chose d'important, demandez-vous : est-ce que j'abandonne parce que c'est vraiment la bonne decision, ou parce que je suis simplement fatigue en ce moment ?"),
  "de": ("Wenn du mude bist — ruh dich aus, gib nicht auf.",
         "Lektionen des Lebens",
         "Bimbo, ein nigerianischer Pastor und Autor, schrieb diesen Gedanken, nachdem er Hunderte von Menschen durch Krisen begleitet hatte. Er beobachtete, dass das Aufgeben nicht im Moment der Niederlage geschieht — es geschieht in den Momenten der Erschopfung, die ihr vorausgehen.",
         "Wenn Sie das nachste Mal aufhoren wollen, etwas Wichtiges zu tun, fragen Sie sich: Gebe ich auf, weil es wirklich die richtige Entscheidung ist, oder weil ich gerade einfach mude bin?"),
  "es": ("Cuando estes cansado, descansa; no te rindas.",
         "Lecciones de vida",
         "Bimbo, pastor y autor nigeriano, escribio este pensamiento tras acompanar a cientos de personas a traves de crisis. Observo que la rendicion no llega en el momento de la derrota, sino en los instantes de agotamiento que la preceden.",
         "La proxima vez que quieras dejar algo importante, preguntate: me estoy rindiendo porque es realmente la decision correcta, o porque simplemente estoy cansado en este momento?"),
  "pt": ("Quando estiver cansado, descanse; nao desista.",
         "Licoes de vida",
         "Bimbo, pastor e autor nigeriano, escreveu este pensamento apos acompanhar centenas de pessoas em crises. Observou que a desistencia nao ocorre no momento da derrota, mas nos instantes de esgotamento que a precedem.",
         "Da proxima vez que quiser parar algo importante, pergunte-se: estou desistindo porque e realmente a decisao certa, ou porque simplesmente estou cansado agora?"),
},
"331": {
  "fr": ("La connaissance de soi est le debut de toute sagesse.",
         "Ethique a Nicomaque",
         "Aristote observa ses etudiants debattre de politique et de philosophie avec assurance. Mais quand il leur demanda de se decrire eux-memes honnêtement, ils hesiterent. Il nota que connaitre le monde exterieur sans se connaitre soi-meme est une forme d'ignorance.",
         "Ecrivez 5 de vos forces et 5 de vos faiblesses. Puis demandez a quelqu'un de proche de faire la meme liste sur vous. Comparez."),
  "de": ("Selbsterkenntnis ist der Beginn aller Weisheit.",
         "Nikomachische Ethik",
         "Aristoteles beobachtete seine Studenten, die selbstsicher uber Politik und Philosophie diskutierten. Als er sie aber bat, sich selbst ehrlich zu beschreiben, zogerten sie. Er stellte fest, dass das Kennen der Aussenwelt ohne Selbstkenntnis eine Form von Unwissenheit ist.",
         "Schreiben Sie 5 Ihrer Starken und 5 Ihrer Schwachen auf. Dann bitten Sie jemanden Nahes, dieselbe Liste uber Sie zu erstellen. Vergleichen Sie."),
  "es": ("El autoconocimiento es el comienzo de toda sabiduria.",
         "Etica a Nicomaco",
         "Aristoteles observo a sus estudiantes debatir con seguridad sobre politica y filosofia. Pero cuando les pidio que se describieran honestamente a si mismos, dudaron. Noto que conocer el mundo exterior sin conocerse a uno mismo es una forma de ignorancia.",
         "Escribe 5 de tus fortalezas y 5 de tus debilidades. Luego pide a alguien cercano que haga la misma lista sobre ti. Compara."),
  "pt": ("O autoconhecimento e o inicio de toda sabedoria.",
         "Etica a Nicomaco",
         "Aristoteles observou seus alunos debatendo com confianca sobre politica e filosofia. Mas quando lhes pediu que se descrevessem honestamente, hesitaram. Notou que conhecer o mundo exterior sem se conhecer e uma forma de ignorancia.",
         "Escreva 5 de seus pontos fortes e 5 de seus pontos fracos. Em seguida peca a alguem proximo que faca a mesma lista sobre voce. Compare."),
},
"332": {
  "fr": ("On ne peut pas changer le passe. Mais l'attitude envers le passe — c'est en ton pouvoir.",
         "Decider sa vie : vers un sens a l'existence",
         "Frankl survivit a Auschwitz. En sortant, il ne raconta pas une histoire de haine — il parla de comment il avait continue a choisir sa reponse interieures aux circonstances. Il nota que la derniere liberte humaine est de choisir son attitude dans n'importe quelle condition.",
         "Pensez a un evenement douloureux de votre passe que vous blâmez pour quelque chose dans votre vie actuelle. Demandez-vous : quelle attitude nouvelle pourrait m'aider a avancer ?"),
  "de": ("Die Vergangenheit kann man nicht andern. Aber die Einstellung zur Vergangenheit — das liegt in deiner Macht.",
         "...trotzdem Ja zum Leben sagen",
         "Frankl uberlebte Auschwitz. Als er herauskam, erzahlte er keine Geschichte des Hasses — er sprach davon, wie er weiterhin seine innere Reaktion auf die Umstande wahlte. Er stellte fest, dass die letzte menschliche Freiheit darin besteht, seine Einstellung unter allen Bedingungen zu wahlen.",
         "Denken Sie an ein schmerzhaftes Ereignis aus Ihrer Vergangenheit, dem Sie etwas in Ihrem heutigen Leben zuschreiben. Fragen Sie sich: Welche neue Einstellung konnte mir helfen, voranzukommen?"),
  "es": ("No se puede cambiar el pasado. Pero la actitud hacia el pasado esta en tu poder.",
         "El hombre en busca de sentido",
         "Frankl sobrevivio a Auschwitz. Al salir, no conto una historia de odio, sino de como seguia eligiendo su respuesta interior a las circunstancias. Anoto que la ultima libertad humana es elegir la propia actitud en cualquier condicion.",
         "Piensa en un evento doloroso de tu pasado al que culpas de algo en tu vida actual. Preguntate: que nueva actitud podria ayudarme a avanzar?"),
  "pt": ("Nao se pode mudar o passado. Mas a atitude em relacao ao passado esta em seu poder.",
         "Em busca de sentido",
         "Frankl sobreviveu a Auschwitz. Ao sair, nao contou uma historia de odio, mas de como continuava escolhendo sua resposta interior as circunstancias. Anotou que a ultima liberdade humana e escolher sua atitude em qualquer condicao.",
         "Pense em um evento doloroso de seu passado que culpa por algo em sua vida atual. Pergunte-se: que nova atitude poderia me ajudar a avancar?"),
},
"333": {
  "fr": ("Nous ne pouvons pas controler le vent, mais nous pouvons diriger les voiles.",
         "Entretiens, Livre IV",
         "Epictete, ancien esclave devenu philosophe, fut interroge sur comment il restait serein malgre les humiliations qu'il avait subies. Il repondit : les humiliations etaient reelles — mais ma reaction a toujours ete mienne. Personne n'a jamais pu me prendre cela.",
         "Identifiez aujourd'hui une chose que vous ne pouvez pas controler et qui vous preoccupe. Puis identifiez une action concrete que vous pouvez prendre dans cette situation."),
  "de": ("Wir konnen den Wind nicht kontrollieren, aber wir konnen die Segel steuern.",
         "Gesprache, Buch IV",
         "Epiktet, ein ehemaliger Sklave und Philosoph, wurde gefragt, wie er trotz erlittener Demutigung gelassen blieb. Er antwortete: Die Demutigung war real — aber meine Reaktion war immer meine. Niemand hat mir das je nehmen konnen.",
         "Identifizieren Sie heute etwas, das Sie nicht kontrollieren konnen und das Sie beschaftigt. Dann identifizieren Sie eine konkrete Handlung, die Sie in dieser Situation vornehmen konnen."),
  "es": ("No podemos controlar el viento, pero podemos dirigir las velas.",
         "Discursos, Libro IV",
         "Epicteto, ex esclavo convertido en filosofo, fue interrogado sobre como permanecia sereno a pesar de las humillaciones sufridas. Respondio: las humillaciones eran reales, pero mi reaccion siempre fue mia. Nadie jamas pudo quitarme eso.",
         "Identifica hoy algo que no puedes controlar y que te preocupa. Luego identifica una accion concreta que puedas tomar en esa situacion."),
  "pt": ("Nao podemos controlar o vento, mas podemos dirigir as velas.",
         "Conversacoes, Livro IV",
         "Epicteto, ex-escravo tornado filosofo, foi questionado sobre como permanecia sereno apesar das humilhacoes sofridas. Respondeu: as humilhacoes eram reais, mas minha reacao sempre foi minha. Ninguem jamais pude me tirar isso.",
         "Identifique hoje algo que nao pode controlar e que te preocupa. Em seguida identifique uma acao concreta que pode tomar nessa situacao."),
},
"334": {
  "fr": ("Tout probleme que tu peux resoudre avec de l'argent n'est pas vraiment un probleme.",
         "Decoded",
         "Jay-Z raconte dans ses interviews avoir cru longtemps que les problemes d'argent etaient le summum de la souffrance. Quand il devint riche, il decouvrit une couche plus profonde : les problemes relationnels, de sens, d'identite. L'argent avait resolu une couche — mais en avait revele d'autres.",
         "Faites la liste de vos plus grandes inquietudes actuelles. Lesquelles pourraient etre resolues par plus d'argent ? Lesquelles ne le seraient pas ?"),
  "de": ("Jedes Problem, das du mit Geld kaufen kannst, ist kein richtiges Problem.",
         "Decoded",
         "Jay-Z erzahlt in seinen Interviews, dass er lange glaubte, Geldprobleme seien der Gipfel des Leidens. Als er reich wurde, entdeckte er eine tiefere Schicht: Beziehungsprobleme, Sinnprobleme, Identitätsprobleme. Geld hatte eine Schicht geloest — aber andere enthullt.",
         "Listen Sie Ihre grossten aktuellen Sorgen auf. Welche konnten durch mehr Geld geloest werden? Welche nicht?"),
  "es": ("Todo problema que puedes resolver con dinero no es realmente un problema.",
         "Decoded",
         "Jay-Z cuenta en sus entrevistas haber creido durante mucho tiempo que los problemas de dinero eran lo maximo del sufrimiento. Cuando se volvio rico, descubrio una capa mas profunda: problemas relacionales, de sentido, de identidad. El dinero habia resuelto una capa, pero habia revelado otras.",
         "Haz una lista de tus mayores preocupaciones actuales. Cuales podrian resolverse con mas dinero? Cuales no?"),
  "pt": ("Todo problema que voce pode resolver com dinheiro nao e realmente um problema.",
         "Decoded",
         "Jay-Z conta em suas entrevistas ter acreditado por muito tempo que problemas de dinheiro eram o auge do sofrimento. Quando ficou rico, descobriu uma camada mais profunda: problemas relacionais, de sentido, de identidade. O dinheiro havia resolvido uma camada, mas revelou outras.",
         "Faca uma lista de suas maiores preocupacoes atuais. Quais poderiam ser resolvidas com mais dinheiro? Quais nao?"),
},
"335": {
  "fr": ("La patience n'est pas la capacite d'attendre — c'est la capacite de garder une bonne attitude en attendant.",
         "Gerer vos emotions",
         "Meyer travailla avec une femme qui disait avoir de la patience, mais se plaignait constamment. Meyer distingua deux types d'attente : passive et active. L'attente passive engendre la frustration ; l'attente active est choisie et productive.",
         "La prochaine fois que vous devez attendre quelque chose, fixez-vous une micro-tache ou un apprentissage pendant ce temps. Transformez l'attente en investissement."),
  "de": ("Geduld ist nicht die Fahigkeit zu warten — es ist die Fahigkeit, in der Wartezeit eine gute Einstellung zu behalten.",
         "Verwalten Sie Ihre Emotionen",
         "Meyer arbeitete mit einer Frau, die sagte, sie habe Geduld, aber standig klagte. Meyer unterschied zwei Arten des Wartens: passiv und aktiv. Passives Warten erzeugt Frustration; aktives Warten ist gewahlt und produktiv.",
         "Wenn Sie das nachste Mal auf etwas warten mussen, setzen Sie sich eine Mikroaufgabe oder ein Lernziel fur diese Zeit. Verwandeln Sie das Warten in eine Investition."),
  "es": ("La paciencia no es la capacidad de esperar, sino la de mantener una buena actitud mientras se espera.",
         "Gestiona tus emociones",
         "Meyer trabajo con una mujer que decia tener paciencia pero se quejaba constantemente. Meyer distinguio dos tipos de espera: pasiva y activa. La espera pasiva genera frustracion; la espera activa es elegida y productiva.",
         "La proxima vez que tengas que esperar algo, ponerte una microtarea o un aprendizaje durante ese tiempo. Transforma la espera en inversion."),
  "pt": ("A paciencia nao e a capacidade de esperar, mas a de manter uma boa atitude enquanto espera.",
         "Gerencie suas emocoes",
         "Meyer trabalhou com uma mulher que dizia ter paciencia mas reclamava constantemente. Meyer distinguiu dois tipos de espera: passiva e ativa. A espera passiva gera frustracao; a espera ativa e escolhida e produtiva.",
         "Da proxima vez que tiver de esperar algo, defina uma microtarefa ou aprendizado durante esse tempo. Transforme a espera em investimento."),
},
"336": {
  "fr": ("Votre cerveau n'est pas programme pour le bonheur — il est programme pour la survie.",
         "Le cerveau qui guérit",
         "Hanson decrivit comment le cerveau humain a un 'biais de negativite' evolutif : les mauvaises experiences s'impriment plus profondement que les bonnes. Il proposa une pratique : savourer consciemment les bons moments 15-20 secondes pour les 'installer' en memoire a long terme.",
         "Aujourd'hui, quand quelque chose de bien se passe, arretez-vous 20 secondes et savourez consciemment ce moment. Repetez trois fois."),
  "de": ("Ihr Gehirn ist nicht auf Gluck programmiert — es ist auf Uberleben programmiert.",
         "Das Gehirn, das heilt",
         "Hanson beschrieb, wie das menschliche Gehirn einen evolutionaren 'Negativitatsbias' hat: Schlechte Erfahrungen prragen sich tiefer ein als gute. Er schlug eine Praxis vor: Gute Momente bewusst 15-20 Sekunden geniessen, um sie im Langzeitgedachtnis zu 'installieren'.",
         "Wenn heute etwas Gutes passiert, halten Sie 20 Sekunden inne und geniessen Sie den Moment bewusst. Wiederholen Sie dreimal."),
  "es": ("Tu cerebro no esta programado para la felicidad, esta programado para la supervivencia.",
         "El cerebro que sana",
         "Hanson describio como el cerebro humano tiene un 'sesgo de negatividad' evolutivo: las malas experiencias se graban mas profundamente que las buenas. Propuso una practica: saborear conscientemente los buenos momentos durante 15-20 segundos para 'instalarlos' en la memoria a largo plazo.",
         "Hoy, cuando algo bueno suceda, detente 20 segundos y saborea conscientemente ese momento. Repite tres veces."),
  "pt": ("Seu cerebro nao esta programado para a felicidade, esta programado para a sobrevivencia.",
         "O cerebro que cura",
         "Hanson descreveu como o cerebro humano tem um 'vies de negatividade' evolutivo: as mas experiencias se gravam mais profundamente do que as boas. Propos uma pratica: saborear conscientemente os bons momentos por 15-20 segundos para 'instala-los' na memoria de longo prazo.",
         "Hoje, quando algo bom acontecer, pare 20 segundos e saboreie conscientemente esse momento. Repita tres vezes."),
},
"337": {
  "fr": ("Le moyen le plus rapide de se sentir heureux est d'exprimer de la gratitude a quelqu'un qu'on a neglige de remercier.",
         "La force de l'optimisme",
         "Seligman conduisit une experience ou des participants devaient ecrire une lettre de gratitude et la lire en personne a quelqu'un qu'ils n'avaient jamais remercié. Les resultats montrèrent une augmentation de bonheur plus forte que n'importe quelle autre intervention testee.",
         "Pensez a quelqu'un qui a eu un impact positif sur vous et que vous n'avez jamais remercié proprement. Ecrivez-lui un message aujourd'hui — meme court."),
  "de": ("Der schnellste Weg zum Gluck ist, jemandem Dankbarkeit auszudrucken, den man vergessen hat zu danken.",
         "Flourish: Wie Menschen aufbluhen",
         "Seligman fuhrte ein Experiment durch, bei dem die Teilnehmer einen Dankbarkeitsbrief schreiben und ihn einer Person personlich vorlesen sollten, der sie nie gedankt hatten. Die Ergebnisse zeigten einen starkeren Anstieg des Glucks als jede andere getestete Intervention.",
         "Denken Sie an jemanden, der einen positiven Einfluss auf Sie hatte und dem Sie nie richtig gedankt haben. Schreiben Sie ihm heute eine Nachricht — auch wenn sie kurz ist."),
  "es": ("El camino mas rapido hacia la felicidad es expresar gratitud a alguien a quien olvidaste agradecer.",
         "La fuerza del optimismo",
         "Seligman realizo un experimento en el que los participantes debian escribir una carta de gratitud y leerla en persona a alguien a quien nunca habian dado las gracias. Los resultados mostraron un aumento de felicidad mayor que cualquier otra intervencion probada.",
         "Piensa en alguien que tuvo un impacto positivo en ti y a quien nunca agradeciste correctamente. Escribele un mensaje hoy, aunque sea breve."),
  "pt": ("O caminho mais rapido para a felicidade e expressar gratidao a alguem que esqueceu de agradecer.",
         "Florescer: como as pessoas prosperam",
         "Seligman conduziu um experimento em que participantes deviam escrever uma carta de gratidao e le-la pessoalmente para alguem a quem nunca tinham agradecido. Os resultados mostraram um aumento de felicidade maior do que qualquer outra intervencao testada.",
         "Pense em alguem que teve um impacto positivo em voce e a quem nunca agradeceu adequadamente. Escreva-lhe uma mensagem hoje, mesmo que curta."),
},
"338": {
  "fr": ("Les gens font rarement quelque chose de mal en pensant que c'est mauvais.",
         "Fondements de la pensee sociale",
         "Bandura etudia des soldats qui avaient commis des atrocites pendant la guerre. Presque aucun n'avait pense agir de facon malveillante — chacun avait un cadre moral qui justifiait ses actions. Cette decouverte transforma la psychologie morale.",
         "Pensez a une action passee que vous regrettez. Quelle histoire vous etes-vous raconte a ce moment-la pour la justifier ? Que pensez-vous de cette histoire maintenant ?"),
  "de": ("Menschen tun selten etwas Schlechtes in dem Glauben, dass es schlecht ist.",
         "Grundlagen des sozialen Denkens",
         "Bandura untersuchte Soldaten, die wahrend des Krieges Grausamkeiten begangen hatten. Fast keiner von ihnen dachte, er handle bosartig — jeder hatte einen moralischen Rahmen, der seine Handlungen rechtfertigte. Diese Entdeckung veranderte die Moralpsychologie.",
         "Denken Sie an eine vergangene Handlung, die Sie bereuen. Welche Geschichte haben Sie sich in diesem Moment erzahlt, um sie zu rechtfertigen? Was denken Sie jetzt uber diese Geschichte?"),
  "es": ("Las personas raramente hacen algo malo pensando que es malo.",
         "Fundamentos del pensamiento social",
         "Bandura estudio a soldados que habian cometido atrocidades durante la guerra. Casi ninguno penso que actuaba de manera maliciosa: cada uno tenia un marco moral que justificaba sus acciones. Este descubrimiento transformo la psicologia moral.",
         "Piensa en una accion pasada que lamentes. Que historia te contaste en ese momento para justificarla? Que piensas de esa historia ahora?"),
  "pt": ("As pessoas raramente fazem algo ruim pensando que e ruim.",
         "Fundamentos do pensamento social",
         "Bandura estudou soldados que haviam cometido atrocidades durante a guerra. Quase nenhum pensou estar agindo de forma maliciosa: cada um tinha um quadro moral que justificava suas acoes. Essa descoberta transformou a psicologia moral.",
         "Pense em uma acao passada que se arrepende. Que historia se contou naquele momento para justifica-la? O que pensa dessa historia agora?"),
},
"339": {
  "fr": ("Nous jugeons les autres par leurs actes, nous-memes par nos intentions.",
         "Les 7 habitudes des gens tres efficaces",
         "Covey observa des conflits organisationnels ou chaque cote se plaignait de l'injustice de l'autre. En demandant a chaque partie de decrire ses propres motivations et les motivations de l'autre, il decouvrit un biais universel : nous nous voyons sous le meilleur jour.",
         "Pensez a quelqu'un dont vous critiquez le comportement. Essayez d'imaginer honnêtement l'intention positive qu'il pourrait avoir derriere cet acte."),
  "de": ("Wir urteilen uber andere nach ihren Taten, uber uns selbst nach unseren Absichten.",
         "Die 7 Wege zur Effektivitat",
         "Covey beobachtete organisatorische Konflikte, bei denen jede Seite die Ungerechtigkeit der anderen beklagte. Als er jede Partei bat, ihre eigenen Motivationen und die Motivationen der anderen zu beschreiben, entdeckte er einen universellen Bias: Wir sehen uns selbst im besten Licht.",
         "Denken Sie an jemanden, dessen Verhalten Sie kritisieren. Versuchen Sie ehrlich, die positive Absicht vorzustellen, die hinter dieser Handlung stecken konnte."),
  "es": ("Juzgamos a los demas por sus actos; a nosotros mismos, por nuestras intenciones.",
         "Los 7 habitos de la gente altamente efectiva",
         "Covey observo conflictos organizacionales donde cada parte se quejaba de la injusticia de la otra. Al pedir a cada parte que describiera sus propias motivaciones y las del otro, descubrio un sesgo universal: nos vemos a nosotros mismos con la mejor luz.",
         "Piensa en alguien cuyo comportamiento criticas. Intenta imaginar honestamente la intencion positiva que podria tener detras de ese acto."),
  "pt": ("Julgamos os outros por seus atos; a nos mesmos, por nossas intencoes.",
         "Os 7 habitos das pessoas altamente eficazes",
         "Covey observou conflitos organizacionais onde cada lado reclamava da injustica do outro. Ao pedir a cada parte que descrevesse suas proprias motivacoes e as do outro, descobriu um vies universal: nos nos vemos sob a melhor luz.",
         "Pense em alguem cujo comportamento critica. Tente imaginar honestamente a intencao positiva que poderia ter por tras desse ato."),
},
"340": {
  "fr": ("L'amour de soi est la reputation que vous construisez pour vous-meme.",
         "Le pilier de l'estime de soi",
         "Branden travailla avec des centaines de cadres superieurs qui avaient reussi exterieurement mais se sentaient vides. Il decouvrit que l'estime de soi ne vient pas des realisations — elle vient de la coherence entre les valeurs declarees et les actions reelles.",
         "Identifiez une valeur que vous affirmez avoir. Evaluez sur 10 combien vos actions de la semaine derniere reflétaient cette valeur. Si le score est bas, choisissez un changement concret."),
  "de": ("Selbstwertgefuhl ist der Ruf, den Sie fur sich selbst aufbauen.",
         "Die Saule des Selbstwertgefuhls",
         "Branden arbeitete mit Hunderten von leitenden Angestellten, die ausserstlich erfolgreich waren, sich aber leer fuhlten. Er entdeckte, dass Selbstwertgefuhl nicht aus Leistungen kommt — es kommt aus der Kohärenz zwischen proklamierten Werten und tatsachlichen Handlungen.",
         "Identifizieren Sie einen Wert, von dem Sie behaupten, ihn zu haben. Bewerten Sie auf einer Skala von 1-10, wie sehr Ihre Handlungen der letzten Woche diesen Wert widerspiegelten. Bei niedrigem Score wahlen Sie eine konkrete Änderung."),
  "es": ("La autoestima es la reputacion que construyes para ti mismo.",
         "El pilar de la autoestima",
         "Branden trabajo con cientos de altos directivos que habian tenido exito externo pero se sentian vacios. Descubrio que la autoestima no viene de los logros, sino de la coherencia entre los valores declarados y las acciones reales.",
         "Identifica un valor que afirmas tener. Evalua del 1 al 10 cuanto reflejaron tus acciones de la semana pasada ese valor. Si la puntuacion es baja, elige un cambio concreto."),
  "pt": ("A autoestima e a reputacao que voce constroi para si mesmo.",
         "O pilar da autoestima",
         "Branden trabalhou com centenas de executivos seniors que tinham sucesso externo mas se sentiam vazios. Descobriu que a autoestima nao vem das realizacoes, mas da coerencia entre os valores declarados e as acoes reais.",
         "Identifique um valor que afirma ter. Avalie de 1 a 10 o quanto suas acoes da semana passada refletiram esse valor. Se a pontuacao for baixa, escolha uma mudanca concreta."),
},
"341": {
  "fr": ("L'homme est la mesure de toutes choses — mais seulement quand il se connait.",
         "Fragments",
         "Protagoras debattait avec des philosophes qui affirmaient que la verite etait absolue et universelle. Il leur demandait : et si deux hommes sages arrivent a des conclusions opposees ? La verite n'est-elle pas relative a celui qui la percoit ?",
         "Choisissez une conviction forte que vous avez. Essayez serieusement de vous mettre a la place de quelqu'un qui pense le contraire. Que comprenez-vous depuis cette perspective ?"),
  "de": ("Der Mensch ist das Mass aller Dinge — aber nur, wenn er sich selbst kennt.",
         "Fragmente",
         "Protagoras debattierte mit Philosophen, die behaupteten, die Wahrheit sei absolut und universell. Er fragte sie: Was ist, wenn zwei weise Manner zu entgegengesetzten Schlussfolgerungen kommen? Ist die Wahrheit nicht relativ zu demjenigen, der sie wahrnimmt?",
         "Wahlen Sie eine starke Uberzeugung, die Sie haben. Versuchen Sie ernsthaft, sich in die Lage von jemandem zu versetzen, der das Gegenteil denkt. Was verstehen Sie aus dieser Perspektive?"),
  "es": ("El hombre es la medida de todas las cosas, pero solo cuando se conoce a si mismo.",
         "Fragmentos",
         "Protagoras debatia con filosofos que afirmaban que la verdad era absoluta y universal. Les preguntaba: y si dos sabios llegan a conclusiones opuestas? No es la verdad relativa a quien la percibe?",
         "Elige una conviction fuerte que tengas. Intenta seriamente ponerte en el lugar de alguien que piensa lo contrario. Que comprendes desde esa perspectiva?"),
  "pt": ("O homem e a medida de todas as coisas, mas apenas quando se conhece.",
         "Fragmentos",
         "Protagoras debatia com filosofos que afirmavam que a verdade era absoluta e universal. Perguntava-lhes: e se dois sabios chegam a conclusoes opostas? A verdade nao e relativa a quem a percebe?",
         "Escolha uma conviccao forte que tem. Tente seriamente se colocar no lugar de alguem que pensa o contrario. O que compreende dessa perspectiva?"),
},
"342": {
  "fr": ("Le subconscient dit toujours oui.",
         "La puissance de votre subconscient",
         "Murphy travailla avec des patients qui essayaient de changer des comportements par la volonte seule — et echouaient. Il decouvrit que le subconscient ne distingue pas le reel de l'imagine. En changeant les images mentales repetees, les comportements changeaient sans effort conscient.",
         "Ce soir avant de dormir, imaginez-vous accomplissant quelque chose que vous voulez — avec des details sensoriels. Repetez pendant 7 jours et observez ce qui change."),
  "de": ("Das Unterbewusstsein sagt immer ja.",
         "Die Macht Ihres Unterbewusstseins",
         "Murphy arbeitete mit Patienten, die versuchten, Verhaltensweisen allein durch Willenskraft zu andern — und scheiterten. Er entdeckte, dass das Unterbewusstsein nicht zwischen Real und Imaginar unterscheidet. Durch die Änderung der wiederholten mentalen Bilder anderten sich die Verhaltensweisen ohne bewusste Anstrengung.",
         "Stellen Sie sich heute Abend vor dem Einschlafen vor, wie Sie etwas erreichen, das Sie wollen — mit sinnlichen Details. Wiederholen Sie 7 Tage lang und beobachten Sie, was sich andert."),
  "es": ("El subconsciente siempre dice si.",
         "El poder de tu mente subconsciente",
         "Murphy trabajo con pacientes que intentaban cambiar comportamientos solo con fuerza de voluntad, y fallaban. Descubrio que el subconsciente no distingue lo real de lo imaginado. Al cambiar las imagenes mentales repetidas, los comportamientos cambiaban sin esfuerzo consciente.",
         "Esta noche, antes de dormir, imaginate logrando algo que deseas, con detalles sensoriales. Repite durante 7 dias y observa que cambia."),
  "pt": ("O subconsciente sempre diz sim.",
         "O poder do seu subconsciente",
         "Murphy trabalhou com pacientes que tentavam mudar comportamentos apenas com forca de vontade e falhavam. Descobriu que o subconsciente nao distingue o real do imaginado. Ao mudar as imagens mentais repetidas, os comportamentos mudavam sem esforco consciente.",
         "Esta noite, antes de dormir, imagine-se realizando algo que deseja, com detalhes sensoriais. Repita por 7 dias e observe o que muda."),
},
"343": {
  "fr": ("Il n'y a rien de bon ou de mauvais — c'est seulement notre pensee qui le fait.",
         "Hamlet, Acte II",
         "Hamlet, en attente de vengeance, observe deux acteurs pleurer de vrais larmes pour un personnage fictif. Il se demande : si la douleur imaginee peut etre reelle, qu'est-ce que cela dit de la douleur basee sur notre interpretation des evenements ?",
         "Pensez a quelque chose que vous percevez comme 'mauvais' dans votre vie. Demandez-vous : dans quel sens cette situation pourrait-elle etre neutre ou meme positive ?"),
  "de": ("Es gibt nichts Gutes oder Schlechtes — nur unser Denken macht es dazu.",
         "Hamlet, Akt II",
         "Hamlet, in Erwartung der Rache, beobachtet zwei Schauspieler, die echte Tranen fur eine fiktive Figur weinen. Er fragt sich: Wenn imaginarer Schmerz real sein kann, was sagt das uber den Schmerz, der auf unserer Interpretation von Ereignissen basiert?",
         "Denken Sie an etwas, das Sie in Ihrem Leben als 'schlecht' wahrnehmen. Fragen Sie sich: Inwiefern konnte diese Situation neutral oder sogar positiv sein?"),
  "es": ("No hay nada bueno ni malo: solo nuestro pensamiento lo hace asi.",
         "Hamlet, Acto II",
         "Hamlet, esperando la venganza, observa a dos actores llorar lagrimas reales por un personaje ficticio. Se pregunta: si el dolor imaginado puede ser real, que dice eso del dolor basado en nuestra interpretacion de los eventos?",
         "Piensa en algo que percibes como 'malo' en tu vida. Preguntate: en que sentido podria ser neutral o incluso positivo?"),
  "pt": ("Nao ha nada bom ou ruim: e apenas nosso pensamento que o torna assim.",
         "Hamlet, Ato II",
         "Hamlet, esperando a vinganca, observa dois atores chorando lagrimas reais por um personagem ficticio. Pergunta-se: se a dor imaginada pode ser real, o que isso diz sobre a dor baseada em nossa interpretacao dos eventos?",
         "Pense em algo que percebe como 'ruim' em sua vida. Pergunte-se: em que sentido essa situacao poderia ser neutra ou ate positiva?"),
},
"344": {
  "fr": ("Nous ne construisons pas des murs pour tenir les gens dehors — nous les construisons pour voir qui se soucie assez de les franchir.",
         "Le Petit Prince",
         "Saint-Exupery observa des gens solitaires qui se plaignaient d'isolement mais repoussaient toute tentative de connexion. Il nota dans ses carnets : les murs qu'on construit pour se proteger peuvent devenir les barreaux de notre propre prison.",
         "Pensez a un mur emotionnel que vous avez construit. Demandez-vous : est-ce qu'il me protege vraiment, ou m'empeche-t-il de recevoir ce que je veux ?"),
  "de": ("Wir errichten keine Mauern, um die Menschen draussen zu halten — wir errichten sie, um zu sehen, wer sich genueg kummert, um sie zu uberwinden.",
         "Der kleine Prinz",
         "Saint-Exupery beobachtete einsame Menschen, die sich uber Isolation beklagten, aber jeden Verbindungsversuch zuruckwiesen. Er notierte in seinen Notizbuchern: Die Mauern, die wir zum Schutz bauen, konnen zu den Gitterstaben unseres eigenen Gefangnisses werden.",
         "Denken Sie an eine emotionale Mauer, die Sie errichtet haben. Fragen Sie sich: Schutzt sie mich wirklich, oder hindert sie mich daran, das zu empfangen, was ich will?"),
  "es": ("No construimos muros para mantener a la gente fuera: los construimos para ver quien se preocupa lo suficiente como para cruzarlos.",
         "El Principito",
         "Saint-Exupery observo a personas solitarias que se quejaban del aislamiento pero rechazaban todo intento de conexion. Anoto en sus cuadernos: los muros que construimos para protegernos pueden convertirse en los barrotes de nuestra propia prision.",
         "Piensa en un muro emocional que hayas construido. Preguntate: me protege realmente, o me impide recibir lo que quiero?"),
  "pt": ("Nao construimos muros para manter as pessoas de fora: os construimos para ver quem se importa o suficiente para cruzа-los.",
         "O Pequeno Principe",
         "Saint-Exupery observou pessoas solitarias que reclamavam do isolamento mas rejeitavam toda tentativa de conexao. Anotou em seus cadernos: os muros que construimos para nos proteger podem se tornar as grades de nossa propria prisao.",
         "Pense em um muro emocional que construiu. Pergunte-se: ele realmente me protege, ou me impede de receber o que quero?"),
},
"345": {
  "fr": ("Une generation d'enfants qu'on n'a pas appris a supporter l'inconfort est une generation qui souffre davantage.",
         "The Coddling of the American Mind",
         "Haidt etudia des donnees sur la sante mentale des etudiants americains entre 2012 et 2018. Il decouvrit que les niveaux d'anxiete et de depression avaient augmente dramatiquement precisement dans la generation protegee de toute friction. La conclusion : le confort excessif fragilise.",
         "Cette semaine, choisissez intentionnellement une chose inconfortable que vous evitez. Faites-la. Observez ce qui se passe reellement versus ce que vous aviez imagine."),
  "de": ("Eine Generation von Kindern, die man nicht beigebracht hat, Unbehagen zu ertragen, ist eine Generation, die mehr leidet.",
         "The Coddling of the American Mind",
         "Haidt untersuchte Daten zur psychischen Gesundheit amerikanischer Studenten zwischen 2012 und 2018. Er entdeckte, dass die Angst- und Depressionsniveaus in der Generation, die vor jeder Reibung geschutzt wurde, dramatisch gestiegen waren. Das Fazit: Ubermassiger Komfort schwacht.",
         "Wahlen Sie diese Woche absichtlich etwas Unbequemes, das Sie vermeiden. Tun Sie es. Beobachten Sie, was wirklich passiert, im Vergleich zu dem, was Sie sich vorgestellt haben."),
  "es": ("Una generacion de ninos a los que no se les ensenо a soportar la incomodidad es una generacion que sufre mas.",
         "La transformacion de la mente americana",
         "Haidt estudio datos sobre la salud mental de estudiantes universitarios estadounidenses entre 2012 y 2018. Descubrio que los niveles de ansiedad y depresion habian aumentado dramaticamente en la generacion protegida de toda friccion. La conclusion: el confort excesivo debilita.",
         "Esta semana, elige intencionalmente algo incomodo que evitas. Hazlo. Observa lo que realmente sucede frente a lo que imaginabas."),
  "pt": ("Uma geracao de criancas a quem nao se ensinou a suportar o desconforto e uma geracao que sofre mais.",
         "A transformacao da mente americana",
         "Haidt estudou dados sobre a saude mental de estudantes universitarios americanos entre 2012 e 2018. Descobriu que os niveis de ansiedade e depressao haviam aumentado dramaticamente na geracao protegida de toda friccao. A conclusao: o conforto excessivo enfraquece.",
         "Esta semana, escolha intencionalmente algo desconfortavel que evita. Faca isso. Observe o que realmente acontece versus o que imaginou."),
},
"346": {
  "fr": ("Ce ne sont pas vos realisations qui vous definissent. C'est la facon dont vous relevez d'un echec.",
         "Les seconds montagnes",
         "Brooks interviewe des personnes qui avaient tout reussi selon les criteres sociaux et se sentaient neanmoins vides. Il nota que ceux qui avaient traverse un echec ou une perte significatifs et s'etaient releves avaient une profondeur que les autres n'avaient pas.",
         "Pensez a votre plus grand echec. Qu'avez-vous appris que vous n'auriez jamais appris autrement ? Comment cet echec vous a-t-il forme ?"),
  "de": ("Nicht Ihre Leistungen definieren Sie. Es ist die Art, wie Sie sich von einem Scheitern erholen.",
         "Die zweiten Berge",
         "Brooks interviewte Menschen, die nach sozialen Massstaben alles erreicht hatten und sich dennoch leer fuhlten. Er stellte fest, dass diejenigen, die ein bedeutendes Scheitern oder einen Verlust erlebt und sich erholt hatten, eine Tiefe hatten, die andere nicht hatten.",
         "Denken Sie an Ihr grosstes Scheitern. Was haben Sie gelernt, das Sie auf keine andere Weise hatten lernen konnen? Wie hat dieses Scheitern Sie geformt?"),
  "es": ("No son tus logros los que te definen. Es la forma en que te recuperas de un fracaso.",
         "Las segundas montanas",
         "Brooks entrevisto a personas que habian logrado todo segun los criterios sociales y se sentian vacias. Noto que quienes habian atravesado un fracaso o una perdida significativa y se habian recuperado tenian una profundidad que los demas no tenian.",
         "Piensa en tu mayor fracaso. Que aprendiste que no habrias aprendido de ninguna otra manera? Como te formo ese fracaso?"),
  "pt": ("Nao sao suas realizacoes que te definem. E a forma como voce se recupera de um fracasso.",
         "As segundas montanhas",
         "Brooks entrevistou pessoas que tinham alcancado tudo pelos criterios sociais e se sentiam vazias. Notou que aquelas que haviam passado por um fracasso ou perda significativa e se recuperado tinham uma profundidade que as outras nao tinham.",
         "Pense em seu maior fracasso. O que aprendeu que nao teria aprendido de outra forma? Como esse fracasso te formou?"),
},
"347": {
  "fr": ("La meilleure facon d'aider les autres, c'est d'abord de s'aider soi-meme.",
         "Motivation et personnalite",
         "Maslow remarqua que ses patients les plus effaces — ceux qui se sacrifiaient constamment — etaient souvent aussi les plus amers et epuises. Les personnes qui prenaient soin d'elles-memes avaient plus a donner, pas moins.",
         "Identifiez une chose que vous faites pour les autres alors que vous en avez besoin pour vous-meme. Faites-la pour vous cette semaine."),
  "de": ("Der beste Weg, anderen zu helfen, besteht darin, sich zuerst selbst zu helfen.",
         "Motivation und Personlichkeit",
         "Maslow bemerkte, dass seine selbstlosesten Patienten — diejenigen, die sich standig opferten — oft auch die verbittersten und erschopftesten waren. Menschen, die sich um sich selbst kummerten, hatten mehr zu geben, nicht weniger.",
         "Identifizieren Sie etwas, das Sie fur andere tun, wahrend Sie es fur sich selbst brauchen. Tun Sie es diese Woche fur sich."),
  "es": ("La mejor manera de ayudar a los demas es ayudarse primero a uno mismo.",
         "Motivacion y personalidad",
         "Maslow noto que sus pacientes mas abnegados, los que se sacrificaban constantemente, eran a menudo tambien los mas amargados y agotados. Las personas que se cuidaban a si mismas tenian mas que dar, no menos.",
         "Identifica algo que haces por los demas mientras tu mismo lo necesitas. Hazlo por ti esta semana."),
  "pt": ("A melhor forma de ajudar os outros e ajudar-se primeiro a si mesmo.",
         "Motivacao e personalidade",
         "Maslow notou que seus pacientes mais abnegados, os que se sacrificavam constantemente, eram frequentemente tambem os mais amargurados e esgotados. As pessoas que cuidavam de si mesmas tinham mais a dar, nao menos.",
         "Identifique algo que faz pelos outros enquanto voce mesmo precisa. Faca isso por voce esta semana."),
},
"348": {
  "fr": ("L'acceptation n'est pas une defaite. C'est une carte precise de la realite.",
         "La guerison radicale",
         "Brach travaillait avec un homme qui refusait d'accepter le diagnostic de cancer de sa femme. Il passait ses energies a chercher des alternatives, a nier. Quand il accepta finalement la realite, quelque chose de surprenant se produisit : il devint presents et sa femme sentit qu'il etait enfin la.",
         "Pensez a quelque chose dans votre vie que vous resistez encore a accepter. Dites-le a voix haute : 'C'est ainsi maintenant.' Remarquez si quelque chose se libère."),
  "de": ("Akzeptanz ist keine Niederlage. Es ist eine genaue Karte der Realitat.",
         "Radikale Akzeptanz",
         "Brach arbeitete mit einem Mann, der die Krebsdiagnose seiner Frau nicht akzeptieren wollte. Er verschwendete seine Energie damit, Alternativen zu suchen und zu leugnen. Als er die Realitat schliesslich akzeptierte, geschah etwas Uberraschades: Er wurde prasenter, und seine Frau spürte, dass er endlich da war.",
         "Denken Sie an etwas in Ihrem Leben, dem Sie sich noch widersetzen zu akzeptieren. Sagen Sie es laut: 'Es ist jetzt so.' Bemerken Sie, ob etwas freigesetzt wird."),
  "es": ("La aceptacion no es una derrota. Es un mapa preciso de la realidad.",
         "Aceptacion radical",
         "Brach trabajaba con un hombre que se negaba a aceptar el diagnostico de cancer de su esposa. Gastaba sus energias buscando alternativas, negando. Cuando finalmente acepto la realidad, algo sorprendente ocurrio: se volvio presente y su esposa sintio que al fin estaba ahi.",
         "Piensa en algo en tu vida que aun resistes aceptar. Dilo en voz alta: 'Asi es ahora.' Observa si algo se libera."),
  "pt": ("A aceitacao nao e uma derrota. E um mapa preciso da realidade.",
         "Aceitacao radical",
         "Brach trabalhava com um homem que se recusava a aceitar o diagnostico de cancer de sua esposa. Gastava suas energias buscando alternativas, negando. Quando finalmente aceitou a realidade, algo surpreendente ocorreu: tornou-se presente e sua esposa sentiu que ele finalmente estava la.",
         "Pense em algo em sua vida que ainda resistir a aceitar. Diga em voz alta: 'E assim agora.' Observe se algo se libera."),
},
"349": {
  "fr": ("Tout ce qui t'irrite peut devenir ton professeur.",
         "Dhammapada",
         "Le Bouddha enseigna a un moine irrite par un eleve turbulent. Il lui demanda : qu'est-ce qui en toi est irrite ? Le moine realisa que son irritation refletait son attachement a son propre confort et son image d'enseignant parfait.",
         "Notez la derniere chose qui vous a irrite. Demandez-vous : qu'est-ce que cela revele sur une attente non satisfaite en moi ?"),
  "de": ("Alles, was dich irritiert, kann dein Lehrer werden.",
         "Dhammapada",
         "Der Buddha lehrte einen Monch, der von einem turbulenten Schuler geargert wurde. Er fragte ihn: Was in dir ist geargert? Der Monch erkannte, dass seine Irritation seine Bindung an seinen eigenen Komfort und sein Bild als perfekter Lehrer widerspiegelte.",
         "Notieren Sie das Letzte, das Sie irritiert hat. Fragen Sie sich: Was offenbart das uber eine nicht erfulle Erwartung in mir?"),
  "es": ("Todo lo que te irrita puede convertirse en tu maestro.",
         "Dhammapada",
         "Buda ensenо a un monje irritado por un alumno turbulento. Le pregunto: que en ti esta irritado? El monje se dio cuenta de que su irritacion reflejaba su apego a su propio confort y su imagen de maestro perfecto.",
         "Anota lo ultimo que te irrito. Preguntate: que revela esto sobre una expectativa insatisfecha en mi?"),
  "pt": ("Tudo o que te irrita pode se tornar teu professor.",
         "Dhammapada",
         "O Buda ensinou a um monge irritado por um aluno turbulento. Perguntou-lhe: o que em voce esta irritado? O monge percebeu que sua irritacao refletia seu apego ao seu proprio conforto e sua imagem de professor perfeito.",
         "Anote a ultima coisa que te irritou. Pergunte-se: o que isso revela sobre uma expectativa insatisfeita em mim?"),
},
"350": {
  "fr": ("A la fin, tout ira bien. Si ce n'est pas encore bien — c'est que ce n'est pas encore la fin.",
         "Interview, 1980",
         "Lennon dit ces mots lors d'une interview tardive, quelques semaines avant sa mort. Il parlait de ses propres luttes — la fame, la paix avec Yoko, les conflits dans les Beatles. La phrase n'etait pas de la naivete — c'etait une foi forgee par de nombreuses tempetes traversees.",
         "Pensez a une situation difficile actuelle. Pouvez-vous voir, même vaguement, comment elle pourrait se resoudre ? Si oui, c'est que la fin n'est pas encore arrivee."),
  "de": ("Am Ende wird alles gut sein. Wenn es noch nicht gut ist — dann ist es noch nicht das Ende.",
         "Interview, 1980",
         "Lennon sagte diese Worte in einem spaten Interview, wenige Wochen vor seinem Tod. Er sprach uber seine eigenen Kampfe — den Ruhm, den Frieden mit Yoko, die Konflikte in den Beatles. Der Satz war keine Naivitat — es war ein Glaube, der durch viele durchstandene Sturme geformt wurde.",
         "Denken Sie an eine aktuelle schwierige Situation. Konnen Sie, auch nur vage, sehen, wie sie sich losen konnte? Wenn ja, dann ist das Ende noch nicht gekommen."),
  "es": ("Al final todo estara bien. Si aun no esta bien, es que todavia no es el final.",
         "Entrevista, 1980",
         "Lennon dijo estas palabras en una entrevista tardia, pocas semanas antes de su muerte. Hablaba de sus propias luchas: la fama, la paz con Yoko, los conflictos en los Beatles. La frase no era ingenuidad: era una fe forjada por muchas tormentas atravesadas.",
         "Piensa en una situacion dificil actual. Puedes ver, aunque sea vagamente, como podria resolverse? Si es asi, es que el final aun no ha llegado."),
  "pt": ("No final tudo ficara bem. Se ainda nao esta bem, e porque ainda nao e o final.",
         "Entrevista, 1980",
         "Lennon disse essas palavras em uma entrevista tardia, poucas semanas antes de sua morte. Falava de suas proprias lutas: a fama, a paz com Yoko, os conflitos nos Beatles. A frase nao era ingenuidade: era uma fe forjada por muitas tempestades atravessadas.",
         "Pense em uma situacao dificil atual. Voce consegue ver, mesmo vagamente, como ela poderia se resolver? Se sim, e porque o final ainda nao chegou."),
},
}

for lang_code in ["fr","de","es","pt"]:
    with open(f'/tmp/new_cards_{lang_code}.json',encoding='utf-8') as f:
        cards=json.load(f)
    updated=0
    for card in cards:
        cid=card['id']
        if cid in T and lang_code in T[cid]:
            q,s,st,a=T[cid][lang_code]
            card['quote']=q;card['source']=s;card['story']=st;card['action']=a;updated+=1
    with open(f'/tmp/new_cards_{lang_code}.json','w',encoding='utf-8') as f:
        json.dump(cards,f,ensure_ascii=False,indent=2)
    print(f"{lang_code}: updated {updated} psychology cards")
