# -*- coding: utf-8 -*-
#!/usr/bin/env python3
import json

T = {
"121": {
  "fr": ("Ne considere jamais comme avantageux ce qui te forcerait a briser ta parole ou a perdre le respect de toi-meme.",
         "Meditations, Livre III",
         "Aurele ecrivit ceci apres une reunion avec un senateur qui lui proposa un compromis politiquement avantageux mais malhonnete. Au lieu de refuser directement, il ouvrit son journal et nota ce rappel : aucun avantage ne vaut la perte de l'integrite interieure.",
         "Rappelez-vous une promesse non tenue. Tenez-la aujourd'hui ou dites honnêtement a la personne que vous ne pouvez pas."),
  "de": ("Halte niemals etwas fur vorteilhaft, was dich zwingen wurde, dein Wort zu brechen oder deine Selbstachtung zu verlieren.",
         "Selbstbetrachtungen, Buch III",
         "Aurelius schrieb dies nach einem Treffen mit einem Senator, der ihm einen politisch vorteilhaften, aber unehrlichen Kompromiss anbot. Statt direkt abzulehnen, offnete er sein Tagebuch und schrieb diese Erinnerung: Kein Vorteil ist den Verlust innerer Integritat wert.",
         "Erinnern Sie sich an ein Versprechen, das Sie noch nicht gehalten haben. Halten Sie es heute oder sagen Sie der Person ehrlich, dass Sie es nicht konnen."),
  "es": ("Nunca consideres ventajoso lo que te obligaria a romper tu palabra o perder el respeto por ti mismo.",
         "Meditaciones, Libro III",
         "Aurelio escribio esto tras una reunion con un senador que le ofrecio un compromiso politicamente ventajoso pero deshonesto. En lugar de rechazarlo directamente, abrio su diario y escribio este recordatorio: ninguna ventaja vale la perdida de integridad interior.",
         "Recuerda una promesa que aun no has cumplido. Cumplela hoy o dile honestamente a esa persona que no puedes."),
  "pt": ("Nunca consideres vantajoso o que te forcaria a quebrar tua palavra ou perder o respeito por ti mesmo.",
         "Meditacoes, Livro III",
         "Aurelio escreveu isso apos uma reuniao com um senador que lhe ofereceu um compromisso politicamente vantajoso, mas desonesto. Em vez de recusar diretamente, abriu seu diario e escreveu esse lembrete: nenhuma vantagem vale a perda da integridade interior.",
         "Lembre-se de uma promessa que ainda nao cumpriu. Cumpra-a hoje ou diga honestamente a pessoa que nao pode."),
},
"122": {
  "fr": ("La perte n'est rien d'autre que le changement, et le changement est la joie de la nature.",
         "Meditations, Livre IV",
         "Aurele perdit cinq enfants en bas age. Chaque fois il revenait a la meme pensee : la nature reprend ce qu'elle avait donne. La douleur etait reelle — mais resister a la nature doublait la souffrance.",
         "Notez une chose perdue que vous n'avez pas encore acceptee. A cote, ecrivez : quelle nouvelle possibilite est nee grace a cette perte ?"),
  "de": ("Verlust ist nichts anderes als Veranderung, und Veranderung ist die Freude der Natur.",
         "Selbstbetrachtungen, Buch IV",
         "Aurelius verlor funf Kinder im fruhen Kindesalter. Jedes Mal kehrte er zum selben Gedanken zuruck: Die Natur nimmt zuruck, was sie gegeben hat. Der Schmerz war real — aber der Widerstand gegen die Natur verdoppelte das Leiden.",
         "Schreiben Sie etwas auf, das Sie verloren haben und noch nicht akzeptiert haben. Schreiben Sie daneben: Welche neue Moglichkeit entstand durch diesen Verlust?"),
  "es": ("La perdida no es mas que cambio, y el cambio es la alegria de la naturaleza.",
         "Meditaciones, Libro IV",
         "Aurelio perdio cinco hijos en su primera infancia. Cada vez regresaba al mismo pensamiento: la naturaleza toma de vuelta lo que dio. El dolor era real — pero resistir a la naturaleza duplicaba el sufrimiento.",
         "Anota algo que hayas perdido y aun no hayas aceptado. Al lado, escribe: que nueva posibilidad nacio gracias a esa perdida?"),
  "pt": ("A perda nao e nada alem de mudanca, e a mudanca e a alegria da natureza.",
         "Meditacoes, Livro IV",
         "Aurelio perdeu cinco filhos na primeira infancia. Cada vez voltava ao mesmo pensamento: a natureza retoma o que deu. A dor era real — mas resistir a natureza dobrava o sofrimento.",
         "Escreva algo que voce perdeu e ainda nao aceitou. Ao lado, escreva: que nova possibilidade nasceu gracas a essa perda?"),
},
"123": {
  "fr": ("N'attendez pas l'approbation des autres pour etre bon.",
         "Entretiens, Livre I",
         "Un jeune etudiant se plaignit a Epictete que sa famille ne valorisait pas ses etudes philosophiques. Epictete repondit : si la vertu exige l'approbation d'autrui, ce n'est plus une vertu.",
         "Aujourd'hui, faites une bonne action pour quelqu'un qui probablement ne vous remerciera pas. Remarquez votre sensation apres."),
  "de": ("Warte nicht auf die Zustimmung anderer, um gut zu sein.",
         "Gesprache, Buch I",
         "Ein junger Student beklagte sich bei Epiktet, dass seine Familie seine philosophischen Studien nicht schatzte. Epiktet antwortete: Wenn Tugend fremde Zustimmung erfordert, ist es keine Tugend mehr.",
         "Tun Sie heute etwas Gutes fur jemanden, der Sie wahrscheinlich nicht danken wird. Beobachten Sie Ihr Gefuhl danach."),
  "es": ("No esperes la aprobacion de los demas para ser bueno.",
         "Discursos, Libro I",
         "Un joven estudiante se quejo ante Epicteto de que su familia no valoraba sus estudios filosoficos. Epicteto respondio: si la virtud requiere aprobacion ajena, ya no es virtud.",
         "Hoy, haz una buena accion para alguien que probablemente no te lo agradecera. Nota tu sensacion despues."),
  "pt": ("Nao espere a aprovacao dos outros para ser bom.",
         "Conversacoes, Livro I",
         "Um jovem estudante se queixou a Epicteto de que sua familia nao valorizava seus estudos filosoficos. Epicteto respondeu: se a virtude exige aprovacao alheia, ja nao e virtude.",
         "Hoje, faca uma boa acao para alguem que provavelmente nao ira agradecer. Note sua sensacao depois."),
},
"124": {
  "fr": ("Traite chaque homme comme un ami, mais ne confie pas ton coeur a tous.",
         "Lettres a Lucilius, Lettre 3",
         "Lucilius ecrivit a Seneque au sujet d'un ami auquel il avait entierement fait confiance, mais qui l'avait trahi. Seneque repondit : la sagesse n'est ni de se fermer a tous, ni de s'ouvrir a chacun. La confiance se merite avec le temps.",
         "Pensez a quelqu'un a qui vous faites trop confiance trop vite. Fixez une limite interieure : ce que vous ne lui direz plus avant qu'il le merite."),
  "de": ("Behandle jeden Menschen wie einen Freund, aber vertraue nicht allen dein Herz an.",
         "Briefe an Lucilius, Brief 3",
         "Lucilius schrieb an Seneca uber einen Freund, dem er vollstandig vertraut hatte, der ihn aber verraten hatte. Seneca antwortete: Weisheit besteht weder darin, sich allen zu verschliessen, noch sich jedem zu offnen. Vertrauen wird mit der Zeit verdient.",
         "Denken Sie an jemanden, dem Sie zu schnell zu viel vertrauen. Setzen Sie eine innere Grenze: Was werden Sie ihm nicht mehr erzahlen, bevor er es verdient hat?"),
  "es": ("Trata a cada hombre como a un amigo, pero no confies tu corazon a todos.",
         "Cartas a Lucilio, Carta 3",
         "Lucilio escribio a Seneca sobre un amigo en quien habia confiado plenamente, pero que lo traiciono. Seneca respondio: la sabiduria no esta en cerrarse a todos ni en abrirse a cada uno. La confianza se gana con el tiempo.",
         "Piensa en alguien en quien confias demasiado rapido. Establece un limite interno: que no le diras mas antes de que se lo gane."),
  "pt": ("Trate cada homem como amigo, mas nao confie seu coracao a todos.",
         "Cartas a Lucilio, Carta 3",
         "Lucilio escreveu a Seneca sobre um amigo em quem havia confiado plenamente, mas que o traiu. Seneca respondeu: a sabedoria nao esta em fechar-se a todos nem em abrir-se a cada um. A confianca e conquistada com o tempo.",
         "Pense em alguem em quem voce confia rapido demais. Estabeleca um limite interno: o que nao lhe contara mais antes que ele mereca."),
},
"125": {
  "fr": ("Si le comportement de quelqu'un t'offense, rentre immediatement en toi-meme et demande : qu'y a-t-il en toi qui cause cette douleur ?",
         "Meditations, Livre VIII",
         "L'un des proches d'Aurele l'humilia publiquement lors d'un conseil. Aurele fit une pause, continua calmement. La nuit, il nota : l'irritation signale une instabilite interieure, pas la faute d'autrui.",
         "Rappelez-vous la derniere fois ou les mots de quelqu'un vous ont blesse plus que prevu. Demandez honnêtement : pourquoi cela m'a-t-il blesse precisement ?"),
  "de": ("Wenn das Verhalten eines anderen dich beleidigt, kehre sofort in dich selbst zuruck und frage: Was in dir verursacht diesen Schmerz?",
         "Selbstbetrachtungen, Buch VIII",
         "Einer der Vertrauten des Aurelius demutigte ihn offentlich. Aurelius machte eine Pause und fuhrte die Sitzung ruhig weiter. Nachts schrieb er: Irritation signalisiert innere Instabilitat, nicht die Schuld anderer.",
         "Erinnern Sie sich, wann die Worte von jemandem Sie mehr verletzt haben als erwartet. Fragen Sie ehrlich: Warum hat mich das getroffen?"),
  "es": ("Si la conducta de alguien te ofende, retirate inmediatamente a tu interior y pregunta: que hay en ti que causa ese dolor?",
         "Meditaciones, Libro VIII",
         "Uno de los allegados de Aurelio lo humillo publicamente. Aurelio hizo una pausa y continuo calmadamente. Por la noche anoto: la irritacion senala inestabilidad interior, no la culpa ajena.",
         "Recuerda la ultima vez que las palabras de alguien te hirieron mas de lo esperado. Preguntate honestamente: por que me afecto eso precisamente?"),
  "pt": ("Se o comportamento de alguem te ofende, recolhe-te imediatamente e pergunta: o que ha em ti que causa essa dor?",
         "Meditacoes, Livro VIII",
         "Um dos proximos de Aurelio o humilhou publicamente. Aurelio fez uma pausa e continuou calmamente. A noite anotou: a irritacao sinaliza instabilidade interior, nao a culpa alheia.",
         "Lembre-se da ultima vez em que as palavras de alguem te feriram mais do esperado. Pergunta honestamente: por que isso me atingiu?"),
},
"126": {
  "fr": ("L'homme qui ne connait pas le repos ne connait pas non plus la liberte.",
         "Lettres a Lucilius, Lettre 68",
         "Seneque ecrivit a Lucilius qui se plaignait d'etre epuise malgre sa retraite des affaires publiques. Seneque diagnostiqua : la liberation exterieure ne suffit pas si l'esprit reste agite. La vraie liberte commence dans la quietude interieure.",
         "Ce soir, reservez 10 minutes sans ecran, sans musique, sans agenda. Asseyez-vous simplement. Observez l'inconfort — puis le calme qui vient."),
  "de": ("Der Mensch, der keine Ruhe kennt, kennt auch keine Freiheit.",
         "Briefe an Lucilius, Brief 68",
         "Seneca schrieb an Lucilius, der klagte, erschopft zu sein, obwohl er sich aus dem offentlichen Leben zuruckgezogen hatte. Seneca diagnostizierte: Die aussere Befreiung reicht nicht, wenn der Geist unruhig bleibt. Wahre Freiheit beginnt in der inneren Stille.",
         "Reservieren Sie heute Abend 10 Minuten ohne Bildschirm, ohne Musik, ohne Agenda. Sitzen Sie einfach. Beobachten Sie das Unbehagen — und dann die kommende Stille."),
  "es": ("El hombre que no conoce el reposo tampoco conoce la libertad.",
         "Cartas a Lucilio, Carta 68",
         "Seneca escribio a Lucilio que se quejaba de estar agotado a pesar de su retiro de los asuntos publicos. Seneca diagnostico: la liberacion exterior no basta si la mente permanece agitada. La verdadera libertad comienza en la quietud interior.",
         "Esta noche, reserva 10 minutos sin pantalla, sin musica, sin agenda. Simplemente sientate. Observa la incomodidad y luego la calma que llega."),
  "pt": ("O homem que nao conhece o repouso tambem nao conhece a liberdade.",
         "Cartas a Lucilio, Carta 68",
         "Seneca escreveu a Lucilio que reclamava estar esgotado apesar de sua retirada dos assuntos publicos. Seneca diagnosticou: a libertacao exterior nao basta se a mente permanece agitada. A verdadeira liberdade comeca na quietude interior.",
         "Esta noite, reserve 10 minutos sem tela, sem musica, sem agenda. Simplesmente sente-se. Observe o desconforto e depois a calma que vem."),
},
"127": {
  "fr": ("La mort n'est rien pour nous : quand nous sommes, la mort n'est pas la; quand la mort est la, nous ne sommes plus.",
         "Lettre a Menocee",
         "Epicure ecrivit cette lettre a son ami Menocee qui avait peur de mourir. Il voulait lui montrer que la peur de la mort est irrationnelle : on ne peut jamais rencontrer la mort, car des que la mort arrive, on n'est plus la pour la vivre.",
         "Ecrivez ce que vous feriez differemment si vous saviez que vous n'auriez jamais peur de la mort. Choisissez une chose et commencez-la cette semaine."),
  "de": ("Der Tod ist nichts fur uns: Wenn wir sind, ist der Tod nicht da; wenn der Tod da ist, sind wir nicht mehr.",
         "Brief an Menoikeus",
         "Epikur schrieb diesen Brief an seinen Freund Menoikeus, der Angst vor dem Tod hatte. Er wollte ihm zeigen, dass die Todesfurcht irrational ist: Man kann dem Tod nie begegnen, denn sobald der Tod kommt, ist man nicht mehr da, um ihn zu erleben.",
         "Schreiben Sie, was Sie anders tun wurden, wenn Sie wussten, dass Sie nie Angst vor dem Tod haben wurden. Wahlen Sie eine Sache und beginnen Sie sie diese Woche."),
  "es": ("La muerte no es nada para nosotros: cuando somos, la muerte no esta; cuando la muerte esta, nosotros ya no somos.",
         "Carta a Meneceo",
         "Epicuro escribio esta carta a su amigo Meneceo que tenia miedo a morir. Queria mostrarle que el miedo a la muerte es irracional: nunca se puede encontrar la muerte, pues en cuanto llega, uno ya no esta para vivirla.",
         "Escribe que harias de forma diferente si supieras que nunca tendrias miedo a la muerte. Elige una cosa y comienza esta semana."),
  "pt": ("A morte nao e nada para nos: quando somos, a morte nao esta; quando a morte esta, nos nao estamos mais.",
         "Carta a Menoiceu",
         "Epicuro escreveu esta carta a seu amigo Menoiceu que tinha medo de morrer. Queria mostrar-lhe que o medo da morte e irracional: nunca se pode encontrar a morte, pois assim que ela chega, nao se esta mais la para vivê-la.",
         "Escreva o que faria de forma diferente se soubesse que nunca teria medo da morte. Escolha uma coisa e comece esta semana."),
},
"128": {
  "fr": ("Ce n'est pas ce qui arrive qui rend l'homme malheureux, mais ce qu'il pense de ce qui arrive.",
         "Manuel, chapitre 5",
         "Un etudiant d'Epictete se plaignit d'etre humilie par un ami riche. Epictete lui demanda : qu'est-ce qui t'a blesse — ses mots ou ta conviction que ses mots avaient du pouvoir sur toi ? L'etudiant resta silencieux.",
         "Pensez a quelque chose qui vous a contrarie recemment. Ecrivez : la situation, et separe, votre interpretation de la situation. Remarquez la difference."),
  "de": ("Nicht das, was geschieht, macht den Menschen ungluecklich, sondern das, was er uber das Geschehene denkt.",
         "Handbuchlein, Kapitel 5",
         "Ein Schuler Epiktets beklagte sich, von einem reichen Freund gedemuetigt worden zu sein. Epiktet fragte ihn: Was hat dich verletzt — seine Worte oder deine Uberzeugung, dass seine Worte Macht uber dich hatten? Der Schuler schwieg.",
         "Denken Sie an etwas, das Sie kurzlich aufgeregt hat. Schreiben Sie: die Situation und getrennt davon Ihre Interpretation der Situation. Bemerken Sie den Unterschied."),
  "es": ("No es lo que sucede lo que hace infeliz al hombre, sino lo que piensa sobre lo que sucede.",
         "Manual, capitulo 5",
         "Un estudiante de Epicteto se quejo de haber sido humillado por un amigo rico. Epicteto le pregunto: que te hirio, sus palabras o tu conviccion de que sus palabras tenian poder sobre ti? El estudiante quedo en silencio.",
         "Piensa en algo que te haya molestado recientemente. Escribe: la situacion y, por separado, tu interpretacion de la situacion. Observa la diferencia."),
  "pt": ("Nao e o que acontece que torna o homem infeliz, mas o que ele pensa sobre o que acontece.",
         "Manual, capitulo 5",
         "Um estudante de Epicteto reclamou ter sido humilhado por um amigo rico. Epicteto perguntou-lhe: o que te feriu, as suas palavras ou a sua conviccao de que as suas palavras tinham poder sobre voce? O estudante ficou em silencio.",
         "Pense em algo que te incomodou recentemente. Escreva: a situacao e, separadamente, sua interpretacao da situacao. Note a diferenca."),
},
"129": {
  "fr": ("Supporte et abstiens-toi.",
         "Discours moraux",
         "Cette maxime d'Epictete etait inscrite a l'entree de son ecole. Les visiteurs demandaient souvent : est-ce tout ? Epictete repondait : oui. Supporte ce qui est inevitable. Abstiens-toi de ce qui n'est pas necessaire. Presque tout ce que nous souffrons vient de l'incapacite a faire l'un ou l'autre.",
         "Aujourd'hui, identifiez une chose que vous devez supporter et une chose dont vous devez vous abstenir. Pratiquez les deux consciemment."),
  "de": ("Ertrage und enthalte dich.",
         "Moralische Abhandlungen",
         "Dieses Motto Epiktets war am Eingang seiner Schule eingraviert. Besucher fragten oft: Ist das alles? Epiktet antwortete: Ja. Ertrage, was unvermeidlich ist. Enthalte dich dessen, was nicht notwendig ist. Fast alles, was wir leiden, kommt von der Unfahigkeit, eines von beiden zu tun.",
         "Identifizieren Sie heute etwas, das Sie ertragen mussen, und etwas, wovon Sie sich enthalten mussen. Uben Sie beides bewusst."),
  "es": ("Soporta y abstente.",
         "Discursos morales",
         "Esta maxima de Epicteto estaba grabada a la entrada de su escuela. Los visitantes preguntaban a menudo: es todo? Epicteto respondia: si. Soporta lo inevitable. Abstente de lo innecesario. Casi todo lo que sufrimos viene de la incapacidad de hacer una u otra cosa.",
         "Hoy identifica algo que debes soportar y algo de lo que debes abstenerte. Practica ambas conscientemente."),
  "pt": ("Suporta e abstente-te.",
         "Discursos morais",
         "Esta maxima de Epicteto estava gravada na entrada de sua escola. Os visitantes frequentemente perguntavam: e so isso? Epicteto respondia: sim. Suporte o inevitavel. Abstenha-se do desnecessario. Quase tudo o que sofremos vem da incapacidade de fazer uma ou outra coisa.",
         "Hoje identifique algo que deve suportar e algo do qual deve se abster. Pratique ambos conscientemente."),
},
"130": {
  "fr": ("Vis comme si tu vivais une deuxieme fois et que tu avais agi comme tu t'appretes a agir la premiere fois.",
         "Decider sa vie",
         "Frankl developpa cet exercice de pensee dans les camps de concentration. Imaginer qu'on rejoue sa vie avec la conscience de ce qui vient l'aidait a choisir differemment dans les moments de tentation ou de faiblesse.",
         "Pensez a une decision que vous vous appretez a prendre. Imaginez que vous la revivez dans 10 ans. Que choisiriez-vous alors ?"),
  "de": ("Lebe, als ob du ein zweites Mal lebst und als hattest du beim ersten Mal so gehandelt, wie du jetzt zu handeln im Begriff bist.",
         "...trotzdem Ja zum Leben sagen",
         "Frankl entwickelte diese Gedankenuebung in den Konzentrationslagern. Sich vorzustellen, dass man sein Leben mit dem Bewusstsein des Kommenden neu spielt, half ihm, in Momenten der Versuchung oder Schwache anders zu wahlen.",
         "Denken Sie an eine Entscheidung, die Sie gerade treffen wollen. Stellen Sie sich vor, Sie erleben sie in 10 Jahren neu. Was wurden Sie dann wahlen?"),
  "es": ("Vive como si vivieras por segunda vez y como si la primera vez hubieras actuado como estas a punto de actuar ahora.",
         "El hombre en busca de sentido",
         "Frankl desarrollo este ejercicio mental en los campos de concentracion. Imaginarse que revive su vida con conciencia de lo que viene le ayudaba a elegir de forma diferente en momentos de tentacion o debilidad.",
         "Piensa en una decision que estas a punto de tomar. Imagina que la revives dentro de 10 anos. Que elegiras entonces?"),
  "pt": ("Viva como se vivesse pela segunda vez e como se na primeira vez tivesse agido como esta prestes a agir agora.",
         "Em busca de sentido",
         "Frankl desenvolveu esse exercicio mental nos campos de concentracao. Imaginar que revive sua vida com a consciencia do que vem o ajudava a escolher de forma diferente em momentos de tentacao ou fraqueza.",
         "Pense em uma decisao que esta prestes a tomar. Imagine que a revive daqui a 10 anos. O que escolheria entao?"),
},
"131": {
  "fr": ("La philosophie ne promet rien d'exterieur a l'homme.",
         "Entretiens, Livre I",
         "Un riche commercant vint trouver Epictete en esperant que la philosophie lui apporterait prestige et succes. Epictete lui repondit directement : la philosophie ne rend pas riche, celebre ou populaire. Elle t'aide a etre libre — ce qui est infiniment plus rare.",
         "Demandez-vous : pourquoi est-ce que je cherche a me developper en ce moment — pour paraitre ou pour etre ? La reponse honnete guide les prochaines actions."),
  "de": ("Die Philosophie verspricht dem Menschen nichts Ausseres.",
         "Gesprache, Buch I",
         "Ein reicher Kaufmann kam zu Epiktet in der Hoffnung, dass die Philosophie ihm Prestige und Erfolg bringen wurde. Epiktet antwortete direkt: Philosophie macht nicht reich, beruehmt oder beliebt. Sie hilft dir, frei zu sein — was unendlich seltener ist.",
         "Fragen Sie sich: Warum strebe ich gerade nach Entwicklung — um zu erscheinen oder um zu sein? Die ehrliche Antwort leitet die nachsten Handlungen."),
  "es": ("La filosofia no le promete nada externo al hombre.",
         "Discursos, Libro I",
         "Un rico comerciante vino a ver a Epicteto esperando que la filosofia le trajera prestigio y exito. Epicteto le respondio directamente: la filosofia no te hace rico, famoso ni popular. Te ayuda a ser libre, lo cual es infinitamente mas raro.",
         "Preguntate: por que busco desarrollarme en este momento, para parecer o para ser? La respuesta honesta guia las proximas acciones."),
  "pt": ("A filosofia nao promete nada externo ao homem.",
         "Conversacoes, Livro I",
         "Um rico comerciante veio ver Epicteto esperando que a filosofia lhe trouxesse prestigio e sucesso. Epicteto respondeu diretamente: a filosofia nao te faz rico, famoso nem popular. Ela te ajuda a ser livre, o que e infinitamente mais raro.",
         "Pergunte-se: por que busco me desenvolver neste momento, para parecer ou para ser? A resposta honesta guia as proximas acoes."),
},
"132": {
  "fr": ("Fais ce que la nature exige en ce moment. Pars immediatement si tu en as la possibilite.",
         "Meditations, Livre VIII",
         "Aurele ecrivit cela un matin ou il avait du mal a quitter son lit, sachant qu'une longue journee de responsabilites imperiales l'attendait. Il se rappela : la nature exige que tu te leves, que tu agisses, que tu ne t'attardes pas dans le confort.",
         "Identifiez une chose que vous reportez depuis des jours. La nature exige-t-elle que vous la fassiez ? Si oui, faites-la dans la prochaine heure."),
  "de": ("Tu, was die Natur jetzt verlangt. Geh sofort, wenn du die Moglichkeit hast.",
         "Selbstbetrachtungen, Buch VIII",
         "Aurelius schrieb dies an einem Morgen, an dem er Schwierigkeiten hatte, sein Bett zu verlassen, da er wusste, dass ein langer Tag kaiserlicher Pflichten auf ihn wartete. Er erinnerte sich: Die Natur verlangt, dass du aufstehst, handelst und dich nicht im Komfort aufhaltst.",
         "Identifizieren Sie etwas, das Sie seit Tagen aufschieben. Verlangt die Natur, dass Sie es tun? Wenn ja, tun Sie es in der nachsten Stunde."),
  "es": ("Haz lo que la naturaleza exige ahora mismo. Parte de inmediato si tienes la posibilidad.",
         "Meditaciones, Libro VIII",
         "Aurelio escribio esto una manana en que le costaba levantarse de la cama, sabiendo que le esperaba un largo dia de responsabilidades imperiales. Se recordo: la naturaleza exige que te levantes, actues, y no te demores en la comodidad.",
         "Identifica algo que llevas dias postergando. Lo exige la naturaleza? Si es asi, hazlo en la proxima hora."),
  "pt": ("Faca o que a natureza exige agora. Parte imediatamente se tens a possibilidade.",
         "Meditacoes, Livro VIII",
         "Aurelio escreveu isso numa manha em que tinha dificuldade de sair da cama, sabendo que um longo dia de responsabilidades imperiais o aguardava. Lembrou-se: a natureza exige que te levantes, ajas, e nao te demores no conforto.",
         "Identifique algo que esta adiando ha dias. A natureza exige que o faca? Se sim, faca-o na proxima hora."),
},
"133": {
  "fr": ("Nous ne pouvons pas choisir les circonstances exterieures, mais nous pouvons toujours choisir comment y repondre.",
         "Manuel, chapitre 1",
         "Epictete vecut comme esclave pendant de nombreuses annees. Ses maitres pouvaient controler son corps, mais pas sa pensee. Il decouvrit que meme en captivite totale, une zone de liberte restait intacte : la reponse interieure aux evenements.",
         "Aujourd'hui, face a une circonstance desagreable que vous ne pouvez pas changer, ecrivez trois facons differentes d'y repondre. Choisissez la meilleure."),
  "de": ("Wir konnen die ausseren Umstande nicht wahlen, aber wir konnen immer wahlen, wie wir reagieren.",
         "Handbuchlein, Kapitel 1",
         "Epiktet lebte viele Jahre als Sklave. Seine Herren konnten seinen Korper kontrollieren, aber nicht seine Gedanken. Er entdeckte, dass selbst in totaler Gefangenschaft eine Zone der Freiheit intakt blieb: die innere Reaktion auf Ereignisse.",
         "Schreiben Sie heute angesichts eines unangenehmen Umstands, den Sie nicht andern konnen, drei verschiedene Reaktionsmoglichkeiten auf. Wahlen Sie die beste."),
  "es": ("No podemos elegir las circunstancias externas, pero siempre podemos elegir como responder.",
         "Manual, capitulo 1",
         "Epicteto vivio como esclavo durante muchos anos. Sus amos podian controlar su cuerpo, pero no su pensamiento. Descubrio que incluso en cautiverio total, una zona de libertad permanecia intacta: la respuesta interior a los eventos.",
         "Hoy, ante una circunstancia desagradable que no puedes cambiar, escribe tres formas distintas de responder. Elige la mejor."),
  "pt": ("Nao podemos escolher as circunstancias externas, mas sempre podemos escolher como responder.",
         "Manual, capitulo 1",
         "Epicteto viveu como escravo por muitos anos. Seus donos podiam controlar seu corpo, mas nao seu pensamento. Descobriu que mesmo em cativeiro total, uma zona de liberdade permanecia intacta: a resposta interior aos eventos.",
         "Hoje, diante de uma circunstancia desagradavel que nao pode mudar, escreva tres formas diferentes de responder. Escolha a melhor."),
},
"134": {
  "fr": ("Le bonheur de ceux qui peuvent se donner le bonheur.",
         "Meditations, Livre VII",
         "Aurele ecrivit ces mots apres avoir observe des courtisans qui dependaient entierement des humeurs imperiales pour leur propre joie. Il nota : quelle fragilite que d'avoir besoin d'autrui pour etre heureux. Le sage trouve le bonheur en lui-meme.",
         "Identifiez une chose qui vous rendrait heureux aujourd'hui et qui ne depend pas d'une autre personne. Faites-la."),
  "de": ("Das Gluck derer, die sich ihr Gluck selbst geben konnen.",
         "Selbstbetrachtungen, Buch VII",
         "Aurelius schrieb diese Worte, nachdem er Hofleute beobachtet hatte, die vollstandig von kaiserlicher Stimmung fur ihre eigene Freude abhingen. Er notierte: Welche Zerbrechlichkeit, andere zu benotigen, um glucklich zu sein. Der Weise findet Gluck in sich selbst.",
         "Identifizieren Sie etwas, das Sie heute glucklich machen wurde und nicht von einer anderen Person abhangt. Tun Sie es."),
  "es": ("La felicidad de quienes pueden darse la felicidad a si mismos.",
         "Meditaciones, Libro VII",
         "Aurelio escribio estas palabras tras observar a cortesanos que dependian completamente del humor imperial para su propia alegria. Anoto: que fragilidad necesitar de otros para ser feliz. El sabio encuentra la felicidad en si mismo.",
         "Identifica algo que te haria feliz hoy y que no dependa de otra persona. Hazlo."),
  "pt": ("A felicidade daqueles que podem se dar a felicidade.",
         "Meditacoes, Livro VII",
         "Aurelio escreveu essas palavras apos observar cortesaos que dependiam completamente do humor imperial para sua propria alegria. Anotou: que fragilidade necessitar de outros para ser feliz. O sabio encontra a felicidade em si mesmo.",
         "Identifique algo que te tornaria feliz hoje e que nao depende de outra pessoa. Faca isso."),
},
"135": {
  "fr": ("Le temps passe pendant que nous hesisons.",
         "Lettres a Lucilius, Lettre 1",
         "Seneque ecrivit cette lettre a Lucilius en reponse a sa plainte que la vie passait trop vite. Seneque corrigea son ami : la vie ne passe pas — nous la gaspillons. Chaque heure d'hesitation est une heure perdue que nul ne recuperera.",
         "Pensez a une decision que vous hesitez a prendre depuis plus d'une semaine. Decidez maintenant — meme imparfaitement. L'action imparfaite vaut mieux que la parfaite inaction."),
  "de": ("Die Zeit vergeht, wahrend wir zogern.",
         "Briefe an Lucilius, Brief 1",
         "Seneca schrieb diesen Brief an Lucilius als Antwort auf dessen Klage, dass das Leben zu schnell vergehe. Seneca korrigierte seinen Freund: Das Leben vergeht nicht — wir verschwenden es. Jede Stunde des Zogerns ist eine verlorene Stunde, die niemand zuruckgewinnen wird.",
         "Denken Sie an eine Entscheidung, bei der Sie seit mehr als einer Woche zogern. Entscheiden Sie jetzt — auch wenn es unvollkommen ist. Unvollkommenes Handeln ist besser als vollkommene Untätigkeit."),
  "es": ("El tiempo pasa mientras dudamos.",
         "Cartas a Lucilio, Carta 1",
         "Seneca escribio esta carta a Lucilio en respuesta a su queja de que la vida pasaba demasiado rapido. Seneca corrigio a su amigo: la vida no pasa, la desperdiciamos. Cada hora de duda es una hora perdida que nadie recuperara.",
         "Piensa en una decision que llevas mas de una semana dudando en tomar. Decidete ahora, aunque sea imperfectamente. La accion imperfecta vale mas que la perfecta inaccion."),
  "pt": ("O tempo passa enquanto hesitamos.",
         "Cartas a Lucilio, Carta 1",
         "Seneca escreveu esta carta a Lucilio em resposta a sua queixa de que a vida passava rapido demais. Seneca corrigiu seu amigo: a vida nao passa, nos a desperdicamos. Cada hora de hesitacao e uma hora perdida que ninguem recuperara.",
         "Pense em uma decisao que esta hesitando em tomar ha mais de uma semana. Decida agora, mesmo que seja imperfeito. A acao imperfeita vale mais do que a perfeita inacao."),
},
"136": {
  "fr": ("Celui qui craint la mort ne fera rien digne de la vie.",
         "Lettres a Lucilius, Lettre 77",
         "Seneque ecrivit a Lucilius qui avait failli se noyer et etait devenu obssede par la mort. Seneque repondit : la mort n'est pas ce qui te menace — c'est de vivre en retrait par peur de la mort qui t'appauvrit. Vise grandement, sachant que tout finit.",
         "Ecrivez une chose que vous n'avez pas encore osee faire par peur des consequences. Est-ce que cette peur serait encore la si vous n'aviez plus peur de la mort ?"),
  "de": ("Wer den Tod furchtet, wird nichts tun, was des Lebens wurde ist.",
         "Briefe an Lucilius, Brief 77",
         "Seneca schrieb an Lucilius, der beinahe ertrunken war und von der Angst vor dem Tod besessen wurde. Seneca antwortete: Der Tod bedroht dich nicht — es ist das Zuruckziehen aus Todesfurcht, das dich verarmt. Strebe gross an, im Wissen, dass alles endet.",
         "Schreiben Sie etwas, das Sie aus Angst vor den Konsequenzen noch nicht gewagt haben. Ware diese Angst noch da, wenn Sie keine Angst mehr vor dem Tod hatten?"),
  "es": ("El que teme a la muerte no hara nada digno de la vida.",
         "Cartas a Lucilio, Carta 77",
         "Seneca escribio a Lucilio, que casi habia muerto ahogado y se habia obsesionado con la muerte. Seneca respondio: la muerte no te amenaza, es vivir retraido por miedo a la muerte lo que te empobrece. Aspira en grande, sabiendo que todo termina.",
         "Escribe algo que aun no te has atrevido a hacer por miedo a las consecuencias. Ese miedo seguiria ahi si ya no tuvieras miedo a la muerte?"),
  "pt": ("Quem teme a morte nao fara nada digno da vida.",
         "Cartas a Lucilio, Carta 77",
         "Seneca escreveu a Lucilio, que quase morreu afogado e ficou obcecado com a morte. Seneca respondeu: a morte nao te ameaca, e viver retraido por medo da morte que te empobrece. Aspire alto, sabendo que tudo termina.",
         "Escreva algo que ainda nao se atreveu a fazer por medo das consequencias. Esse medo ainda estaria la se voce nao tivesse mais medo da morte?"),
},
"137": {
  "fr": ("Rien de grand dans le monde ne s'est accompli sans passion.",
         "Lecons sur la philosophie de l'histoire",
         "Hegel observa les grands conquerants et reformateurs de l'histoire et nota qu'aucun d'eux n'agissait par devoir sec. Chacun etait anime par quelque chose de plus grand — une vision, une conviction, une passion qui depassait la raison pure.",
         "Identifiez la passion qui sous-tend votre travail actuel. Si vous n'en trouvez pas, demandez-vous : ou est-elle allee ? Comment la rallumer ?"),
  "de": ("Nichts Grosses in der Welt ist ohne Leidenschaft vollbracht worden.",
         "Vorlesungen uber die Philosophie der Geschichte",
         "Hegel beobachtete die grossen Eroberer und Reformer der Geschichte und stellte fest, dass keiner von ihnen aus trockener Pflicht handelte. Jeder wurde von etwas Grosserem angetrieben — einer Vision, einer Uberzeugung, einer Leidenschaft, die uber die reine Vernunft hinausging.",
         "Identifizieren Sie die Leidenschaft, die Ihrer aktuellen Arbeit zugrunde liegt. Wenn Sie keine finden, fragen Sie sich: Wo ist sie geblieben? Wie kann ich sie wieder entfachen?"),
  "es": ("Nada grande en el mundo se ha cumplido sin pasion.",
         "Lecciones sobre la filosofia de la historia",
         "Hegel observo a los grandes conquistadores y reformadores de la historia y noto que ninguno actuaba por puro deber. Cada uno estaba impulsado por algo mas grande: una vision, una conviccion, una pasion que superaba la razon pura.",
         "Identifica la pasion que subyace a tu trabajo actual. Si no la encuentras, preguntate: adonde fue? Como puedo reavivarla?"),
  "pt": ("Nada grande no mundo se realizou sem paixao.",
         "Licoes sobre a filosofia da historia",
         "Hegel observou os grandes conquistadores e reformadores da historia e notou que nenhum agia por dever seco. Cada um era impulsionado por algo maior: uma visao, uma conviccao, uma paixao que superava a razao pura.",
         "Identifique a paixao que fundamenta seu trabalho atual. Se nao encontrar, pergunte-se: para onde foi? Como reacende-la?"),
},
"138": {
  "fr": ("Sois severe avec toi-meme et indulgent avec les autres.",
         "Entretiens, chapitre XII",
         "Confucius observa deux de ses disciples qui se querellaient, chacun pointant les fautes de l'autre. Il leur demanda : combien de temps avez-vous consacre a examiner vos propres fautes ce mois-ci ? Les deux se turent. Il conclut : commence par toi-meme.",
         "Ce soir, evaluez une decision que vous avez prise aujourd'hui avec la meme severite que vous appliquez aux autres. Puis pensez a quelqu'un que vous avez juge et demandez-vous si vous avez ete juste."),
  "de": ("Sei streng mit dir selbst und nachsichtig mit anderen.",
         "Gesprache, Kapitel XII",
         "Konfuzius beobachtete zwei seiner Junger, die stritten und gegenseitig auf die Fehler des anderen zeigten. Er fragte sie: Wie viel Zeit haben Sie in diesem Monat damit verbracht, Ihre eigenen Fehler zu untersuchen? Beide schwiegen. Er schloss: Fang bei dir selbst an.",
         "Bewerten Sie heute Abend eine Entscheidung, die Sie heute getroffen haben, mit derselben Strenge, die Sie auf andere anwenden. Denken Sie dann an jemanden, den Sie beurteilt haben, und fragen Sie sich, ob Sie fair waren."),
  "es": ("Se severo contigo mismo e indulgente con los demas.",
         "Conversaciones, capitulo XII",
         "Confucio observo a dos de sus discipulos que se disputaban, cada uno senalando los defectos del otro. Les pregunto: cuanto tiempo dedicaron este mes a examinar sus propios defectos? Ambos callaron. Concluyo: empieza por ti mismo.",
         "Esta noche, evalua una decision que tomaste hoy con la misma severidad que aplicas a los demas. Luego piensa en alguien a quien hayas juzgado y preguntate si fuiste justo."),
  "pt": ("Sê severo contigo mesmo e indulgente com os outros.",
         "Conversacoes, capitulo XII",
         "Confucio observou dois de seus discipulos que discutiam, cada um apontando as falhas do outro. Perguntou-lhes: quanto tempo dedicaram este mes a examinar suas proprias falhas? Ambos ficaram em silencio. Concluiu: comece por voce mesmo.",
         "Esta noite, avalie uma decisao que tomou hoje com a mesma severidade que aplica aos outros. Em seguida pense em alguem que julgou e pergunte-se se foi justo."),
},
"139": {
  "fr": ("La plus douce des victoires, c'est de se vaincre soi-meme.",
         "Les Lois, Livre I",
         "Platon rapporta que les Jeux olympiques etaient celebres non seulement pour honorer les vainqueurs sportifs, mais pour rappeler que la victoire sur soi-meme est superieure a toute victoire sur autrui. Un champion peut etre vaincu par ses propres desirs.",
         "Identifiez une habitude ou une impulsion que vous avez du mal a controler. Resistez-y consciemment aujourd'hui une fois. Notez comment vous vous sentez apres."),
  "de": ("Das Susseste der Siege ist, sich selbst zu besiegen.",
         "Die Gesetze, Buch I",
         "Platon berichtete, dass die Olympischen Spiele nicht nur gefeiert wurden, um Sportsieger zu ehren, sondern um daran zu erinnern, dass der Sieg uber sich selbst jedem Sieg uber andere uberlegen ist. Ein Champion kann von seinen eigenen Begierden besiegt werden.",
         "Identifizieren Sie eine Gewohnheit oder einen Impuls, den Sie schwer kontrollieren konnen. Widerstehen Sie ihm heute bewusst einmal. Notieren Sie, wie Sie sich danach fuhlen."),
  "es": ("La mas dulce de las victorias es vencerse a uno mismo.",
         "Las Leyes, Libro I",
         "Platon relato que los Juegos Olimpicos se celebraban no solo para honrar a los vencedores deportivos, sino para recordar que la victoria sobre uno mismo es superior a cualquier victoria sobre los demas. Un campeon puede ser derrotado por sus propios deseos.",
         "Identifica un habito o impulso que te cuesta controlar. Resiste conscientemente hoy una vez. Anota como te sientes despues."),
  "pt": ("A mais doce das vitorias e vencer a si mesmo.",
         "As Leis, Livro I",
         "Platao relatou que os Jogos Olimpicos eram celebrados nao so para honrar os vencedores esportivos, mas para lembrar que a vitoria sobre si mesmo e superior a qualquer vitoria sobre os outros. Um campiao pode ser derrotado por seus proprios desejos.",
         "Identifique um habito ou impulso que tem dificuldade de controlar. Resista conscientemente uma vez hoje. Anote como se sente depois."),
},
"140": {
  "fr": ("Quand tu seras fatigue de la vanite, retire-toi en toi-meme autant que tu peux.",
         "Meditations, Livre IV",
         "Aurele ecrivit cela pendant une campagne militaire, au milieu du bruit des soldats et des decisions urgentes. Il nota que l'agitation exterieure est incontournable, mais que chaque homme possede un espace interieur ou la paix est toujours accessible.",
         "Accordez-vous 5 minutes de retraite interieure aujourd'hui — fermez les yeux, respirez, observez vos pensees sans y reagir. Meme au bureau, meme en deplacement."),
  "de": ("Wenn du der Eitelkeit mude bist, ziehe dich in dich selbst zuruck, so weit du kannst.",
         "Selbstbetrachtungen, Buch IV",
         "Aurelius schrieb dies wahrend eines Militarfeldzugs, inmitten des Larms der Soldaten und dringender Entscheidungen. Er notierte, dass aussere Unruhe unvermeidlich ist, aber dass jeder Mensch einen inneren Raum besitzt, in dem Frieden immer zuganglich ist.",
         "Gonnen Sie sich heute 5 Minuten innerer Ruhe — schliessen Sie die Augen, atmen Sie, beobachten Sie Ihre Gedanken ohne zu reagieren. Auch im Buro, auch unterwegs."),
  "es": ("Cuando estes cansado de la vanidad, retira en ti mismo todo lo que puedas.",
         "Meditaciones, Libro IV",
         "Aurelio escribio esto durante una campana militar, en medio del ruido de los soldados y las decisiones urgentes. Anoto que la agitacion exterior es inevitable, pero que cada hombre posee un espacio interior donde la paz siempre es accesible.",
         "Date 5 minutos de retiro interior hoy: cierra los ojos, respira, observa tus pensamientos sin reaccionar. Aunque sea en la oficina o de camino."),
  "pt": ("Quando estiveres cansado da vaidade, recolhe-te em ti mesmo o quanto puderes.",
         "Meditacoes, Livro IV",
         "Aurelio escreveu isso durante uma campanha militar, em meio ao barulho dos soldados e das decisoes urgentes. Anotou que a agitacao exterior e inevitavel, mas que cada homem possui um espaco interior onde a paz e sempre acessivel.",
         "Conceda-se 5 minutos de recolhimento interior hoje: feche os olhos, respire, observe seus pensamentos sem reagir. Mesmo no escritorio, mesmo a caminho."),
},
"141": {
  "fr": ("Le sage porte tout ce qui lui appartient avec lui.",
         "Fragments stoiciens",
         "Stilpon de Megare perdit sa ville, sa famille et ses biens lors d'une conquete militaire. Quand le conquerant lui demanda s'il avait perdu quelque chose, il repondit : non. Car tout ce qui m'appartient vraiment — ma raison, ma vertu, mon caractere — est toujours avec moi.",
         "Imaginez que vous perdez tout ce que vous possedez. Qu'est-ce que personne ne peut vous prendre ? C'est votre richesse veritable."),
  "de": ("Der Weise tragt alles, was ihm gehort, bei sich.",
         "Stoische Fragmente",
         "Stilpon von Megara verlor seine Stadt, seine Familie und seinen Besitz bei einer Militareroberung. Als der Eroberer ihn fragte, ob er etwas verloren habe, antwortete er: Nein. Denn alles, was mir wirklich gehort — meine Vernunft, meine Tugend, meinen Charakter — trage ich immer bei mir.",
         "Stellen Sie sich vor, Sie verlieren alles, was Sie besitzen. Was kann Ihnen niemand wegnehmen? Das ist Ihr wahrer Reichtum."),
  "es": ("El sabio lleva consigo todo lo que le pertenece.",
         "Fragmentos estoicos",
         "Stilpon de Megara perdio su ciudad, su familia y sus bienes en una conquista militar. Cuando el conquistador le pregunto si habia perdido algo, respondio: no. Porque todo lo que verdaderamente me pertenece, mi razon, mi virtud, mi caracter, siempre esta conmigo.",
         "Imagina que pierdes todo lo que posees. Que es lo que nadie puede quitarte? Esa es tu verdadera riqueza."),
  "pt": ("O sabio carrega tudo o que lhe pertence consigo.",
         "Fragmentos estoicos",
         "Estilpon de Megara perdeu sua cidade, sua familia e seus bens em uma conquista militar. Quando o conquistador lhe perguntou se havia perdido algo, respondeu: nao. Pois tudo o que verdadeiramente me pertence, minha razao, minha virtude, meu carater, sempre esta comigo.",
         "Imagine que perde tudo o que possui. O que ninguem pode te tirar? Essa e sua verdadeira riqueza."),
},
"142": {
  "fr": ("Cesse de parler de ce que devrait etre un homme bon, et sois-le.",
         "Meditations, Livre X",
         "Aurele s'impatientait des philosophes de cour qui passaient des heures a theoriser sur la vertu tout en practiquant la flatterie et la corruption. Il ecrivit cet aphorisme comme reproche a lui-meme autant qu'aux autres : les mots sans actes sont du vent.",
         "Pensez a une valeur que vous affirmez souvent verbalement. Evaluez honnêtement votre comportement des 7 derniers jours. Correspond-il a cette valeur ?"),
  "de": ("Hor auf davon zu reden, wie ein guter Mensch sein sollte, und sei einer.",
         "Selbstbetrachtungen, Buch X",
         "Aurelius wurde ungeduldiger mit den Hofphilosophen, die stundenlang uber Tugend theorisierten und gleichzeitig Schmeichelei und Korruption praktizierten. Er schrieb diesen Aphorismus als Tadel an sich selbst ebenso wie an andere: Worte ohne Taten sind Wind.",
         "Denken Sie an einen Wert, den Sie oft verbal behaupten. Bewerten Sie ehrlich Ihr Verhalten der letzten 7 Tage. Entspricht es diesem Wert?"),
  "es": ("Deja de hablar de como debe ser un hombre bueno, y selo.",
         "Meditaciones, Libro X",
         "Aurelio se impacientaba con los filosofos de corte que pasaban horas teorizando sobre la virtud mientras practicaban la adulacion y la corrupcion. Escribio este aforismo como reproche para si mismo tanto como para los demas: las palabras sin actos son viento.",
         "Piensa en un valor que afirmas verbalmente con frecuencia. Evalua honestamente tu comportamiento en los ultimos 7 dias. Coincide con ese valor?"),
  "pt": ("Para de falar de como deve ser um homem bom e se-o.",
         "Meditacoes, Livro X",
         "Aurelio ficava impaciente com os filosofos da corte que passavam horas teorizando sobre a virtude enquanto praticavam a adulacao e a corrupcao. Escreveu esse aforismo como reproche a si mesmo tanto quanto aos outros: palavras sem atos sao vento.",
         "Pense em um valor que afirma verbalmente com frequencia. Avalie honestamente seu comportamento nos ultimos 7 dias. Corresponde a esse valor?"),
},
"143": {
  "fr": ("Aucun vent ne sera favorable pour celui qui ne sait pas vers quel port il navigue.",
         "Lettres a Lucilius, Lettre 71",
         "Seneque repondit a Lucilius qui se plaignait que tout semblait aller de travers. Il lui posa cette question : ou veux-tu aller ? Lucilius ne sut pas repondre. Seneque conclut : la confusion vient rarement de mauvaise chance — elle vient du manque de direction.",
         "Ecrivez en une phrase votre objectif principal pour l'annee. Si vous ne pouvez pas, c'est le premier probleme a resoudre."),
  "de": ("Kein Wind wird gunstig fur den sein, der nicht weiss, in welchen Hafen er segelt.",
         "Briefe an Lucilius, Brief 71",
         "Seneca antwortete Lucilius, der klagte, dass alles schief zu laufen schien. Er stellte ihm diese Frage: Wo willst du hingehen? Lucilius wusste keine Antwort. Seneca schloss: Verwirrung kommt selten von schlechtem Pech — sie kommt vom Mangel an Richtung.",
         "Schreiben Sie in einem Satz Ihr Hauptziel fur das Jahr auf. Wenn Sie das nicht konnen, ist das das erste Problem, das es zu losen gilt."),
  "es": ("Ningun viento sera favorable para quien no sabe hacia que puerto navega.",
         "Cartas a Lucilio, Carta 71",
         "Seneca respondio a Lucilio que se quejaba de que todo parecia ir mal. Le hizo esta pregunta: adonde quieres ir? Lucilio no supo responder. Seneca concluyo: la confusion rara vez viene de la mala suerte, viene de la falta de direccion.",
         "Escribe en una frase tu objetivo principal para el ano. Si no puedes, ese es el primer problema que resolver."),
  "pt": ("Nenhum vento sera favoravel para quem nao sabe para que porto navega.",
         "Cartas a Lucilio, Carta 71",
         "Seneca respondeu a Lucilio que reclamava que tudo parecia dar errado. Fez-lhe esta pergunta: para onde quer ir? Lucilio nao soube responder. Seneca concluiu: a confusao raramente vem de ma sorte, vem da falta de direcao.",
         "Escreva em uma frase seu objetivo principal para o ano. Se nao conseguir, esse e o primeiro problema a resolver."),
},
"144": {
  "fr": ("Ne te perds pas dans la foule.",
         "Lettres a Lucilius, Lettre 7",
         "Seneque deconseilla a Lucilius de frequenter trop les foules et les spectacles. Non par mepris des gens, mais parce qu'il avait observe que les foules exercent une pression invisible : elles uniformisent, elles aplatissent, elles erodent l'individualite sans qu'on s'en rende compte.",
         "Cette semaine, identifiez une opinion ou une habitude que vous avez adoptee par pression sociale sans vraiment la choisir. Demandez-vous si c'est vraiment la votre."),
  "de": ("Verliere dich nicht in der Menge.",
         "Briefe an Lucilius, Brief 7",
         "Seneca riet Lucilius davon ab, zu viel in Menschenmengen und bei Spektakeln zu verkehren. Nicht aus Verachtung fur Menschen, sondern weil er beobachtet hatte, dass Massen einen unsichtbaren Druck ausuben: Sie vereinheitlichen, glatten und erodieren die Individualitat, ohne dass man es bemerkt.",
         "Identifizieren Sie diese Woche eine Meinung oder Gewohnheit, die Sie durch sozialen Druck ubernommen haben, ohne sie wirklich zu wahlen. Fragen Sie sich, ob sie wirklich Ihre eigene ist."),
  "es": ("No te pierdas en la multitud.",
         "Cartas a Lucilio, Carta 7",
         "Seneca desaconsejo a Lucilio que frecuentara demasiado las multitudes y los espectaculos. No por desprecio hacia la gente, sino porque habia observado que las multitudes ejercen una presion invisible: uniformizan, aplanan, erosionan la individualidad sin que uno se percate.",
         "Esta semana identifica una opinion o habito que adoptaste por presion social sin elegirlo de verdad. Preguntate si realmente es tuyo."),
  "pt": ("Nao te percas na multidao.",
         "Cartas a Lucilio, Carta 7",
         "Seneca desaconselhou Lucilio de frequentar demasiado as multidoes e os espetaculos. Nao por desprezo pelas pessoas, mas porque observou que as multidoes exercem uma pressao invisivel: uniformizam, achatam, corroem a individualidade sem que se perceba.",
         "Esta semana identifique uma opiniao ou habito que adotou por pressao social sem realmente escolher. Pergunte-se se realmente e seu."),
},
"145": {
  "fr": ("Meme en tombant, le grand homme ne lache pas ce qui lui appartient en propre.",
         "Lettres a Lucilius, Lettre 98",
         "Seneque ecrivit a Lucilius qui venait de subir une perte financiere majeure et se sentait dechire. Seneque lui rappela : les biens exterieurs peuvent etre arraches, mais le caractere, la dignite, la sagesse accumulee — cela ne se prend pas. Meme dans la defaite, tu restes toi.",
         "Imaginez que vous perdez votre statut, votre fortune ou votre reputation demain. Qu'est-ce qui resterait intouchable en vous ? C'est cela qui vaut la peine d'etre protege."),
  "de": ("Selbst wenn er fallt, lasst der grosse Mann nicht los, was ihm wirklich gehort.",
         "Briefe an Lucilius, Brief 98",
         "Seneca schrieb an Lucilius, der gerade einen grossen finanziellen Verlust erlitten hatte und sich zerrissen fuhlte. Seneca erinnerte ihn: Aussere Guter konnen gerissen werden, aber Charakter, Wurde, angesammelte Weisheit — das lasst sich nicht nehmen. Auch in der Niederlage bleibst du du.",
         "Stellen Sie sich vor, Sie verlieren morgen Ihren Status, Ihr Vermogen oder Ihren Ruf. Was wurde in Ihnen unberuhrbar bleiben? Das ist es, was es zu schutzen gilt."),
  "es": ("Incluso al caer, el gran hombre no suelta lo que verdaderamente le pertenece.",
         "Cartas a Lucilio, Carta 98",
         "Seneca escribio a Lucilio que acababa de sufrir una gran perdida financiera y se sentia destrozado. Seneca le recordo: los bienes externos pueden ser arrebatados, pero el caracter, la dignidad, la sabiduria acumulada, eso no se quita. Incluso en la derrota, sigues siendo tu.",
         "Imagina que mañana pierdes tu estatus, tu fortuna o tu reputacion. Que permaneceria intocable en ti? Eso es lo que merece ser protegido."),
  "pt": ("Mesmo ao cair, o grande homem nao solta o que verdadeiramente lhe pertence.",
         "Cartas a Lucilio, Carta 98",
         "Seneca escreveu a Lucilio que havia sofrido uma grande perda financeira e se sentia destroçado. Seneca lembrou-lhe: os bens externos podem ser tomados, mas o carater, a dignidade, a sabedoria acumulada, isso nao se tira. Mesmo na derrota, voce continua sendo voce.",
         "Imagine que amanha perde seu status, sua fortuna ou sua reputacao. O que permaneceria intocavel em voce? Isso e o que merece ser protegido."),
},
}

for lang_code in ["fr","de","es","pt"]:
    with open(f'/tmp/new_cards_{lang_code}.json',encoding='utf-8') as f:
        cards=json.load(f)
    updated=0
    for card in cards:
        cid=card['id']
        if cid in T and lang_code in T[cid]:
            q,s,st,a=T[cid][lang_code]
            card['quote']=q;card['source']=s;card['story']=st;card['action']=a;updated+=1
    with open(f'/tmp/new_cards_{lang_code}.json','w',encoding='utf-8') as f:
        json.dump(cards,f,ensure_ascii=False,indent=2)
    print(f"{lang_code}: updated {updated} stoicism cards")
