#!/usr/bin/env python3
import json

T = {}

T["205"] = {
  "fr": ("Le vrai leader est celui qui crée plus de leaders, pas plus de suiveurs.", "Attribué", "Nader a combattu pendant des décennies pour les droits des consommateurs aux États-Unis. Sa principale découverte : les mouvements qui dépendent d'une seule personne s'effondrent avec elle. Les mouvements qui créent des milliers de leaders compétents vivent éternellement. Il ne formait pas des partisans — il créait des organisateurs.", "Pensez à quelqu'un dans votre entourage qui pourrait assumer plus de responsabilités. Que pouvez-vous faire aujourd'hui pour l'aider à grandir ?"),
  "de": ("Der wahre Führer ist derjenige, der mehr Führungspersönlichkeiten schafft, nicht mehr Anhänger.", "Zugeschrieben", "Nader kämpfte jahrzehntelang für Verbraucherrechte in den USA. Seine wichtigste Erkenntnis: Bewegungen, die von einer einzigen Person abhängen, scheitern mit ihr. Bewegungen, die Tausende kompetenter Führungspersönlichkeiten schaffen, leben ewig. Er bildete keine Anhänger aus — er schuf Organisatoren.", "Denken Sie an jemanden in Ihrem Umfeld, der mehr Verantwortung übernehmen könnte. Was können Sie heute tun, um ihm zu helfen zu wachsen?"),
  "es": ("El verdadero líder es aquel que crea más líderes, no más seguidores.", "Atribuido", "Nader luchó durante décadas por los derechos de los consumidores en EE. UU. Su principal descubrimiento: los movimientos que dependen de una sola persona se derrumban con ella. Los movimientos que crean miles de líderes competentes viven eternamente. No formaba seguidores — creaba organizadores.", "Piensa en alguien de tu entorno que podría asumir más responsabilidad. ¿Qué puedes hacer hoy para ayudarle a crecer?"),
  "pt": ("O verdadeiro líder é aquele que cria mais líderes, não mais seguidores.", "Atribuído", "Nader lutou por décadas pelos direitos dos consumidores nos EUA. Sua principal descoberta: movimentos que dependem de uma única pessoa desmoronam com ela. Movimentos que criam milhares de líderes competentes vivem eternamente. Ele não formava seguidores — criava organizadores.", "Pense em alguém no seu círculo que poderia assumir mais responsabilidade. O que você pode fazer hoje para ajudá-lo a crescer?"),
}
T["206"] = {
  "fr": ("Le leadership est une action, pas une position.", "Attribué", "McGannon dirigea Westinghouse Broadcasting dans les années 1960–80, en faisant de lui un modèle de diversité et d'éthique dans le journalisme. Il n'attendait pas l'approbation de ses conseillers — il agissait quand c'était juste. Sa décision la plus célèbre : embaucher la première présentatrice noire en prime time 20 ans avant que cela devienne la norme.", "Identifiez une situation dans votre vie où vous attendez une permission ou un poste pour prendre l'initiative. Faites un pas en avant sans permission — aujourd'hui."),
  "de": ("Führung ist eine Handlung, keine Position.", "Zugeschrieben", "McGannon leitete Westinghouse Broadcasting in den 1960–80er Jahren und machte es zu einem Vorbild für Vielfalt und Ethik im Journalismus. Er wartete nicht auf die Zustimmung von Beratern — er handelte, wenn es richtig war. Seine bekannteste Entscheidung: die erste schwarze Frau als Moderatorin in der Hauptsendezeit einzustellen, 20 Jahre bevor dies zur Norm wurde.", "Identifizieren Sie eine Situation in Ihrem Leben, in der Sie auf eine Erlaubnis oder eine Position warten, um die Initiative zu ergreifen. Machen Sie heute einen Schritt vorwärts ohne Erlaubnis."),
  "es": ("El liderazgo es una acción, no una posición.", "Atribuido", "McGannon dirigió Westinghouse Broadcasting en los años 1960-80, convirtiéndola en un modelo de diversidad y ética en el periodismo. No esperaba la aprobación de sus asesores — actuaba cuando era correcto. Su decisión más famosa: contratar a la primera mujer negra como presentadora en horario de máxima audiencia 20 años antes de que fuera la norma.", "Identifica una situación en tu vida donde estás esperando un permiso o un cargo para tomar la iniciativa. Da un paso adelante sin permiso — hoy."),
  "pt": ("Liderança é ação, não posição.", "Atribuído", "McGannon dirigiu a Westinghouse Broadcasting nos anos 1960–80, tornando-a um modelo de diversidade e ética no jornalismo. Não esperava aprovação dos conselheiros — agia quando era correto. Sua decisão mais famosa: contratar a primeira mulher negra como apresentadora no horário nobre 20 anos antes de isso se tornar norma.", "Identifique uma situação na sua vida onde você está esperando uma permissão ou cargo para tomar iniciativa. Dê um passo à frente sem permissão — hoje."),
}
T["207"] = {
  "fr": ("Les gens suivent le leader avant de suivre sa vision.", "Les 21 lois irréfutables du leadership", "Maxwell a étudié des centaines de leaders et découvert : les idées brillantes ne font pas bouger les gens. Les gens font bouger les gens. Quand Martin Luther King prononçait son discours J'ai un rêve, les gens pleuraient non pas à cause de la force de l'idée — mais à cause de la force de l'homme devant eux.", "Rappelez-vous une situation où vous avez tenté de convaincre des gens d'une idée et avez échoué. Rétrospectivement : vous faisaient-ils suffisamment confiance ? Qu'auriez-vous pu faire pour renforcer la confiance ?"),
  "de": ("Die Menschen folgen dem Führer, bevor sie seiner Vision folgen.", "Die 21 Gesetze der Führung", "Maxwell studierte Hunderte von Führungspersönlichkeiten und entdeckte: Brillante Ideen bewegen Menschen nicht. Menschen bewegen Menschen. Als Martin Luther King seine Rede Ich habe einen Traum hielt, weinten die Menschen nicht wegen der Kraft der Idee — sondern wegen der Kraft des Mannes vor ihnen.", "Erinnern Sie sich an eine Situation, in der Sie versuchten, Menschen von einer Idee zu überzeugen, und scheiterten. Im Rückblick: Vertrauten sie Ihnen genug? Was hätten Sie tun können, um zuerst das Vertrauen zu stärken?"),
  "es": ("Las personas siguen al líder antes de seguir su visión.", "Las 21 leyes irrefutables del liderazgo", "Maxwell estudió a cientos de líderes y descubrió: las ideas brillantes no mueven a la gente. Las personas mueven a las personas. Cuando Martin Luther King pronunciaba su discurso Tengo un sueño, la gente lloraba no por la fuerza de la idea — sino por la fuerza del hombre ante ellos.", "Recuerda una situación en que intentaste convencer a personas de una idea y fracasaste. Mirando atrás: ¿te tenían suficiente confianza? ¿Qué podrías haber hecho para fortalecer primero la confianza?"),
  "pt": ("As pessoas seguem o líder antes de seguir sua visão.", "As 21 Leis da Liderança", "Maxwell estudou centenas de líderes e descobriu: ideias brilhantes não movem pessoas. Pessoas movem pessoas. Quando Martin Luther King pronunciava seu discurso Eu tenho um sonho, as pessoas choravam não pela força da ideia — mas pela força do homem diante delas.", "Lembre-se de uma situação em que tentou convencer pessoas de uma ideia e fracassou. Olhando para trás: elas confiavam suficientemente em você? O que você poderia ter feito para fortalecer primeiro a confiança?"),
}
T["208"] = {
  "fr": ("Les grands leaders n'ont pas peur de paraître vulnérables.", "Les dons de l'imperfection", "Brown a passé 12 ans à étudier la honte et la vulnérabilité. Sa principale conclusion sur les leaders : les plus efficaces parlaient ouvertement de leurs erreurs et doutes. Ce n'est pas une faiblesse — c'est ce qui rend les gens prêts à les suivre. L'armure protège non pas le leader — elle éloigne l'équipe.", "Lors de la prochaine réunion avec votre équipe, admettez une erreur ou une incertitude que vous cachez habituellement. Observez la réaction."),
  "de": ("Große Führungspersönlichkeiten haben keine Angst, verletzlich zu wirken.", "Die Gaben der Unvollkommenheit", "Brown verbrachte 12 Jahre damit, Scham und Verletzlichkeit zu studieren. Ihre wichtigste Schlussfolgerung: Die effektivsten Führungspersönlichkeiten sprachen offen über ihre Fehler und Zweifel. Das ist keine Schwäche — es ist das, was Menschen bereit macht, ihnen zu folgen. Rüstung schützt nicht den Führer — sie entfremdet das Team.", "Gestehen Sie beim nächsten Meeting mit Ihrem Team einen Fehler oder eine Unsicherheit ein, die Sie normalerweise verbergen. Beobachten Sie die Reaktion."),
  "es": ("Los grandes líderes no temen parecer vulnerables.", "Los dones de la imperfección", "Brown pasó 12 años estudiando la vergüenza y la vulnerabilidad. Su principal conclusión sobre los líderes: los más eficaces hablaban abiertamente de sus errores y dudas. No es debilidad — es lo que hace que las personas estén dispuestas a seguirles. La armadura no protege al líder — aleja al equipo.", "En la próxima reunión con tu equipo, admite un error o incertidumbre que normalmente ocultas. Observa la reacción."),
  "pt": ("Grandes líderes não têm medo de parecer vulneráveis.", "Os Presentes da Imperfeição", "Brown passou 12 anos estudando vergonha e vulnerabilidade. Sua principal conclusão sobre líderes: os mais eficazes falavam abertamente sobre seus erros e dúvidas. Isso não é fraqueza — é o que faz as pessoas estarem dispostas a segui-los. A armadura não protege o líder — ela afasta a equipe.", "Na próxima reunião com sua equipe, admita um erro ou incerteza que você normalmente esconde. Observe a reação."),
}
T["209"] = {
  "fr": ("Commander, c'est servir, rien de plus, rien de moins.", "Antimémoires", "Malraux était ministre de la Culture de France sous de Gaulle. Il remarquait : les meilleurs commandants militaires qu'il connaissait entraient les premiers dans le danger et quittaient le champ de bataille les derniers. Leur autorité n'était pas fondée sur le grade — elle était fondée sur le fait qu'ils servaient les hommes qu'ils commandaient.", "Aujourd'hui, faites quelque chose pour votre équipe ou vos proches qui est considéré comme hors de votre niveau. Aidez à une petite tâche, rangez le désordre d'autrui, soutenez discrètement."),
  "de": ("Befehlen bedeutet dienen, nicht mehr und nicht weniger.", "Anti-Memoiren", "Malraux war Kulturminister Frankreichs unter de Gaulle. Er bemerkte: Die besten Militärkommandanten, die er kannte, gingen als Erste in die Gefahr und verließen das Schlachtfeld als Letzte. Ihre Autorität war nicht auf ihrem Rang begründet — sie war darauf begründet, dass sie den Männern dienten, die sie befehligten.", "Tun Sie heute etwas für Ihr Team oder Ihre Nächsten, das gemeinhin als nicht Ihrem Niveau entsprechend gilt. Helfen Sie bei einer kleinen Aufgabe, räumen Sie fremde Unordnung auf, unterstützen Sie unauffällig."),
  "es": ("Mandar es servir, nada más y nada menos.", "Antimemorias", "Malraux fue ministro de Cultura de Francia bajo De Gaulle. Observaba: los mejores comandantes militares que conocía entraban primero en el peligro y eran los últimos en abandonar el campo de batalla. Su autoridad no se basaba en el rango — se basaba en que servían a los hombres a quienes mandaban.", "Hoy, haz algo por tu equipo o tus allegados que normalmente se considera por debajo de tu nivel. Ayuda con una tarea pequeña, recoge el desorden ajeno, apoya discretamente."),
  "pt": ("Comandar é servir, nada mais e nada menos.", "Antimemórias", "Malraux era ministro da Cultura da França sob De Gaulle. Ele observava: os melhores comandantes militares que conhecia eram os primeiros a entrar no perigo e os últimos a deixar o campo de batalha. Sua autoridade não se baseava no posto — baseava-se no fato de servirem os homens que comandavam.", "Hoje, faça algo pela sua equipe ou entes queridos que normalmente é considerado fora do seu nível. Ajude com uma tarefa pequena, organize a bagunça de outro, apoie discretamente."),
}
T["210"] = {
  "fr": ("La plus grande victoire d'un leader, c'est quand en son absence tout fonctionne mieux qu'en sa présence.", "Le Manager efficace", "Drucker conseillait des centaines d'entreprises et élabora le test principal : que se passe-t-il en ton absence ? Si tout s'effondre — tu as créé une dépendance, pas une organisation. Si tout continue de fonctionner — tu as créé un système. Le vrai leadership se rend lui-même inutile.", "Nommez une chose que vous seul faites et que personne d'autre ne peut faire sans vous. C'est une dépendance. Comment pourriez-vous transmettre ce savoir ou cette compétence à quelqu'un d'autre ?"),
  "de": ("Der größte Sieg eines Führers ist, wenn in seiner Abwesenheit alles besser funktioniert als in seiner Anwesenheit.", "Der effektive Führungskraft", "Drucker beriet Hunderte von Unternehmen und entwickelte den Haupttest für einen Führer: Was passiert, wenn du nicht da bist? Wenn alles zusammenbricht — hast du eine Abhängigkeit geschaffen. Wenn alles weiter funktioniert — hast du ein System geschaffen. Wahre Führung macht sich selbst überflüssig.", "Nennen Sie eine Sache, die nur Sie tun und die niemand anderes ohne Sie tun kann. Das ist eine Abhängigkeit. Wie könnten Sie dieses Wissen oder diese Fähigkeit an jemand anderen weitergeben?"),
  "es": ("La mayor victoria de un líder es cuando en su ausencia todo funciona mejor que con él presente.", "El ejecutivo eficaz", "Drucker asesoró a cientos de empresas y desarrolló la prueba principal para un líder: ¿qué pasa cuando no estás? Si todo se derrumba — has creado dependencia. Si todo sigue funcionando — has creado un sistema. El verdadero liderazgo se hace a sí mismo innecesario.", "Nombra una cosa que solo haces tú y que nadie más puede hacer sin ti. Eso es dependencia. ¿Cómo podrías transmitir ese conocimiento o habilidad a alguien más?"),
  "pt": ("A maior vitória de um líder é quando na sua ausência tudo funciona melhor do que na sua presença.", "O Executivo Eficaz", "Drucker assessorou centenas de empresas e desenvolveu o teste principal para um líder: o que acontece quando você não está? Se tudo desmorona — você criou dependência. Se tudo continua funcionando — você criou um sistema. A verdadeira liderança torna-se desnecessária.", "Nomeie uma coisa que só você faz e que ninguém mais consegue fazer sem você. Isso é dependência. Como você poderia transmitir esse conhecimento ou habilidade para outra pessoa?"),
}
T["211"] = {
  "fr": ("Le leader connaît le chemin, marche sur le chemin et montre le chemin.", "Développer les leaders autour de vous", "Maxwell travaillait avec des leaders d'entreprise qui prononçaient de belles discours sur les valeurs, mais étaient les premiers à les enfreindre sous pression. Les équipes le voyaient. L'écart entre les paroles et les actes détruit l'autorité plus vite que n'importe quel échec. Le leader est la carte sur laquelle l'équipe se dirige.", "Identifiez une valeur que vous déclarez mais ne mettez pas toujours en pratique. Aujourd'hui, comportez-vous de manière à ce que vos actions soient entièrement conformes à cette valeur."),
  "de": ("Der Führer kennt den Weg, geht den Weg und zeigt den Weg.", "Führungspersönlichkeiten um Sie herum entwickeln", "Maxwell arbeitete mit Unternehmensleitern, die wunderschöne Reden über Unternehmenswerte hielten, aber unter Druck als Erste dagegen verstießen. Die Teams sahen das. Die Kluft zwischen Worten und Taten zerstört Autorität schneller als jedes Scheitern. Der Führer ist die Karte, an der sich das Team orientiert.", "Identifizieren Sie einen Wert, den Sie deklarieren, aber nicht immer verkörpern. Verhalten Sie sich heute so, dass Ihre Handlungen vollständig mit diesem Wert übereinstimmen."),
  "es": ("El líder conoce el camino, anda el camino y muestra el camino.", "Desarrollar líderes a tu alrededor", "Maxwell trabajaba con líderes corporativos que daban hermosos discursos sobre los valores, pero eran los primeros en incumplirlos bajo presión. Los equipos lo veían. La brecha entre palabras y hechos destruye la autoridad más rápido que cualquier fracaso. El líder es el mapa por el que se orienta el equipo.", "Identifica un valor que declaras pero no siempre encarnas. Hoy, compórtate de manera que tus acciones coincidan completamente con ese valor."),
  "pt": ("O líder conhece o caminho, anda pelo caminho e mostra o caminho.", "Desenvolvendo Líderes ao Seu Redor", "Maxwell trabalhava com líderes corporativos que faziam belos discursos sobre os valores, mas eram os primeiros a violá-los sob pressão. As equipes viam isso. A lacuna entre palavras e ações destrói a autoridade mais rápido do que qualquer fracasso. O líder é o mapa pelo qual a equipe se orienta.", "Identifique um valor que você declara mas nem sempre pratica. Hoje, comporte-se de forma que suas ações coincidam completamente com esse valor."),
}
T["212"] = {
  "fr": ("Le respect se gagne par les actes, pas par les titres.", "Mon chemin américain", "Powell — général quatre étoiles et secrétaire d'État américain — racontait comment au début de sa carrière un jeune lieutenant ne l'écoutait pas à cause de préjugés raciaux. Powell n'a pas fait appel à son poste. Il faisait son travail si bien que le sceptique est venu lui-même lui demander conseil.", "Au lieu de vous référer à votre poste dans la prochaine dispute, laissez vos résultats parler pour vous. Que pouvez-vous faire pour montrer votre compétence en actes ?"),
  "de": ("Respekt wird durch Taten verdient, nicht durch Titel.", "Mein amerikanischer Weg", "Powell — Vier-Sterne-General und US-Außenminister — erzählte, wie am Anfang seiner Karriere ein junger Leutnant ihn aufgrund rassischer Vorurteile nicht auf ihn hörte. Powell berief sich nicht auf seinen Rang. Er machte seine Arbeit so gut, dass der Skeptiker selbst zu ihm kam, um Rat zu bitten.", "Statt sich im nächsten Streit auf Ihre Position zu berufen, lassen Sie Ihre Ergebnisse für Sie sprechen. Was können Sie tun, um Kompetenz durch Taten zu zeigen?"),
  "es": ("El respeto se gana con los actos, no con los títulos.", "Mi camino americano", "Powell — general de cuatro estrellas y secretario de Estado de EE. UU. — contaba que al inicio de su carrera un joven teniente no le escuchaba por prejuicios raciales. Powell no apeló a su cargo. Hacía su trabajo tan bien que el escéptico vino él solo a pedirle consejo.", "En lugar de apelar a tu cargo en la próxima disputa, deja que tus resultados hablen por ti. ¿Qué puedes hacer para demostrar competencia con hechos?"),
  "pt": ("O respeito se conquista pelos atos, não pelos títulos.", "Meu Caminho Americano", "Powell — general de quatro estrelas e secretário de Estado americano — contava que no início da carreira um jovem tenente não o ouvia por preconceito racial. Powell não apelou para seu posto. Fazia seu trabalho tão bem que o cético veio ele mesmo pedir conselho.", "Em vez de apelar ao seu cargo na próxima discussão, deixe seus resultados falarem por você. O que você pode fazer para demonstrar competência com atos?"),
}
T["213"] = {
  "fr": ("La meilleure façon de prédire l'avenir est de le créer.", "Management : tâches, responsabilités, pratiques", "Drucker écrivait cela en 1954, quand la plupart des théories managériales se concentraient sur la réaction. Il a renversé le paradigme : les grandes organisations ne s'adaptent pas à l'avenir, elles le forment. Cela exige de la vision, du courage et le refus d'attendre la permission.", "Écrivez un changement que vous souhaitez voir dans votre domaine. Quelle petite action pouvez-vous entreprendre aujourd'hui pour créer cet avenir ?"),
  "de": ("Der beste Weg, die Zukunft vorherzusagen, ist, sie zu gestalten.", "Management: Aufgaben, Verantwortlichkeiten, Praktiken", "Drucker schrieb dies 1954, als sich die meisten Managementtheorien auf Reaktion konzentrierten. Er kehrte das Paradigma um: Großartige Organisationen passen sich nicht an die Zukunft an, sie gestalten sie. Das erfordert Vision, Mut und die Weigerung, auf Erlaubnis zu warten.", "Schreiben Sie eine Veränderung auf, die Sie in Ihrem Bereich sehen möchten. Welche kleine Maßnahme können Sie heute ergreifen, um diese Zukunft zu gestalten?"),
  "es": ("La mejor manera de predecir el futuro es crearlo.", "Management: tareas, responsabilidades, prácticas", "Drucker escribió esto en 1954, cuando la mayoría de las teorías de gestión se centraban en la reacción. Invirtió el paradigma: las grandes organizaciones no se adaptan al futuro, lo forman. Eso requiere visión, valentía y negarse a esperar permiso.", "Escribe un cambio que deseas ver en tu ámbito. ¿Qué pequeña acción puedes emprender hoy para crear ese futuro?"),
  "pt": ("A melhor maneira de prever o futuro é criá-lo.", "Management: Tarefas, Responsabilidades, Práticas", "Drucker escreveu isso em 1954, quando a maioria das teorias de gestão se concentrava na reação. Ele inverteu o paradigma: grandes organizações não se adaptam ao futuro, elas o moldam. Isso exige visão, coragem e a recusa de esperar permissão.", "Escreva uma mudança que você quer ver no seu campo. Que pequena ação você pode tomar hoje para criar esse futuro?"),
}
T["214"] = {
  "fr": ("Inspirez les autres par l'exemple, pas par les mots.", "Attribué", "Schweitzer était organiste, théologien et philosophe de renommée mondiale. À 38 ans, il abandonna sa carrière et partit comme médecin en Afrique. On ne lui demandait jamais pourquoi il l'avait fait. On lui demandait comment suivre son exemple. L'exemple est le seul discours qui ne peut être réfuté.", "Rappellez-vous une personne qui vous a inspiré par l'exemple. Qu'est-ce qui dans son comportement vous a inspiré ? Comment incarner cela dans vos actions aujourd'hui ?"),
  "de": ("Inspirieren Sie andere durch Ihr Beispiel, nicht durch Worte.", "Zugeschrieben", "Schweitzer war Organist, Theologe und Philosoph von Weltruhm. Mit 38 Jahren gab er seine Karriere auf und ging als Arzt nach Afrika. Man fragte ihn nie, warum er das getan hatte. Man fragte ihn, wie man seinem Beispiel folgen könne. Das Beispiel ist die einzige Rede, die nicht widerlegt werden kann.", "Erinnern Sie sich an jemanden, der Sie durch sein Beispiel inspiriert hat. Was in seinem Verhalten hat Sie inspiriert? Wie können Sie das in Ihren Handlungen heute verkörpern?"),
  "es": ("Inspira a los demás con el ejemplo, no con las palabras.", "Atribuido", "Schweitzer era organista, teólogo y filósofo de renombre mundial. A los 38 años abandonó su carrera y se fue como médico a África. Nunca le preguntaban por qué lo había hecho. Le preguntaban cómo seguir su ejemplo. El ejemplo es el único discurso que no puede ser refutado.", "Recuerda a una persona que te haya inspirado con el ejemplo. ¿Qué en su comportamiento te inspiró? ¿Cómo encarnar eso en tus acciones hoy?"),
  "pt": ("Inspire os outros pelo exemplo, não pelas palavras.", "Atribuído", "Schweitzer era organista, teólogo e filósofo de renome mundial. Aos 38 anos, abandonou a carreira e foi como médico para a África. Nunca lhe perguntavam por que havia feito isso. Perguntavam como seguir o seu exemplo. O exemplo é o único discurso que não pode ser refutado.", "Lembre-se de uma pessoa que o inspirou pelo exemplo. O que no comportamento dela o inspirou? Como incorporar isso em suas ações hoje?"),
}
T["215"] = {
  "fr": ("La force du leader ne réside pas dans le fait de connaître toutes les réponses, mais dans le fait de poser les bonnes questions.", "La cinquième discipline", "Senge étudiait les organisations apprenantes — des entreprises qui s'adaptaient plus vite que leurs concurrents. Ce qui les unissait : les leaders posaient des questions lors des réunions plutôt que de donner des réponses. Cela créait une culture de recherche, pas d'exécution.", "Lors de la prochaine réunion, posez trois questions ouvertes avant d'exprimer votre opinion. Notez les idées qui en émergent."),
  "de": ("Die Stärke eines Führers liegt nicht darin, alle Antworten zu kennen, sondern darin, die richtigen Fragen zu stellen.", "Die fünfte Disziplin", "Senge untersuchte lernende Organisationen — Unternehmen, die sich schneller als Konkurrenten anpassten. Was sie verband: Führer stellten in Meetings Fragen, statt Antworten zu geben. Dies schuf eine Kultur des Suchens, nicht des Ausführens.", "Stellen Sie im nächsten Meeting drei offene Fragen, bevor Sie Ihre Meinung äußern. Notieren Sie die Ideen, die dadurch entstehen."),
  "es": ("La fuerza del líder no está en conocer todas las respuestas, sino en hacer las preguntas correctas.", "La quinta disciplina", "Senge estudiaba las organizaciones que aprenden — empresas que se adaptaban más rápido que sus competidores. Lo que las unía: los líderes hacían preguntas en las reuniones en lugar de dar respuestas. Eso creaba una cultura de búsqueda, no de ejecución.", "En la próxima reunión, haz tres preguntas abiertas antes de expresar tu opinión. Anota las ideas que surjan."),
  "pt": ("A força do líder não está em conhecer todas as respostas, mas em fazer as perguntas certas.", "A Quinta Disciplina", "Senge estudava organizações que aprendem — empresas que se adaptavam mais rápido que os concorrentes. O que as unia: os líderes faziam perguntas nas reuniões em vez de dar respostas. Isso criava uma cultura de busca, não de execução.", "Na próxima reunião, faça três perguntas abertas antes de expressar sua opinião. Anote as ideias que surgem."),
}
T["216"] = {
  "fr": ("Le leadership est la capacité de voir du potentiel là où d'autres voient un problème.", "Sur le leadership", "Gardner était conseiller de plusieurs présidents américains. Il étudiait ce qui distingue les leaders transformateurs des gestionnaires. Réponse : les gestionnaires voient un problème et cherchent une solution. Les leaders voient un problème et voient derrière lui une opportunité de croissance.", "Prenez un problème actuel dans votre vie ou votre travail. Reformulez-le : Comment cette situation pourrait-elle devenir une opportunité ? Écrivez trois réponses possibles."),
  "de": ("Führung ist die Fähigkeit, Potenzial zu sehen, wo andere ein Problem sehen.", "Über Führung", "Gardner war Berater mehrerer US-Präsidenten. Er untersuchte, was transformierende Führungspersönlichkeiten von Managern unterscheidet. Antwort: Manager sehen ein Problem und suchen eine Lösung. Führungspersönlichkeiten sehen ein Problem und sehen dahinter eine Wachstumschance.", "Nehmen Sie ein aktuelles Problem. Formulieren Sie es um: Wie könnte diese Situation eine Chance werden? Schreiben Sie drei mögliche Antworten."),
  "es": ("El liderazgo es la capacidad de ver potencial donde otros ven un problema.", "Sobre el liderazgo", "Gardner fue asesor de varios presidentes de EE. UU. Estudiaba qué distingue a los líderes transformadores de los gestores. Respuesta: los gestores ven un problema y buscan una solución. Los líderes ven un problema y ven detrás de él una oportunidad de crecimiento.", "Toma un problema actual. Reformúlalo: ¿Cómo podría esta situación convertirse en una oportunidad? Escribe tres respuestas posibles."),
  "pt": ("Liderança é a capacidade de enxergar potencial onde outros veem um problema.", "Sobre Liderança", "Gardner foi conselheiro de vários presidentes americanos. Ele estudava o que distingue líderes transformadores de gestores. Resposta: gestores veem um problema e buscam uma solução. Líderes veem um problema e enxergam por trás dele uma oportunidade de crescimento.", "Pegue um problema atual. Reformule-o: Como essa situação poderia se tornar uma oportunidade? Escreva três respostas possíveis."),
}
T["217"] = {
  "fr": ("Les grands leaders écoutent avec l'intention de comprendre, pas avec l'intention de répondre.", "Les 7 habitudes des gens très efficaces", "Covey décrivait une réunion avec le PDG d'une grande entreprise. Celui-ci posa une question à un employé, puis sans attendre la réponse — commença à parler. L'employé se referma. Covey nota : l'écoute simulée est pire que le silence. Elle dit : Tu n'es pas important pour moi.", "Lors de la prochaine conversation importante, fixez-vous comme objectif : écouter 70 % du temps, parler 30 %. Posez des questions de clarification."),
  "de": ("Große Führungspersönlichkeiten hören mit der Absicht zu verstehen, nicht mit der Absicht zu antworten.", "Die 7 Wege zur Effektivität", "Covey beschrieb ein Meeting mit dem CEO eines großen Unternehmens. Dieser stellte einem Mitarbeiter eine Frage und begann dann ohne die Antwort abzuwarten zu sprechen. Der Mitarbeiter schloss sich ab. Covey notierte: Vorgetäuschtes Zuhören ist schlimmer als Schweigen.", "Setzen Sie sich beim nächsten wichtigen Gespräch als Ziel: 70 % der Zeit zuhören, 30 % sprechen. Stellen Sie Verständnisfragen."),
  "es": ("Los grandes líderes escuchan con la intención de comprender, no con la intención de responder.", "Los 7 hábitos de la gente altamente efectiva", "Covey describía una reunión con el CEO de una gran corporación. Este le hizo una pregunta a un empleado y luego sin esperar la respuesta empezó a hablar. El empleado se cerró. Covey anotó: escuchar fingidamente es peor que el silencio.", "En la próxima conversación importante, ponte como objetivo: escuchar el 70 % del tiempo, hablar el 30 %. Haz preguntas aclaratorias."),
  "pt": ("Grandes líderes ouvem com a intenção de entender, não com a intenção de responder.", "Os 7 Hábitos das Pessoas Altamente Eficazes", "Covey descrevia uma reunião com o CEO de uma grande corporação. Ele fez uma pergunta a um funcionário e então sem esperar a resposta começou a falar. O funcionário se fechou. Covey anotou: ouvir fingido é pior que o silêncio.", "Na próxima conversa importante, defina como meta: ouvir 70% do tempo, falar 30%. Faça perguntas de esclarecimento."),
}
T["218"] = {
  "fr": ("La tâche du leader n'est pas d'être en tête de tout le monde, mais de soulever ceux qui sont en retard.", "Un long chemin vers la liberté", "En prison sur l'île Robben, Mandela apprenait à lire aux détenus illettrés. Il était un avocat instruit — mais il consacrait des heures à enseigner l'alphabet à des prisonniers qui n'avaient jamais eu accès à l'éducation. Son leadership n'était pas une position — c'était un service.", "Trouvez aujourd'hui quelqu'un à qui vous pouvez transmettre une connaissance ou une compétence. Prenez 15 à 30 minutes pour lui expliquer quelque chose que vous savez faire."),
  "de": ("Die Aufgabe des Führers ist nicht, vor allen zu stehen, sondern diejenigen zu heben, die zurückliegen.", "Der lange Weg zur Freiheit", "Im Gefängnis auf Robben Island brachte Mandela analphabetischen Gefangenen das Lesen bei. Er war ein gebildeter Anwalt — aber er verbrachte Stunden damit, Gefangenen das Alphabet beizubringen, die nie Zugang zu Bildung hatten. Sein Führungsstil war keine Position — es war Dienst.", "Finden Sie heute jemanden, dem Sie Wissen oder eine Fähigkeit weitergeben können. Nehmen Sie sich 15 bis 30 Minuten Zeit, um etwas zu erklären."),
  "es": ("La tarea del líder no es estar delante de todos, sino elevar a quienes quedan atrás.", "El largo camino hacia la libertad", "En prisión en la isla Robben, Mandela enseñaba a leer a los reclusos analfabetos. Era un abogado instruido — pero dedicaba horas a enseñar el abecedario a prisioneros que nunca habían tenido acceso a la educación. Su liderazgo no era una posición — era un servicio.", "Encuentra hoy a alguien a quien puedas transmitir un conocimiento o habilidad. Dedica 15-30 minutos a explicar algo que sabes hacer."),
  "pt": ("A tarefa do líder não é estar à frente de todos, mas elevar aqueles que ficaram para trás.", "Um Longo Caminho até a Liberdade", "Na prisão na Ilha Robben, Mandela ensinava a ler os presos analfabetos. Era um advogado instruído — mas dedicava horas a ensinar o alfabeto a prisioneiros que nunca tiveram acesso à educação. Sua liderança não era uma posição — era serviço.", "Encontre hoje alguém a quem você possa transmitir um conhecimento ou habilidade. Dedique 15 a 30 minutos para explicar algo que você sabe."),
}
T["219"] = {
  "fr": ("Le charisme n'est pas quelque chose avec lequel on naît. C'est quelque chose qu'on développe par le souci profond des autres.", "L'amour est une arme commerciale mortelle", "Sanders a étudié les biographies de 50 des leaders les plus charismatiques du siècle et découvert : aucun n'était naturellement charismatique. Ce qui les unissait — un intérêt sincère pour les gens autour d'eux. Les gens se sentaient vus et importants. C'est ce qui créait le magnétisme.", "Choisissez une personne de votre entourage et faites quelque chose qui lui montre que vous pensez à elle et vous vous souciez d'elle. Par sincère attention, pas pour obtenir une faveur."),
  "de": ("Charisma ist nichts, womit man geboren wird. Es ist etwas, das man durch tiefe Fürsorge für andere entwickelt.", "Liebe ist eine todbringende Geschäftswaffe", "Sanders studierte die Biografien von 50 der charismatischsten Führungspersönlichkeiten des Jahrhunderts und entdeckte: Keine war von Natur aus charismatisch. Was sie verband — ein aufrichtiges Interesse an den Menschen um sie herum. Die Menschen fühlten sich gesehen und wichtig. Das war es, was Magnetismus schuf.", "Wählen Sie eine Person in Ihrem Umfeld und tun Sie etwas, das ihr zeigt: Sie denken an sie und kümmern sich um sie. Aus aufrichtiger Fürsorge."),
  "es": ("El carisma no es algo con lo que se nace. Es algo que se desarrolla mediante el profundo cuidado de los demás.", "El amor es un arma letal en los negocios", "Sanders estudió las biografías de 50 de los líderes más carismáticos del siglo y descubrió: ninguno era naturalmente carismático. Lo que les unía — un interés sincero por las personas a su alrededor. La gente se sentía vista e importante. Eso era lo que creaba el magnetismo.", "Elige a una persona de tu entorno y haz algo que le demuestre que piensas en ella y te preocupas por ella. Por atención sincera."),
  "pt": ("Carisma não é algo com que se nasce. É algo que se desenvolve por meio do cuidado profundo com os outros.", "O Amor é uma Arma de Negócios Mortal", "Sanders estudou as biografias de 50 dos líderes mais carismáticos do século e descobriu: nenhum deles era naturalmente carismático. O que os unia — um interesse sincero pelas pessoas ao redor. As pessoas se sentiam vistas e importantes. Era isso que criava o magnetismo.", "Escolha uma pessoa no seu círculo e faça algo que mostre a ela que você pensa nela e se preocupa com ela. Por atenção sincera."),
}
T["220"] = {
  "fr": ("L'initiative, c'est faire ce qui est juste sans instructions.", "Un message à Garcia", "Hubbard a écrit Un message à Garcia — un essai sur un officier à qui on avait confié de porter un message à un général partisan dans les jungles cubaines. On ne lui a pas dit comment. Il n'a pas demandé d'aide. Il est parti et a accompli la mission.", "Trouvez une tâche que personne n'a assignée mais qui est manifestement nécessaire. Faites-la sans attendre de louange ou de permission."),
  "de": ("Initiative bedeutet, das Richtige ohne Anweisung zu tun.", "Eine Botschaft an Garcia", "Hubbard schrieb Eine Botschaft an Garcia — ein Essay über einen Offizier, dem aufgetragen wurde, eine Botschaft an einen Guerilla-General im kubanischen Dschungel zu überbringen. Niemand sagte ihm, wie. Er bat nicht um Hilfe. Er ging und erfüllte die Mission.", "Finden Sie eine Aufgabe, die niemand gestellt hat, die aber offensichtlich notwendig ist. Erledigen Sie sie ohne auf Lob oder Erlaubnis zu warten."),
  "es": ("La iniciativa es hacer lo correcto sin instrucciones.", "Un mensaje a García", "Hubbard escribió Un mensaje a García — un ensayo sobre un oficial al que se le encomendó llevar un mensaje a un general guerrillero en las selvas cubanas. No le dijeron cómo. No pidió ayuda. Fue y cumplió la misión.", "Encuentra una tarea que nadie ha asignado pero que es evidentemente necesaria. Hazla sin esperar alabanza ni permiso."),
  "pt": ("Iniciativa é fazer o que é certo sem precisar de instruções.", "Uma Mensagem a Garcia", "Hubbard escreveu Uma Mensagem a Garcia — um ensaio sobre um oficial encarregado de entregar uma mensagem a um general guerrilheiro nas selvas cubanas. Ninguém lhe disse como. Ele não pediu ajuda. Foi e cumpriu a missão.", "Encontre uma tarefa que ninguém atribuiu, mas que é visivelmente necessária. Faça-a sem esperar elogio ou permissão."),
}
T["221"] = {
  "fr": ("On ne peut pas gérer ce qu'on ne peut pas mesurer.", "La pratique du management", "Drucker travaillait avec des entreprises qui fixaient des objectifs vagues. Les équipes ne savaient pas à quoi ressemblait le succès. Il insistait : tout objectif doit avoir une métrique concrète. Sinon c'est une intention, pas un objectif.", "Prenez un objectif immesurable. Reformulez-le avec une métrique concrète. Quelle différence cela fait-il dans votre planification quotidienne ?"),
  "de": ("Man kann nicht managen, was man nicht messen kann.", "Die Praxis des Managements", "Drucker arbeitete mit Unternehmen, die vage Ziele setzten. Die Teams wussten nicht, wie Erfolg aussieht. Er bestand darauf: Jedes Ziel muss eine konkrete Metrik haben. Sonst ist es eine Absicht, kein Ziel.", "Nehmen Sie ein nicht messbares Ziel. Formulieren Sie es mit einer konkreten Metrik um. Welchen Unterschied macht das in Ihrer täglichen Planung?"),
  "es": ("No se puede gestionar lo que no se puede medir.", "La práctica del management", "Drucker trabajaba con empresas que fijaban objetivos vagos. Los equipos no sabían cómo era el éxito. Insistía: todo objetivo debe tener una métrica concreta. De lo contrario es una intención, no un objetivo.", "Toma un objetivo inconmensurable. Reformúlalo con una métrica concreta. ¿Qué diferencia hace en tu planificación diaria?"),
  "pt": ("Não se pode gerir o que não se pode medir.", "A Prática do Management", "Drucker trabalhava com empresas que definiam objetivos vagos. As equipes não sabiam como era o sucesso. Ele insistia: todo objetivo deve ter uma métrica concreta. Caso contrário é uma intenção, não um objetivo.", "Pegue um objetivo impossível de medir. Reformule-o com uma métrica concreta. Que diferença isso faz no seu planejamento diário?"),
}
T["222"] = {
  "fr": ("Le meilleur moment pour prendre une décision est quand vous pouvez encore changer de cap, pas quand vous y êtes obligé.", "Aucune règle. La culture unique de Netflix", "Hastings a migré Netflix des DVD au streaming alors que l'activité DVD était encore très rentable. Tous ses conseillers disaient : Attendez. Il a dit : C'est maintenant ou trop tard. Les entreprises qui attendent que le vieux modèle meure perdent l'élan pour construire le nouveau.", "Nommez un domaine où vous savez qu'il faut changer quelque chose, mais vous le retardez. Quelle serait la décision sage à prendre dès maintenant ?"),
  "de": ("Der beste Zeitpunkt, eine Entscheidung zu treffen, ist dann, wenn man noch den Kurs ändern kann, nicht wenn man es schon muss.", "Keine Regeln. Die einzigartige Kultur von Netflix", "Hastings migrierte Netflix von DVDs zum Streaming, als das DVD-Geschäft noch enormen Gewinn abwarf. Alle Berater sagten: Warten Sie. Er sagte: Jetzt oder nie. Unternehmen, die warten, bis das alte Modell stirbt, verlieren den Schwung, das neue aufzubauen.", "Nennen Sie einen Bereich, in dem Sie wissen, dass etwas geändert werden muss, aber Sie es hinausschieben. Was wäre jetzt die weise Entscheidung?"),
  "es": ("El mejor momento para tomar una decisión es cuando todavía puedes cambiar el rumbo, no cuando ya debes hacerlo.", "Sin reglas. La cultura única de Netflix", "Hastings migró Netflix de los DVD al streaming cuando el negocio de los DVD aún generaba enormes beneficios. Todos sus asesores decían: Espere. Él dijo: Ahora o nunca. Las empresas que esperan a que muera el viejo modelo pierden el impulso para construir el nuevo.", "Nombra un área donde sabes que hay que cambiar algo, pero lo estás postergando. ¿Cuál sería la decisión sabia a tomar ahora?"),
  "pt": ("O melhor momento para tomar uma decisão é quando você ainda pode mudar de curso, não quando já é obrigado.", "Sem Regras. A Cultura Única da Netflix", "Hastings migrou a Netflix de DVDs para streaming quando o negócio de DVDs ainda gerava enormes lucros. Todos os conselheiros diziam: Espere. Ele disse: Agora ou nunca. Empresas que esperam o velho modelo morrer perdem o impulso para construir o novo.", "Nomeie uma área onde você sabe que precisa mudar algo, mas está adiando. Qual seria a decisão sábia a tomar agora?"),
}
T["223"] = {
  "fr": ("Garde tes amis proches — et tes critiques encore plus proches.", "L'art de la guerre", "Sun Tzu enseignait aux généraux : l'ennemi le plus dangereux est celui qu'on ne comprend pas. Comprendre un critique, c'est comprendre ses propres failles. Les dirigeants qui s'entourent de personnes qui ne sont que d'accord vivent dans un mirage — jusqu'à ce que la réalité le brise.", "Trouvez quelqu'un qui est régulièrement en désaccord avec vous. Demandez son avis sur votre prochaine décision importante. Écoutez sans défensive."),
  "de": ("Halte deine Freunde nah — und deine Kritiker noch näher.", "Die Kunst des Krieges", "Sun Tzu lehrte Feldherrn: Der gefährlichste Feind ist derjenige, den man nicht versteht. Einen Kritiker zu verstehen bedeutet, die eigenen Schwächen zu verstehen. Führungspersönlichkeiten, die sich nur mit Ja-Sagern umgeben, leben in einem Trugbild.", "Finden Sie jemanden, der regelmäßig anderer Meinung ist als Sie. Bitten Sie ihn um seine Meinung zu Ihrer nächsten wichtigen Entscheidung. Hören Sie ohne Abwehrhaltung zu."),
  "es": ("Mantén a tus amigos cerca — y a tus críticos aún más cerca.", "El arte de la guerra", "Sun Tzu enseñaba a los generales: el enemigo más peligroso es el que no se entiende. Entender a un crítico es entender las propias debilidades. Los líderes que se rodean solo de quienes están de acuerdo viven en un espejismo.", "Encuentra a alguien que habitualmente no esté de acuerdo contigo. Pide su opinión sobre tu próxima decisión importante. Escucha sin defensas."),
  "pt": ("Mantenha seus amigos perto — e seus críticos ainda mais perto.", "A Arte da Guerra", "Sun Tzu ensinava os generais: o inimigo mais perigoso é aquele que não se compreende. Compreender um crítico é compreender as próprias fraquezas. Líderes que se cercam apenas de quem concorda vivem num espelhismo.", "Encontre alguém que regularmente discorda de você. Peça sua opinião sobre sua próxima decisão importante. Ouça sem defensividade."),
}
T["224"] = {
  "fr": ("La confiance se construit lentement, se détruit rapidement et se rétablit douloureusement.", "La vitesse de la confiance", "En 2001, Johnson & Johnson a retiré tout le Tylenol du marché après un seul cas d'empoisonnement — cela a coûté 100 millions de dollars. La presse les a applaudis. Leur part de marché a récupéré en 6 mois. La confiance est l'actif le plus coûteux et le plus rentable d'une organisation.", "Y a-t-il quelqu'un dont vous avez perdu ou risquez de perdre la confiance ? Quelle action concrète pouvez-vous entreprendre aujourd'hui pour la restaurer ?"),
  "de": ("Vertrauen wird langsam aufgebaut, schnell zerstört und schmerzhaft wiederhergestellt.", "Die Schnelligkeit des Vertrauens", "2001 rief Johnson & Johnson das gesamte Tylenol vom Markt zurück, nachdem es nur einen Vergiftungsfall gegeben hatte — das kostete 100 Millionen Dollar. Die Presse applaudierte ihnen. Ihr Marktanteil erholte sich in 6 Monaten. Vertrauen ist der teuerste und profitabelste Vermögenswert einer Organisation.", "Gibt es jemanden, dessen Vertrauen Sie verloren haben oder zu verlieren riskieren? Welche konkrete Maßnahme können Sie heute ergreifen, um es wiederherzustellen?"),
  "es": ("La confianza se construye despacio, se destruye rápido y se restaura dolorosamente.", "La velocidad de la confianza", "En 2001, Johnson & Johnson retiró todo el Tylenol del mercado tras un solo caso de envenenamiento — eso costó 100 millones de dólares. La prensa los aplaudió. Su cuota de mercado se recuperó en 6 meses. La confianza es el activo más costoso y rentable de una organización.", "¿Hay alguien cuya confianza has perdido o arriesgas perder? ¿Qué acción concreta puedes emprender hoy para restaurarla?"),
  "pt": ("A confiança se constrói lentamente, se destrói rapidamente e se restaura dolorosamente.", "A Velocidade da Confiança", "Em 2001, a Johnson & Johnson retirou todo o Tylenol do mercado após um único caso de envenenamento — isso custou 100 milhões de dólares. A imprensa os aplaudiu. Sua participação de mercado se recuperou em 6 meses. A confiança é o ativo mais caro e mais rentável de uma organização.", "Há alguém cuja confiança você perdeu ou arrisca perder? Que ação concreta você pode tomar hoje para restaurá-la?"),
}
T["225"] = {
  "fr": ("Les leaders voient plus que les autres et avant les autres.", "Attribué", "Abraham Lincoln, alors avocat provincial, croyait en l'abolitionnisme dans les années 1840 — 20 ans avant la Guerre civile. Ses contemporains le considéraient comme un idéaliste naïf. Mais il voyait que l'esclavage était fondamentalement incompatible avec les idéaux de la République. Cette vision précoce façonna chacune de ses décisions ultérieures.", "Écrivez une tendance dans votre domaine qui semble insignifiante maintenant, mais pourrait devenir importante dans 3 à 5 ans. Que pourriez-vous faire aujourd'hui pour vous y préparer ?"),
  "de": ("Führungspersönlichkeiten sehen mehr als andere und früher als andere.", "Zugeschrieben", "Abraham Lincoln, damals Provinzanwalt, glaubte in den 1840er Jahren an den Abolitionismus — 20 Jahre vor dem Bürgerkrieg. Seine Zeitgenossen hielten ihn für einen naiven Idealisten. Aber er sah, dass Sklaverei grundlegend unvereinbar mit den Idealen der Republik war. Diese frühe Vision prägte alle seine späteren Entscheidungen.", "Schreiben Sie eine Tendenz in Ihrem Bereich auf, die jetzt unbedeutend erscheint, aber in 3 bis 5 Jahren wichtig werden könnte. Was könnten Sie heute tun, um sich darauf vorzubereiten?"),
  "es": ("Los líderes ven más que los demás y antes que los demás.", "Atribuido", "Abraham Lincoln, entonces abogado de provincias, creía en el abolicionismo en los años 1840 — 20 años antes de la Guerra Civil. Sus contemporáneos lo consideraban un idealista ingenuo. Pero veía que la esclavitud era fundamentalmente incompatible con los ideales de la República.", "Escribe una tendencia en tu ámbito que parezca insignificante ahora, pero que pueda volverse importante en 3 a 5 años. ¿Qué podrías hacer hoy para prepararte?"),
  "pt": ("Líderes veem mais do que os outros e antes dos outros.", "Atribuído", "Abraham Lincoln, então advogado provincial, acreditava no abolicionismo nos anos 1840 — 20 anos antes da Guerra Civil. Seus contemporâneos o consideravam um idealista ingênuo. Mas ele via que a escravidão era fundamentalmente incompatível com os ideais da República.", "Escreva uma tendência no seu campo que pareça insignificante agora, mas que possa se tornar importante em 3 a 5 anos. O que você poderia fazer hoje para se preparar?"),
}
T["226"] = {
  "fr": ("Le vrai leadership, c'est l'influence, pas le pouvoir.", "Le manager minute", "Blanchard a étudié des milliers de managers. Ceux qui s'appuyaient sur les pouvoirs de leur poste obtenaient la conformité. Ceux qui s'appuyaient sur l'influence obtenaient l'engagement. Les premiers se faisaient obéir. Les seconds inspiraient l'initiative.", "Évaluez : les gens vous suivraient-ils si vous n'aviez pas de poste officiel ? Que pouvez-vous faire pour augmenter votre influence indépendamment de votre titre ?"),
  "de": ("Wahres Führertum ist Einfluss, keine Macht.", "Der Minuten-Manager", "Blanchard studierte Tausende von Managern. Diejenigen, die auf Amtsbefugnisse setzten, erreichten Konformität. Diejenigen, die auf Einfluss setzten, erreichten Engagement. Erstere wurden gehorcht. Letztere inspirierten zur Initiative.", "Bewerten Sie: Würden Ihnen die Menschen folgen, wenn Sie keine offizielle Position hätten? Was können Sie tun, um Ihren Einfluss unabhängig von Ihrem Titel zu erhöhen?"),
  "es": ("El verdadero liderazgo es influencia, no poder.", "El manager al minuto", "Blanchard estudió a miles de managers. Quienes se apoyaban en los poderes de su cargo obtenían conformidad. Quienes se apoyaban en la influencia obtenían compromiso. Los primeros eran obedecidos. Los segundos inspiraban iniciativa.", "Evalúa: ¿te seguiría la gente si no tuvieras un cargo oficial? ¿Qué puedes hacer para aumentar tu influencia independientemente de tu título?"),
  "pt": ("A verdadeira liderança é influência, não poder.", "O Manager Minuto", "Blanchard estudou milhares de gestores. Os que dependiam dos poderes do cargo obtinham conformidade. Os que dependiam da influência obtinham comprometimento. Os primeiros eram obedecidos. Os segundos inspiravam iniciativa.", "Avalie: as pessoas o seguiriam se você não tivesse um cargo oficial? O que você pode fazer para aumentar sua influência independentemente do seu título?"),
}
T["227"] = {
  "fr": ("La médiocrité est l'ennemi du grand. Osez ne pas être d'accord avec la norme.", "De la performance à l'excellence", "Collins a étudié des entreprises qui ont effectué la transition vers un travail exceptionnel. Sa principale découverte : aucune n'y est parvenue en faisant mieux ce que tout le monde faisait. Elles ont toutes trouvé quelque chose où elles pouvaient être les meilleures au monde — et se sont concentrées dessus.", "Nommez un domaine où vous pouvez être le meilleur dans votre niche. Comment pourriez-vous concentrer plus d'énergie sur cela et moins sur ce qui est simplement assez bien ?"),
  "de": ("Mittelmaß ist der Feind des Großen. Wagen Sie es, der Norm zu widersprechen.", "Der Weg zu den Besten", "Collins untersuchte Unternehmen, die den Übergang zur herausragenden Arbeit vollzogen. Seine Haupterkenntnis: Keines schaffte dies, indem es besser tat, was alle taten. Sie alle fanden etwas, worin sie die Besten der Welt sein konnten — und konzentrierten sich ausschließlich darauf.", "Nennen Sie einen Bereich, in dem Sie der Beste in Ihrer Nische sein können. Wie könnten Sie mehr Energie darauf konzentrieren?"),
  "es": ("Lo mediocre es el enemigo de lo grandioso. Atrévete a no estar de acuerdo con la norma.", "De bueno a grandioso", "Collins estudió empresas que realizaron la transición hacia un trabajo extraordinario. Su principal descubrimiento: ninguna lo logró haciendo mejor lo que todos hacían. Todas encontraron algo en lo que podían ser las mejores del mundo — y se concentraron en eso.", "Nombra un área en la que puedas ser el mejor en tu nicho. ¿Cómo podrías concentrar más energía en eso?"),
  "pt": ("A mediocridade é o inimigo do grandioso. Atreva-se a discordar da norma.", "De Bom a Excelente", "Collins estudou empresas que fizeram a transição para um trabalho excepcional. Sua principal descoberta: nenhuma conseguiu isso fazendo melhor o que todos faziam. Todas encontraram algo em que podiam ser as melhores do mundo — e se concentraram nisso.", "Nomeie uma área em que você pode ser o melhor no seu nicho. Como você poderia concentrar mais energia nisso?"),
}
T["228"] = {
  "fr": ("Ne dites pas aux gens comment faire les choses. Dites-leur ce qu'il faut faire et laissez-les vous surprendre par les résultats.", "Déclarations militaires du général Patton", "Patton commandait ses troupes en accordant aux officiers un maximum de liberté tactique. Ses ordres décrivaient le résultat, pas la méthode. Ses officiers prenaient des initiatives que les généraux plus conservateurs n'auraient jamais autorisées.", "La prochaine fois que vous déléguez une tâche, dites quoi et pourquoi, mais pas comment. Donnez à la personne la liberté de trouver sa propre solution."),
  "de": ("Sagen Sie den Leuten nicht, wie sie Dinge tun sollen. Sagen Sie ihnen, was getan werden muss, und lassen Sie sie Sie mit den Ergebnissen überraschen.", "Militärische Aussprüche von General Patton", "Patton befehligte Truppen mit maximaler taktischer Freiheit für die Offiziere. Seine Befehle beschrieben das Ergebnis, nicht die Methode. Seine Offiziere ergriffen Initiativen, die konservativere Generäle nie erlaubt hätten.", "Wenn Sie das nächste Mal eine Aufgabe delegieren, sagen Sie was und warum, aber nicht wie. Geben Sie der Person die Freiheit, ihre eigene Lösung zu finden."),
  "es": ("No les digas a las personas cómo hacer las cosas. Diles qué hay que hacer y déjales sorprenderte con los resultados.", "Declaraciones militares del general Patton", "Patton comandaba tropas dando a los oficiales máxima libertad táctica. Sus órdenes describían el resultado, no el método. Sus oficiales tomaban iniciativas que los generales más conservadores nunca habrían permitido.", "La próxima vez que delegues una tarea, di qué y por qué, pero no cómo. Dale a la persona libertad para encontrar su propia solución."),
  "pt": ("Não diga às pessoas como fazer as coisas. Diga a elas o que precisa ser feito e deixe-as surpreendê-lo com os resultados.", "Declarações Militares do General Patton", "Patton comandava tropas dando aos oficiais máxima liberdade tática. Suas ordens descreviam o resultado, não o método. Seus oficiais tomavam iniciativas que generais mais conservadores jamais teriam permitido.", "Na próxima vez que delegar uma tarefa, diga o quê e por quê, mas não como. Dê à pessoa liberdade para encontrar sua própria solução."),
}
T["229"] = {
  "fr": ("La culture mange la stratégie au petit-déjeuner.", "Attribué", "Ford a dépensé des millions pour développer une stratégie de transformation parfaite dans les années 2000. Elle a échoué. Non pas parce que la stratégie était mauvaise — mais parce que la culture de l'entreprise résistait au changement. La stratégie sans transformation culturelle est un document, pas un changement.", "Nommez une norme culturelle dans votre équipe ou famille qui contredit les valeurs déclarées. Que pouvez-vous faire concrètement pour changer ce comportement par votre propre exemple ?"),
  "de": ("Kultur isst die Strategie zum Frühstück.", "Zugeschrieben", "Ford gab in den 2000er Jahren Millionen aus, um eine perfekte Transformationsstrategie zu entwickeln. Sie scheiterte. Nicht weil die Strategie schlecht war — sondern weil die Unternehmenskultur Veränderungen widerstand. Strategie ohne kulturelle Transformation ist ein Dokument, keine Veränderung.", "Nennen Sie eine kulturelle Norm in Ihrem Team oder Ihrer Familie, die den deklarierten Werten widerspricht. Was können Sie konkret tun, um dieses Verhalten durch Ihr eigenes Beispiel zu ändern?"),
  "es": ("La cultura se come a la estrategia en el desayuno.", "Atribuido", "Ford gastó millones desarrollando una estrategia de transformación perfecta en los años 2000. Fracasó. No porque la estrategia fuera mala — sino porque la cultura de la empresa resistía el cambio. La estrategia sin transformación cultural es un documento, no un cambio.", "Nombra una norma cultural en tu equipo o familia que contradice los valores declarados. ¿Qué puedes hacer concretamente para cambiar ese comportamiento con tu propio ejemplo?"),
  "pt": ("A cultura come a estratégia no café da manhã.", "Atribuído", "A Ford gastou milhões desenvolvendo uma estratégia de transformação perfeita nos anos 2000. Fracassou. Não porque a estratégia fosse ruim — mas porque a cultura da empresa resistia à mudança. Estratégia sem transformação cultural é um documento, não uma mudança.", "Nomeie uma norma cultural na sua equipe ou família que contradiz os valores declarados. O que você pode fazer concretamente para mudar esse comportamento com seu próprio exemplo?"),
}
T["230"] = {
  "fr": ("Le leader crée de l'espace pour les autres, il ne le remplit pas lui-même.", "Leadership et nouvelle science", "Wheatley étudiait les systèmes auto-organisés dans la nature et les affaires. Sa conclusion : les meilleurs leaders ne sont pas le centre — ils créent des conditions dans lesquelles les autres peuvent se développer, innover et prendre des décisions. Plus le leader occupe d'espace, moins les autres en ont.", "Lors de la prochaine réunion, parlez consciemment moins que d'habitude. Créez un espace de silence après une question et laissez les autres le remplir."),
  "de": ("Der Führende schafft Raum für andere, anstatt ihn selbst zu füllen.", "Führung und die neue Wissenschaft", "Wheatley untersuchte selbstorganisierende Systeme in der Natur und im Geschäftsleben. Ihr Fazit: Die besten Führungspersönlichkeiten sind nicht das Zentrum — sie schaffen Bedingungen, unter denen andere wachsen, innovieren und Entscheidungen treffen können.", "Sprechen Sie beim nächsten Meeting bewusst weniger als gewöhnlich. Schaffen Sie nach einer Frage einen Stille-Raum und lassen Sie andere ihn füllen."),
  "es": ("El líder crea espacio para los demás, no lo llena él mismo.", "Liderazgo y la nueva ciencia", "Wheatley estudiaba los sistemas autoorganizados en la naturaleza y los negocios. Su conclusión: los mejores líderes no son el centro — crean condiciones en las que otros pueden crecer, innovar y tomar decisiones.", "En la próxima reunión, habla conscientemente menos de lo habitual. Crea un espacio de silencio tras una pregunta y deja que los demás lo llenen."),
  "pt": ("O líder cria espaço para os outros, não o preenche ele mesmo.", "Liderança e a Nova Ciência", "Wheatley estudava sistemas auto-organizados na natureza e nos negócios. Sua conclusão: os melhores líderes não são o centro — eles criam condições nas quais os outros podem crescer, inovar e tomar decisões.", "Na próxima reunião, fale conscientemente menos do que o habitual. Crie um espaço de silêncio após uma pergunta e deixe os outros preenchê-lo."),
}
T["231"] = {
  "fr": ("Félicitez en public, critiquez en privé.", "Attribué", "Churchill était connu pour ses critiques impitoyables de ses conseillers. Mais toujours en tête-à-tête. En public, il soutenait ses gens même lorsqu'il n'était pas d'accord. Il comprit : critiquer quelqu'un devant les autres détruit son autorité, pas seulement son moral.", "Rappelez-vous si vous avez récemment critiqué quelqu'un devant les autres. Si oui — trouvez un moyen de restaurer leur autorité en public. Et pour l'avenir : critique = tête-à-tête."),
  "de": ("Lobe öffentlich, kritisiere unter vier Augen.", "Zugeschrieben", "Churchill war bekannt für seine schonungslose Kritik an seinen Beratern. Aber immer unter vier Augen. In der Öffentlichkeit unterstützte er seine Leute, selbst wenn er nicht einverstanden war. Er verstand: Jemanden vor anderen zu kritisieren zerstört seine Autorität.", "Überlegen Sie, ob Sie jemanden kürzlich vor anderen kritisiert haben. Wenn ja — finden Sie eine Möglichkeit, seine Autorität in der Öffentlichkeit wiederherzustellen. Kritik = unter vier Augen."),
  "es": ("Elogia en público, critica en privado.", "Atribuido", "Churchill era conocido por sus críticas despiadadas a sus asesores. Pero siempre en privado. En público apoyaba a su gente aunque no estuviera de acuerdo. Comprendió: criticar a alguien ante los demás destruye su autoridad.", "Recuerda si criticaste a alguien delante de otros recientemente. Si es así — encuentra la manera de restaurar su autoridad en público. Crítica = en privado."),
  "pt": ("Elogie em público, critique em privado.", "Atribuído", "Churchill era conhecido por suas críticas implacáveis aos conselheiros. Mas sempre em particular. Em público, apoiava sua equipe mesmo quando discordava. Ele entendeu: criticar alguém diante dos outros destrói sua autoridade.", "Lembre-se se você criticou alguém na frente dos outros recentemente. Se sim — encontre uma forma de restaurar a autoridade dessa pessoa em público. Crítica = em particular."),
}
T["232"] = {
  "fr": ("L'échec n'est qu'une opportunité de recommencer, cette fois de manière plus intelligente.", "Ma vie et mon travail", "Avant de créer Ford Motor Company, Ford a fait faillite deux fois. Sa première entreprise a fermé au bout d'un an. La deuxième — en deux ans. Il avait 40 ans quand il a finalement réussi. Sa règle : ne jamais apprendre la même leçon deux fois.", "Écrivez votre échec professionnel le plus douloureux. En dessous — trois leçons concrètes que vous en avez tirées. Comment ces leçons ont-elles influencé vos décisions actuelles ?"),
  "de": ("Misserfolg ist nur eine Gelegenheit, von vorne anzufangen — diesmal intelligenter.", "Mein Leben und mein Werk", "Bevor er die Ford Motor Company gründete, ging Ford zweimal bankrott. Sein erstes Unternehmen schloss nach einem Jahr. Das zweite — nach zwei Jahren. Er war 40, als er mit Ford endlich Erfolg hatte. Seine Regel: Nie dieselbe Lektion zweimal lernen.", "Schreiben Sie Ihren schmerzhaftesten beruflichen Misserfolg auf. Darunter — drei konkrete Lehren. Wie haben diese Lehren Ihre aktuellen Entscheidungen beeinflusst?"),
  "es": ("El fracaso es solo una oportunidad para empezar de nuevo, esta vez con más inteligencia.", "Mi vida y mi obra", "Antes de crear la Ford Motor Company, Ford quebró dos veces. Su primera empresa cerró al cabo de un año. La segunda — en dos años. Tenía 40 años cuando finalmente triunfó. Su regla: nunca aprender la misma lección dos veces.", "Escribe tu fracaso profesional más doloroso. Debajo — tres lecciones concretas que extrajiste de él. ¿Cómo han influido esas lecciones en tus decisiones actuales?"),
  "pt": ("O fracasso é apenas uma oportunidade de recomeçar, desta vez de forma mais inteligente.", "Minha Vida e Meu Trabalho", "Antes de criar a Ford Motor Company, Ford faliu duas vezes. Sua primeira empresa fechou em um ano. A segunda — em dois anos. Tinha 40 anos quando finalmente teve sucesso. Sua regra: nunca aprender a mesma lição duas vezes.", "Escreva seu fracasso profissional mais doloroso. Abaixo — três lições concretas que você tirou dele. Como essas lições influenciaram suas decisões atuais?"),
}
T["233"] = {
  "fr": ("La vitesse du leader est la vitesse de la meute.", "Attribué", "En 2008, la crise financière frappa le secteur bancaire. Umpqua Bank sous la direction de Davis non seulement survécut — elle crut. Davis était vu chaque jour dans les agences, calmement, confiant, avec un plan. Son énergie était contagieuse. Les employés ont arrêté de paniquer parce que leur leader ne paniquait pas.", "Réfléchissez à votre niveau d'énergie et votre rythme de travail. Que transmettez-vous dans les périodes difficiles : panique ou stabilité ?"),
  "de": ("Die Geschwindigkeit des Führers ist die Geschwindigkeit des Rudels.", "Zugeschrieben", "2008 traf die Finanzkrise die Bankenbranche. Umpqua Bank unter der Leitung von Davis überlebte nicht nur — sie wuchs. Davis wurde täglich in den Filialen gesehen, ruhig, zuversichtlich, mit einem Plan. Seine Energie war ansteckend. Die Mitarbeiter hörten auf zu panikieren, weil ihr Führender nicht panikierte.", "Denken Sie über Ihr Energieniveau und Ihr Arbeitstempo nach. Was vermitteln Sie in schwierigen Zeiten: Panik oder Stabilität?"),
  "es": ("La velocidad del líder es la velocidad de la manada.", "Atribuido", "En 2008, la crisis financiera golpeó al sector bancario. Umpqua Bank bajo la dirección de Davis no solo sobrevivió — creció. Se veía a Davis cada día en las sucursales, calmado, confiado, con un plan. Su energía era contagiosa.", "Reflexiona sobre tu nivel de energía y ritmo de trabajo. ¿Qué transmites en los períodos difíciles: pánico o estabilidad?"),
  "pt": ("A velocidade do líder é a velocidade da matilha.", "Atribuído", "Em 2008, a crise financeira atingiu o setor bancário. O Umpqua Bank sob a liderança de Davis não apenas sobreviveu — cresceu. Davis era visto todos os dias nas agências, calmo, confiante, com um plano. Sua energia era contagiante.", "Reflita sobre seu nível de energia e ritmo de trabalho. O que você transmite nos períodos difíceis: pânico ou estabilidade?"),
}
T["234"] = {
  "fr": ("Si tu es la personne la plus intelligente dans la pièce, tu es dans la mauvaise pièce.", "Attribué", "Feynman — lauréat du prix Nobel de physique — ne cherchait jamais la compagnie de ses égaux en termes de connaissances. Il s'entourait délibérément de personnes qui pensaient différemment. Il disait : enseigner à un débutant est la meilleure façon de comprendre si tu comprends vraiment quelque chose.", "Inscrivez-vous à un événement ou un cours où vous en saurez moins que les autres. Trouvez-y une personne dont vous pouvez apprendre quelque chose."),
  "de": ("Wenn du die klügste Person im Raum bist, bist du im falschen Raum.", "Zugeschrieben", "Feynman — Nobelpreisträger für Physik — suchte nie die Gesellschaft von Seinesgleichen an Wissen. Er umgab sich bewusst mit Menschen, die anders dachten. Er sagte: Einem Anfänger beizubringen ist der beste Weg zu verstehen, ob man selbst wirklich etwas versteht.", "Melden Sie sich für eine Veranstaltung oder einen Kurs an, bei dem Sie weniger wissen als die anderen. Finden Sie dort jemanden, von dem Sie etwas lernen können."),
  "es": ("Si eres la persona más lista de la sala, estás en la sala equivocada.", "Atribuido", "Feynman — Premio Nobel de Física — nunca buscaba la compañía de sus iguales en conocimiento. Se rodeaba deliberadamente de personas que pensaban diferente. Decía: enseñar a un principiante es la mejor manera de comprobar si realmente entiendes algo.", "Apúntate a un evento o curso donde sabrás menos que los demás. Encuentra allí a una persona de la que puedas aprender algo."),
  "pt": ("Se você é a pessoa mais inteligente da sala, está na sala errada.", "Atribuído", "Feynman — Prêmio Nobel de Física — nunca buscava a companhia de seus iguais em conhecimento. Cercava-se deliberadamente de pessoas que pensavam diferente. Dizia: ensinar um iniciante é a melhor maneira de descobrir se você realmente entende algo.", "Inscreva-se em um evento ou curso onde você saberá menos do que os outros. Encontre lá uma pessoa da qual você possa aprender algo."),
}
T["235"] = {
  "fr": ("Ce qui compte n'est pas seulement ce que vous faites — mais ce que vous cessez de faire.", "Le Manager efficace", "Drucker conseillait des PDG qui se plaignaient de manquer de temps. Il leur demandait de noter tout ce qu'ils faisaient pendant une semaine. Invariablement, 40 à 50 % des activités pouvaient être déléguées ou abandonnées. La clé de l'efficacité était dans l'élimination.", "Dressez la liste des tâches de cette semaine. Choisissez trois qui pourraient être déléguées et une dont on peut se passer. Qu'est-ce que cela libérerait ?"),
  "de": ("Wichtig ist nicht nur das, was Sie tun — sondern was Sie aufhören zu tun.", "Der effektive Führungskraft", "Drucker beriet CEOs, die sich über Zeitmangel beklagten. Er bat sie, eine Woche lang alles aufzuschreiben. Ausnahmslos konnten 40 bis 50 % der Aktivitäten delegiert oder ganz aufgegeben werden. Der Schlüssel zu größerer Effizienz lag im Eliminieren.", "Erstellen Sie eine Liste der Aufgaben dieser Woche. Wählen Sie drei, die delegiert werden könnten, und eine, auf die vollständig verzichtet werden kann."),
  "es": ("Lo importante no es solo lo que haces — sino lo que dejas de hacer.", "El ejecutivo eficaz", "Drucker asesoraba a directores ejecutivos que se quejaban de falta de tiempo. Les pedía que anotaran todo lo que hacían durante una semana. Invariablemente, el 40-50 % podía delegarse o abandonarse. La clave de mayor eficiencia estaba en eliminar.", "Haz una lista de las tareas de esta semana. Elige tres que podrían delegarse y una de la que se puede prescindir."),
  "pt": ("O importante não é apenas o que você faz — mas o que você para de fazer.", "O Executivo Eficaz", "Drucker aconselhava CEOs que se queixavam de falta de tempo. Pedia a eles que anotassem tudo que faziam durante uma semana. Invariavelmente, 40 a 50% podiam ser delegadas ou abandonadas. A chave para maior eficiência estava em eliminar.", "Faça uma lista das tarefas desta semana. Escolha três que poderiam ser delegadas e uma da qual se pode prescindir."),
}
T["236"] = {
  "fr": ("Les grandes entreprises n'embauchent pas des gens qualifiés pour les motiver — elles embauchent des gens déjà motivés.", "Commencer par le pourquoi", "Sinek étudiait des entreprises avec un culte de la loyauté — Apple, Southwest Airlines, Harley Davidson. Ce qui les unissait : elles n'embauchaient pas pour les compétences — elles embauchaient pour les valeurs et la mission commune. Les gens qualifiés qui ne croyaient pas à la mission partaient.", "Écrivez le pourquoi de votre travail ou projet — non pas ce que vous faites, mais pourquoi c'est important. Partagez-le avec une personne de votre équipe aujourd'hui."),
  "de": ("Großartige Unternehmen stellen keine qualifizierten Menschen ein, um sie zu motivieren — sie stellen bereits motivierte Menschen ein.", "Fang mit dem Warum an", "Sinek untersuchte Unternehmen mit einem Loyalitätskult — Apple, Southwest Airlines, Harley Davidson. Was sie verband: Sie stellten nicht für Fähigkeiten ein — sie stellten für gemeinsame Werte und Mission ein. Qualifizierte Menschen, die nicht an die Mission glaubten, gingen.", "Schreiben Sie das Warum Ihrer Arbeit oder Ihres Projekts auf — nicht was Sie tun, sondern warum es wichtig ist. Teilen Sie es heute mit einer Person in Ihrem Team."),
  "es": ("Las grandes empresas no contratan personas cualificadas para motivarlas — contratan personas ya motivadas.", "Empieza con el por qué", "Sinek estudiaba empresas con culto a la lealtad — Apple, Southwest Airlines, Harley Davidson. Lo que las unía: no contrataban por habilidades — contrataban por valores y misión compartida. Las personas cualificadas que no creían en la misión se iban.", "Escribe el por qué de tu trabajo o proyecto — no qué haces, sino por qué es importante. Compártelo con una persona de tu equipo hoy."),
  "pt": ("Grandes empresas não contratam pessoas qualificadas para motivá-las — elas contratam pessoas já motivadas.", "Comece Pelo Porquê", "Sinek estudava empresas com culto à lealdade — Apple, Southwest Airlines, Harley Davidson. O que as unia: não contratavam por habilidades — contratavam por valores e missão compartilhada. Pessoas qualificadas que não acreditavam na missão saíam.", "Escreva o porquê do seu trabalho ou projeto — não o que você faz, mas por que é importante. Compartilhe isso com uma pessoa da sua equipe hoje."),
}

# Load and update translation files
for lang_code in ["fr", "de", "es", "pt"]:
    src = f'/tmp/new_cards_{lang_code}.json'
    with open(src, encoding='utf-8') as f:
        cards = json.load(f)
    updated = 0
    for card in cards:
        cid = card['id']
        if cid in T and lang_code in T[cid]:
            q, s, st, a = T[cid][lang_code]
            card['quote'] = q
            card['source'] = s
            card['story'] = st
            card['action'] = a
            updated += 1
    with open(src, 'w', encoding='utf-8') as f:
        json.dump(cards, f, ensure_ascii=False, indent=2)
    print(f"{lang_code}: updated {updated} leadership cards")
